using System.Collections.Generic;
using UnityEngine;

namespace CosmicShore.Gameplay
{
    /// <summary>One prism site of the canonical tile, in the tile's own parameter frame.</summary>
    public readonly struct SchwarzPTileSite
    {
        /// <summary>Offset from the tile's flat point, in surface parameter radians.</summary>
        public readonly Vector3 ParamOffset;

        /// <summary>Unit direction in the surface's tangent plane - the prism's "up".</summary>
        public readonly Vector3 ParamTangent;

        public SchwarzPTileSite(Vector3 paramOffset, Vector3 paramTangent)
        {
            ParamOffset = paramOffset;
            ParamTangent = paramTangent;
        }
    }

    /// <summary>A growth step: the neighbouring site, and which tile it belongs to.</summary>
    public readonly struct SchwarzPBond
    {
        public readonly int Site;
        public readonly Vector3Int TileDelta;

        public SchwarzPBond(int site, Vector3Int tileDelta)
        {
            Site = site;
            TileDelta = tileDelta;
        }
    }

    /// <summary>
    /// The non-Euclidean tile of the Schwarz P minimal surface, and the arithmetic that
    /// lays it out across the surface exactly.
    ///
    /// <para><b>The surface is hyperbolic, so it carries no Euclidean lattice.</b> That is
    /// why the assembler's original approach - step a tangent direction, Newton-project
    /// back onto the zero level set, repeat - could only ever be a QUASI-square array: it
    /// drifts, it never closes up, and it has no repeat unit, so nothing can be baked,
    /// verified, or reasoned about. The surface does carry an exact non-Euclidean tiling,
    /// the hyperbolic <b>{6,4}</b> (hexagons with 90-degree corners, four to a vertex),
    /// and on this surface it is startlingly concrete:</para>
    ///
    /// <para><b>THE TILE IS THE PATCH OF SURFACE INSIDE ONE HALF-PERIOD CUBE.</b></para>
    ///
    /// <para>The {100} mirror planes (x, y, z in pi*Z) cut space into cubes of side pi -
    /// half a period. Each cube contains exactly one FLAT POINT of the surface (Gaussian
    /// curvature 0, normal along a body diagonal), and the patch inside it is one
    /// hyperbolic hexagon: six edges, one on each cube face, every one a planar geodesic
    /// because the face is a mirror; six corners, on the six cube edges whose ends straddle
    /// the surface, every one a 4-fold point lying exactly in the flat point's TANGENT
    /// PLANE at the vertices of a regular hexagon; and six neighbours - the six
    /// face-adjacent cubes.</para>
    ///
    /// <para><b>Tile adjacency is therefore simple-cubic adjacency</b>, so a tile is keyed
    /// by a <see cref="Vector3Int"/> and occupancy is exact integer bookkeeping. There is
    /// no float quantization anywhere in the growth path, and no iterative projection: a
    /// site's position is integer arithmetic on a baked offset.</para>
    ///
    /// <para>Each hexagon is 12 copies of the <b>*246 Schwarz triangle</b> - measured
    /// (30, 45, 90) degrees, the signature of the triangle group the P surface's symmetry
    /// quotients onto - whose corners are the flat point (order 6), a tile corner (order 4)
    /// and a tile edge midpoint (order 2). Per cubic unit cell the tiling closes at F=8,
    /// E=24, V=12, Euler characteristic -4: genus 3, exactly as the P surface must be.</para>
    ///
    /// <para><b>Adjacent tiles are MIRROR IMAGES across their shared cube face</b>, so tile
    /// (i,j,k) is the canonical tile carried by T_ijk, which acts one axis at a time:
    /// <c>x -> x + pi*i</c> when i is even, <c>x -> pi*(i+1) - x</c> when i is odd. The
    /// implicit function is invariant under every T_ijk, so the whole surface is one baked
    /// patch plus a sign flip per odd axis (<see cref="AxisSigns"/>).</para>
    ///
    /// <para><b>No rotation is ever baked.</b> Half of the T_ijk are reflections, and a
    /// baked quaternion carried through one is silently wrong - the failure that cost the
    /// gyroid's seed rotations five playtests (Docs/ECOSYSTEM.md 32.7). Positions and
    /// tangents are vectors and transform correctly under a reflection; the surface normal
    /// is recomputed from the closed-form gradient at the transformed point
    /// (<see cref="SurfaceNormalParam"/>), so orientation is derived, never carried.</para>
    ///
    /// <para>Measured and regenerated by <c>Tools/Build/measure_schwarz_p_tile.py</c>
    /// (<c>--check</c> verifies, <c>--write</c> rewrites the table below). Design record:
    /// Docs/ECOSYSTEM.md 34.</para>
    /// </summary>
    public static class SchwarzPTileData
    {
        /// <summary>Edge of one tile's cube in parameter space: half a period.</summary>
        public const float TileParamSize = Mathf.PI;

        /// <summary>One full period of the surface in parameter space.</summary>
        public const float ParamPeriod = 2f * Mathf.PI;

        /// <summary>
        /// Neighbours are every site within this multiple of a site's own nearest-neighbour
        /// distance. On the measured layouts it selects the shell of touching sites and
        /// stops before the next one.
        /// </summary>
        const float BondRadiusFactor = 1.45f;

        public readonly struct TileSite
        {
            public readonly Vector3 Offset;
            public readonly Vector3 Tangent;
            public TileSite(Vector3 offset, Vector3 tangent) { Offset = offset; Tangent = tangent; }
        }

        public readonly struct TileLevel
        {
            public readonly float MeanParamSpacing;
            public readonly TileSite[] Sites;
            public TileLevel(float meanParamSpacing, TileSite[] sites)
            {
                MeanParamSpacing = meanParamSpacing;
                Sites = sites;
            }
        }

        // <<< MEASURED TABLE BEGIN
        // ---- MEASURED by Tools/Build/measure_schwarz_p_tile.py. Do not hand-edit,
        // and never derive one level from another by a symmetry ansatz - that is the
        // mistake the gyroid's seed rotations paid five playtests for
        // (Docs/ECOSYSTEM.md 32.7). Regenerate with --write instead.
        /// <summary>Area of one tile patch in parameter space (radians squared).</summary>
        public const float TilePatchParamArea = 11.578917f;

        static readonly TileLevel[] LevelTable =
        {
            // level 0: 6 sites, mean spacing 1.2254 rad (1.2254..1.2254)
            new TileLevel(1.225350f, new[]
            {
                new TileSite(new Vector3(-0.9581211f, 0.9581211f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-0.9581211f, 0.0000000f, 0.9581211f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -0.9581211f, 0.9581211f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.9581211f, -0.9581211f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(0.9581211f, 0.0000000f, -0.9581211f), new Vector3(0.7071068f, -0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 0.9581211f, -0.9581211f), new Vector3(-0.0000000f, 0.7071068f, -0.7071068f)),
            }),
            // level 1: 18 sites, mean spacing 0.7607 rad (0.6902..0.8132)
            new TileLevel(0.760692f, new[]
            {
                new TileSite(new Vector3(-0.5833442f, 0.0000000f, 0.5833442f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -0.5833442f, 0.5833442f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.5833442f, -0.5833442f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(0.5833442f, 0.0000000f, -0.5833442f), new Vector3(0.7071068f, -0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 0.5833442f, -0.5833442f), new Vector3(-0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-0.5833442f, 0.5833442f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-1.2256769f, 0.4898772f, 0.4898772f), new Vector3(-0.9651601f, 0.1850215f, 0.1850215f)),
                new TileSite(new Vector3(-0.4898772f, -0.4898772f, 1.2256769f), new Vector3(-0.1850215f, -0.1850215f, 0.9651601f)),
                new TileSite(new Vector3(0.4898772f, -1.2256769f, 0.4898772f), new Vector3(0.1850215f, -0.9651601f, 0.1850215f)),
                new TileSite(new Vector3(1.2256769f, -0.4898772f, -0.4898772f), new Vector3(0.9651601f, -0.1850215f, -0.1850215f)),
                new TileSite(new Vector3(0.4898772f, 0.4898772f, -1.2256769f), new Vector3(0.1850215f, 0.1850215f, -0.9651601f)),
                new TileSite(new Vector3(-0.4898772f, 1.2256769f, -0.4898772f), new Vector3(-0.1850215f, 0.9651601f, -0.1850215f)),
                new TileSite(new Vector3(-1.1814823f, 1.1814823f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-1.1814823f, 0.0000000f, 1.1814823f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -1.1814823f, 1.1814823f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(1.1814823f, -1.1814823f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(1.1814823f, 0.0000000f, -1.1814823f), new Vector3(0.7071068f, -0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 1.1814823f, -1.1814823f), new Vector3(-0.0000000f, 0.7071068f, -0.7071068f)),
            }),
            // level 2: 36 sites, mean spacing 0.5497 rad (0.4888..0.5950)
            new TileLevel(0.549740f, new[]
            {
                new TileSite(new Vector3(-0.4240066f, 0.0000000f, 0.4240066f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -0.4240066f, 0.4240066f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.4240066f, -0.4240066f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, 0.0000000f)),
                new TileSite(new Vector3(0.4240066f, 0.0000000f, -0.4240066f), new Vector3(0.7071068f, 0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 0.4240066f, -0.4240066f), new Vector3(0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-0.4240066f, 0.4240066f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-0.8702653f, 0.3922300f, 0.3922300f), new Vector3(-0.8968256f, 0.3128129f, 0.3128129f)),
                new TileSite(new Vector3(-0.3922300f, -0.3922300f, 0.8702653f), new Vector3(-0.3128129f, -0.3128129f, 0.8968256f)),
                new TileSite(new Vector3(0.3922300f, -0.8702653f, 0.3922300f), new Vector3(0.3128129f, -0.8968256f, 0.3128129f)),
                new TileSite(new Vector3(0.8702653f, -0.3922300f, -0.3922300f), new Vector3(0.8968256f, -0.3128129f, -0.3128129f)),
                new TileSite(new Vector3(0.3922300f, 0.3922300f, -0.8702653f), new Vector3(0.3128129f, 0.3128129f, -0.8968256f)),
                new TileSite(new Vector3(-0.3922300f, 0.8702653f, -0.3922300f), new Vector3(-0.3128129f, 0.8968256f, -0.3128129f)),
                new TileSite(new Vector3(-0.8480618f, -0.0000000f, 0.8480618f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(-0.0000000f, -0.8480618f, 0.8480618f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.8480618f, -0.8480618f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, 0.0000000f)),
                new TileSite(new Vector3(0.8480618f, 0.0000000f, -0.8480618f), new Vector3(0.7071068f, 0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 0.8480618f, -0.8480618f), new Vector3(0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-0.8480618f, 0.8480618f, -0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-1.3264101f, 0.7444400f, 0.2970765f), new Vector3(-0.9429802f, 0.3324113f, -0.0170607f)),
                new TileSite(new Vector3(-1.3264101f, 0.2970765f, 0.7444400f), new Vector3(-0.9429802f, -0.0170607f, 0.3324113f)),
                new TileSite(new Vector3(-0.7444400f, -0.2970765f, 1.3264101f), new Vector3(-0.3324113f, 0.0170607f, 0.9429802f)),
                new TileSite(new Vector3(-0.2970765f, -0.7444400f, 1.3264101f), new Vector3(0.0170607f, -0.3324113f, 0.9429802f)),
                new TileSite(new Vector3(0.2970765f, -1.3264101f, 0.7444400f), new Vector3(-0.0170607f, -0.9429802f, 0.3324113f)),
                new TileSite(new Vector3(0.7444400f, -1.3264101f, 0.2970765f), new Vector3(0.3324113f, -0.9429802f, -0.0170607f)),
                new TileSite(new Vector3(1.3264101f, -0.7444400f, -0.2970765f), new Vector3(0.9429802f, -0.3324113f, 0.0170607f)),
                new TileSite(new Vector3(1.3264101f, -0.2970765f, -0.7444400f), new Vector3(0.9429802f, 0.0170607f, -0.3324113f)),
                new TileSite(new Vector3(0.7444400f, 0.2970765f, -1.3264101f), new Vector3(0.3324113f, -0.0170607f, -0.9429802f)),
                new TileSite(new Vector3(0.2970765f, 0.7444400f, -1.3264101f), new Vector3(-0.0170607f, 0.3324113f, -0.9429802f)),
                new TileSite(new Vector3(-0.2970765f, 1.3264101f, -0.7444400f), new Vector3(0.0170607f, 0.9429802f, -0.3324113f)),
                new TileSite(new Vector3(-0.7444400f, 1.3264101f, -0.2970765f), new Vector3(-0.3324113f, 0.9429802f, 0.0170607f)),
                new TileSite(new Vector3(-1.2861609f, -0.0000000f, 1.2861609f), new Vector3(-0.7071068f, 0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(-0.0000000f, -1.2861609f, 1.2861609f), new Vector3(0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(1.2861609f, -1.2861609f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(1.2861609f, 0.0000000f, -1.2861609f), new Vector3(0.7071068f, -0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 1.2861609f, -1.2861609f), new Vector3(-0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-1.2861609f, 1.2861609f, -0.0000000f), new Vector3(-0.7071068f, 0.7071068f, 0.0000000f)),
            }),
            // level 3: 60 sites, mean spacing 0.4313 rad (0.3800..0.4596)
            new TileLevel(0.431332f, new[]
            {
                new TileSite(new Vector3(-0.3260110f, -0.0000000f, 0.3260110f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(-0.0000000f, -0.3260110f, 0.3260110f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.3260110f, -0.3260110f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, 0.0000000f)),
                new TileSite(new Vector3(0.3260110f, 0.0000000f, -0.3260110f), new Vector3(0.7071068f, 0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 0.3260110f, -0.3260110f), new Vector3(0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-0.3260110f, 0.3260110f, -0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-0.6625936f, 0.3126507f, 0.3126507f), new Vector3(-0.8628190f, 0.3574517f, 0.3574517f)),
                new TileSite(new Vector3(-0.3126507f, -0.3126507f, 0.6625936f), new Vector3(-0.3574517f, -0.3574517f, 0.8628190f)),
                new TileSite(new Vector3(0.3126507f, -0.6625936f, 0.3126507f), new Vector3(0.3574517f, -0.8628190f, 0.3574517f)),
                new TileSite(new Vector3(0.6625936f, -0.3126507f, -0.3126507f), new Vector3(0.8628190f, -0.3574517f, -0.3574517f)),
                new TileSite(new Vector3(0.3126507f, 0.3126507f, -0.6625936f), new Vector3(0.3574517f, 0.3574517f, -0.8628190f)),
                new TileSite(new Vector3(-0.3126507f, 0.6625936f, -0.3126507f), new Vector3(-0.3574517f, 0.8628190f, -0.3574517f)),
                new TileSite(new Vector3(-0.6543303f, -0.0000000f, 0.6543303f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(-0.0000000f, -0.6543303f, 0.6543303f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.6543303f, -0.6543303f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, 0.0000000f)),
                new TileSite(new Vector3(0.6543303f, 0.0000000f, -0.6543303f), new Vector3(0.7071068f, 0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 0.6543303f, -0.6543303f), new Vector3(0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-0.6543303f, 0.6543303f, -0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-1.0152289f, 0.6148581f, 0.2762593f), new Vector3(-0.8956501f, 0.4253878f, 0.1298313f)),
                new TileSite(new Vector3(-1.0152289f, 0.2762593f, 0.6148581f), new Vector3(-0.8956501f, 0.1298313f, 0.4253878f)),
                new TileSite(new Vector3(-0.6148581f, -0.2762593f, 1.0152289f), new Vector3(-0.4253878f, -0.1298313f, 0.8956501f)),
                new TileSite(new Vector3(-0.2762593f, -0.6148581f, 1.0152289f), new Vector3(-0.1298313f, -0.4253878f, 0.8956501f)),
                new TileSite(new Vector3(0.2762593f, -1.0152289f, 0.6148581f), new Vector3(0.1298313f, -0.8956501f, 0.4253878f)),
                new TileSite(new Vector3(0.6148581f, -1.0152289f, 0.2762593f), new Vector3(0.4253878f, -0.8956501f, 0.1298313f)),
                new TileSite(new Vector3(1.0152289f, -0.6148581f, -0.2762593f), new Vector3(0.8956501f, -0.4253878f, -0.1298313f)),
                new TileSite(new Vector3(1.0152289f, -0.2762593f, -0.6148581f), new Vector3(0.8956501f, -0.1298313f, -0.4253878f)),
                new TileSite(new Vector3(0.6148581f, 0.2762593f, -1.0152289f), new Vector3(0.4253878f, 0.1298313f, -0.8956501f)),
                new TileSite(new Vector3(0.2762593f, 0.6148581f, -1.0152289f), new Vector3(0.1298313f, 0.4253878f, -0.8956501f)),
                new TileSite(new Vector3(-0.2762593f, 1.0152289f, -0.6148581f), new Vector3(-0.1298313f, 0.8956501f, -0.4253878f)),
                new TileSite(new Vector3(-0.6148581f, 1.0152289f, -0.2762593f), new Vector3(-0.4253878f, 0.8956501f, -0.1298313f)),
                new TileSite(new Vector3(-0.9912864f, 0.9912864f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-0.9912864f, 0.0000000f, 0.9912864f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -0.9912864f, 0.9912864f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.9912864f, -0.9912864f, -0.0000000f), new Vector3(0.7071068f, -0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(0.9912864f, -0.0000000f, -0.9912864f), new Vector3(0.7071068f, -0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(-0.0000000f, 0.9912864f, -0.9912864f), new Vector3(-0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-1.3807751f, 0.5132374f, 0.5132374f), new Vector3(-0.9884511f, 0.1071551f, 0.1071551f)),
                new TileSite(new Vector3(-0.5132374f, -0.5132374f, 1.3807751f), new Vector3(-0.1071551f, -0.1071551f, 0.9884511f)),
                new TileSite(new Vector3(0.5132374f, -1.3807751f, 0.5132374f), new Vector3(0.1071551f, -0.9884511f, 0.1071551f)),
                new TileSite(new Vector3(1.3807751f, -0.5132374f, -0.5132374f), new Vector3(0.9884511f, -0.1071551f, -0.1071551f)),
                new TileSite(new Vector3(0.5132374f, 0.5132374f, -1.3807751f), new Vector3(0.1071551f, 0.1071551f, -0.9884511f)),
                new TileSite(new Vector3(-0.5132374f, 1.3807751f, -0.5132374f), new Vector3(-0.1071551f, 0.9884511f, -0.1071551f)),
                new TileSite(new Vector3(-1.3800666f, 0.9017361f, 0.1987675f), new Vector3(-0.9009776f, 0.4236078f, -0.0937857f)),
                new TileSite(new Vector3(-1.3800666f, 0.1987675f, 0.9017361f), new Vector3(-0.9009776f, -0.0937857f, 0.4236078f)),
                new TileSite(new Vector3(-0.9017361f, -0.1987675f, 1.3800666f), new Vector3(-0.4236078f, 0.0937857f, 0.9009776f)),
                new TileSite(new Vector3(-0.1987675f, -0.9017361f, 1.3800666f), new Vector3(0.0937857f, -0.4236078f, 0.9009776f)),
                new TileSite(new Vector3(0.1987675f, -1.3800666f, 0.9017361f), new Vector3(-0.0937857f, -0.9009776f, 0.4236078f)),
                new TileSite(new Vector3(0.9017361f, -1.3800666f, 0.1987675f), new Vector3(0.4236078f, -0.9009776f, -0.0937857f)),
                new TileSite(new Vector3(1.3800666f, -0.9017361f, -0.1987675f), new Vector3(0.9009776f, -0.4236078f, 0.0937857f)),
                new TileSite(new Vector3(1.3800666f, -0.1987675f, -0.9017361f), new Vector3(0.9009776f, 0.0937857f, -0.4236078f)),
                new TileSite(new Vector3(0.9017361f, 0.1987675f, -1.3800666f), new Vector3(0.4236078f, -0.0937857f, -0.9009776f)),
                new TileSite(new Vector3(0.1987675f, 0.9017361f, -1.3800666f), new Vector3(-0.0937857f, 0.4236078f, -0.9009776f)),
                new TileSite(new Vector3(-0.1987675f, 1.3800666f, -0.9017361f), new Vector3(0.0937857f, 0.9009776f, -0.4236078f)),
                new TileSite(new Vector3(-0.9017361f, 1.3800666f, -0.1987675f), new Vector3(-0.4236078f, 0.9009776f, 0.0937857f)),
                new TileSite(new Vector3(-1.3435042f, 1.3435042f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-1.3435042f, 0.0000000f, 1.3435042f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -1.3435042f, 1.3435042f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(1.3435042f, -1.3435042f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, 0.0000000f)),
                new TileSite(new Vector3(1.3435042f, 0.0000000f, -1.3435042f), new Vector3(0.7071068f, 0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 1.3435042f, -1.3435042f), new Vector3(0.0000000f, 0.7071068f, -0.7071068f)),
            }),
            // level 4: 90 sites, mean spacing 0.3552 rad (0.3111..0.3800)
            new TileLevel(0.355172f, new[]
            {
                new TileSite(new Vector3(-0.2673885f, 0.2673885f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, 0.0000000f)),
                new TileSite(new Vector3(-0.2673885f, 0.0000000f, 0.2673885f), new Vector3(-0.7071068f, 0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -0.2673885f, 0.2673885f), new Vector3(0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.2673885f, -0.2673885f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(0.2673885f, 0.0000000f, -0.2673885f), new Vector3(0.7071068f, -0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 0.2673885f, -0.2673885f), new Vector3(-0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-0.5324690f, 0.2566390f, 0.2566390f), new Vector3(-0.8461524f, 0.3768462f, 0.3768462f)),
                new TileSite(new Vector3(-0.2566390f, -0.2566390f, 0.5324690f), new Vector3(-0.3768462f, -0.3768462f, 0.8461524f)),
                new TileSite(new Vector3(0.2566390f, -0.5324690f, 0.2566390f), new Vector3(0.3768462f, -0.8461524f, 0.3768462f)),
                new TileSite(new Vector3(0.5324690f, -0.2566390f, -0.2566390f), new Vector3(0.8461524f, -0.3768462f, -0.3768462f)),
                new TileSite(new Vector3(0.2566390f, 0.2566390f, -0.5324690f), new Vector3(0.3768462f, 0.3768462f, -0.8461524f)),
                new TileSite(new Vector3(-0.2566390f, 0.5324690f, -0.2566390f), new Vector3(-0.3768462f, 0.8461524f, -0.3768462f)),
                new TileSite(new Vector3(-0.5322005f, -0.0000000f, 0.5322005f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(-0.0000000f, -0.5322005f, 0.5322005f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.5322005f, -0.5322005f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, 0.0000000f)),
                new TileSite(new Vector3(0.5322005f, 0.0000000f, -0.5322005f), new Vector3(0.7071068f, 0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 0.5322005f, -0.5322005f), new Vector3(0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-0.5322005f, 0.5322005f, -0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-0.8143592f, 0.5103997f, 0.2410887f), new Vector3(-0.8631902f, 0.4679045f, 0.1896525f)),
                new TileSite(new Vector3(-0.8143592f, 0.2410887f, 0.5103997f), new Vector3(-0.8631902f, 0.1896525f, 0.4679045f)),
                new TileSite(new Vector3(-0.5103997f, -0.2410887f, 0.8143592f), new Vector3(-0.4679045f, -0.1896525f, 0.8631902f)),
                new TileSite(new Vector3(-0.2410887f, -0.5103997f, 0.8143592f), new Vector3(-0.1896525f, -0.4679045f, 0.8631902f)),
                new TileSite(new Vector3(0.2410887f, -0.8143592f, 0.5103997f), new Vector3(0.1896525f, -0.8631902f, 0.4679045f)),
                new TileSite(new Vector3(0.5103997f, -0.8143592f, 0.2410887f), new Vector3(0.4679045f, -0.8631902f, 0.1896525f)),
                new TileSite(new Vector3(0.8143592f, -0.5103997f, -0.2410887f), new Vector3(0.8631902f, -0.4679045f, -0.1896525f)),
                new TileSite(new Vector3(0.8143592f, -0.2410887f, -0.5103997f), new Vector3(0.8631902f, -0.1896525f, -0.4679045f)),
                new TileSite(new Vector3(0.5103997f, 0.2410887f, -0.8143592f), new Vector3(0.4679045f, 0.1896525f, -0.8631902f)),
                new TileSite(new Vector3(0.2410887f, 0.5103997f, -0.8143592f), new Vector3(0.1896525f, 0.4679045f, -0.8631902f)),
                new TileSite(new Vector3(-0.2410887f, 0.8143592f, -0.5103997f), new Vector3(-0.1896525f, 0.8631902f, -0.4679045f)),
                new TileSite(new Vector3(-0.5103997f, 0.8143592f, -0.2410887f), new Vector3(-0.4679045f, 0.8631902f, -0.1896525f)),
                new TileSite(new Vector3(-0.8073054f, 0.0000000f, 0.8073054f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -0.8073054f, 0.8073054f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(0.8073054f, -0.8073054f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(0.8073054f, 0.0000000f, -0.8073054f), new Vector3(0.7071068f, -0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 0.8073054f, -0.8073054f), new Vector3(-0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-0.8073054f, 0.8073054f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-1.1126400f, 0.4650134f, 0.4650134f), new Vector3(-0.9438865f, 0.2335362f, 0.2335362f)),
                new TileSite(new Vector3(-0.4650134f, -0.4650134f, 1.1126400f), new Vector3(-0.2335362f, -0.2335362f, 0.9438865f)),
                new TileSite(new Vector3(0.4650134f, -1.1126400f, 0.4650134f), new Vector3(0.2335362f, -0.9438865f, 0.2335362f)),
                new TileSite(new Vector3(1.1126400f, -0.4650134f, -0.4650134f), new Vector3(0.9438865f, -0.2335362f, -0.2335362f)),
                new TileSite(new Vector3(0.4650134f, 0.4650134f, -1.1126400f), new Vector3(0.2335362f, 0.2335362f, -0.9438865f)),
                new TileSite(new Vector3(-0.4650134f, 1.1126400f, -0.4650134f), new Vector3(-0.2335362f, 0.9438865f, -0.2335362f)),
                new TileSite(new Vector3(-1.1118835f, 0.7586469f, 0.2101377f), new Vector3(-0.8770135f, 0.4786221f, 0.0420506f)),
                new TileSite(new Vector3(-1.1118835f, 0.2101377f, 0.7586469f), new Vector3(-0.8770135f, 0.0420506f, 0.4786221f)),
                new TileSite(new Vector3(-0.7586469f, -0.2101377f, 1.1118835f), new Vector3(-0.4786221f, -0.0420506f, 0.8770135f)),
                new TileSite(new Vector3(-0.2101377f, -0.7586469f, 1.1118835f), new Vector3(-0.0420506f, -0.4786221f, 0.8770135f)),
                new TileSite(new Vector3(0.2101377f, -1.1118835f, 0.7586469f), new Vector3(0.0420506f, -0.8770135f, 0.4786221f)),
                new TileSite(new Vector3(0.7586469f, -1.1118835f, 0.2101377f), new Vector3(0.4786221f, -0.8770135f, 0.0420506f)),
                new TileSite(new Vector3(1.1118835f, -0.7586469f, -0.2101377f), new Vector3(0.8770135f, -0.4786221f, -0.0420506f)),
                new TileSite(new Vector3(1.1118835f, -0.2101377f, -0.7586469f), new Vector3(0.8770135f, -0.0420506f, -0.4786221f)),
                new TileSite(new Vector3(0.7586469f, 0.2101377f, -1.1118835f), new Vector3(0.4786221f, 0.0420506f, -0.8770135f)),
                new TileSite(new Vector3(0.2101377f, 0.7586469f, -1.1118835f), new Vector3(0.0420506f, 0.4786221f, -0.8770135f)),
                new TileSite(new Vector3(-0.2101377f, 1.1118835f, -0.7586469f), new Vector3(-0.0420506f, 0.8770135f, -0.4786221f)),
                new TileSite(new Vector3(-0.7586469f, 1.1118835f, -0.2101377f), new Vector3(-0.4786221f, 0.8770135f, -0.0420506f)),
                new TileSite(new Vector3(-1.0832594f, 1.0832594f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(-1.0832594f, 0.0000000f, 1.0832594f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -1.0832594f, 1.0832594f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(1.0832594f, -1.0832594f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, 0.0000000f)),
                new TileSite(new Vector3(1.0832594f, 0.0000000f, -1.0832594f), new Vector3(0.7071068f, 0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 1.0832594f, -1.0832594f), new Vector3(0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-1.4152704f, 0.6658842f, 0.3791980f), new Vector3(-0.9769651f, 0.2127087f, -0.0171549f)),
                new TileSite(new Vector3(-1.4152704f, 0.3791980f, 0.6658842f), new Vector3(-0.9769651f, -0.0171549f, 0.2127087f)),
                new TileSite(new Vector3(-0.6658842f, -0.3791980f, 1.4152704f), new Vector3(-0.2127087f, 0.0171549f, 0.9769651f)),
                new TileSite(new Vector3(-0.3791980f, -0.6658842f, 1.4152704f), new Vector3(0.0171549f, -0.2127087f, 0.9769651f)),
                new TileSite(new Vector3(0.3791980f, -1.4152704f, 0.6658842f), new Vector3(-0.0171549f, -0.9769651f, 0.2127087f)),
                new TileSite(new Vector3(0.6658842f, -1.4152704f, 0.3791980f), new Vector3(0.2127087f, -0.9769651f, -0.0171549f)),
                new TileSite(new Vector3(1.4152704f, -0.6658842f, -0.3791980f), new Vector3(0.9769651f, -0.2127087f, 0.0171549f)),
                new TileSite(new Vector3(1.4152704f, -0.3791980f, -0.6658842f), new Vector3(0.9769651f, 0.0171549f, -0.2127087f)),
                new TileSite(new Vector3(0.6658842f, 0.3791980f, -1.4152704f), new Vector3(0.2127087f, -0.0171549f, -0.9769651f)),
                new TileSite(new Vector3(0.3791980f, 0.6658842f, -1.4152704f), new Vector3(-0.0171549f, 0.2127087f, -0.9769651f)),
                new TileSite(new Vector3(-0.3791980f, 1.4152704f, -0.6658842f), new Vector3(0.0171549f, 0.9769651f, -0.2127087f)),
                new TileSite(new Vector3(-0.6658842f, 1.4152704f, -0.3791980f), new Vector3(-0.2127087f, 0.9769651f, 0.0171549f)),
                new TileSite(new Vector3(-1.4108144f, 1.0038659f, 0.1441757f), new Vector3(-0.8679220f, 0.4815780f, -0.1216308f)),
                new TileSite(new Vector3(-1.4108144f, 0.1441757f, 1.0038659f), new Vector3(-0.8679220f, -0.1216308f, 0.4815780f)),
                new TileSite(new Vector3(-1.0038659f, -0.1441757f, 1.4108144f), new Vector3(-0.4815780f, 0.1216308f, 0.8679220f)),
                new TileSite(new Vector3(-0.1441757f, -1.0038659f, 1.4108144f), new Vector3(0.1216308f, -0.4815780f, 0.8679220f)),
                new TileSite(new Vector3(0.1441757f, -1.4108144f, 1.0038659f), new Vector3(-0.1216308f, -0.8679220f, 0.4815780f)),
                new TileSite(new Vector3(1.0038659f, -1.4108144f, 0.1441757f), new Vector3(0.4815780f, -0.8679220f, -0.1216308f)),
                new TileSite(new Vector3(1.4108144f, -1.0038659f, -0.1441757f), new Vector3(0.8679220f, -0.4815780f, 0.1216308f)),
                new TileSite(new Vector3(1.4108144f, -0.1441757f, -1.0038659f), new Vector3(0.8679220f, 0.1216308f, -0.4815780f)),
                new TileSite(new Vector3(1.0038659f, 0.1441757f, -1.4108144f), new Vector3(0.4815780f, -0.1216308f, -0.8679220f)),
                new TileSite(new Vector3(0.1441757f, 1.0038659f, -1.4108144f), new Vector3(-0.1216308f, 0.4815780f, -0.8679220f)),
                new TileSite(new Vector3(-0.1441757f, 1.4108144f, -1.0038659f), new Vector3(0.1216308f, 0.8679220f, -0.4815780f)),
                new TileSite(new Vector3(-1.0038659f, 1.4108144f, -0.1441757f), new Vector3(-0.4815780f, 0.8679220f, 0.1216308f)),
                new TileSite(new Vector3(-1.3807938f, 0.0000000f, 1.3807938f), new Vector3(-0.7071068f, -0.0000000f, 0.7071068f)),
                new TileSite(new Vector3(0.0000000f, -1.3807938f, 1.3807938f), new Vector3(-0.0000000f, -0.7071068f, 0.7071068f)),
                new TileSite(new Vector3(1.3807938f, -1.3807938f, 0.0000000f), new Vector3(0.7071068f, -0.7071068f, -0.0000000f)),
                new TileSite(new Vector3(1.3807938f, 0.0000000f, -1.3807938f), new Vector3(0.7071068f, -0.0000000f, -0.7071068f)),
                new TileSite(new Vector3(0.0000000f, 1.3807938f, -1.3807938f), new Vector3(-0.0000000f, 0.7071068f, -0.7071068f)),
                new TileSite(new Vector3(-1.3807938f, 1.3807938f, 0.0000000f), new Vector3(-0.7071068f, 0.7071068f, -0.0000000f)),
            }),
        };
        // <<< MEASURED TABLE END

        // Bonds are DERIVED from the measured positions rather than baked beside them, so
        // the growth graph cannot drift away from the geometry it is supposed to describe.
        // Built once per level, on first use.
        static readonly Dictionary<int, SchwarzPBond[][]> BondCache = new();

        public static int LevelCount => LevelTable.Length;

        public static int SiteCount(int level) => LevelTable[Clamp(level)].Sites.Length;

        /// <summary>Mean nearest-neighbour distance between sites, in parameter radians.</summary>
        public static float MeanParamSpacing(int level) => LevelTable[Clamp(level)].MeanParamSpacing;

        static int Clamp(int level) => Mathf.Clamp(level, 0, LevelTable.Length - 1);

        /// <summary>
        /// The subdivision whose measured site spacing lands closest to the flora's authored
        /// <c>separationDistance</c>. The tile itself is fixed by the surface; how finely it
        /// is filled with prisms is the one free parameter, and this is where it is chosen.
        /// </summary>
        public static int ResolveLevel(float separationDistance, float periodScale)
        {
            float worldScale = periodScale / ParamPeriod;
            if (worldScale <= 1e-5f || separationDistance <= 1e-5f) return 0;

            int best = 0;
            float bestError = float.MaxValue;
            for (int level = 0; level < LevelTable.Length; level++)
            {
                float error = Mathf.Abs(LevelTable[level].MeanParamSpacing * worldScale - separationDistance);
                if (error >= bestError) continue;
                bestError = error;
                best = level;
            }
            return best;
        }

        /// <summary>World-space distance between neighbouring prisms at this level.</summary>
        public static float WorldSpacing(int level, float periodScale) =>
            MeanParamSpacing(level) * (periodScale / ParamPeriod);

        /// <summary>The flat point at the centre of tile (i,j,k), in parameter space.</summary>
        public static Vector3 TileCenterParam(Vector3Int tile) => new(
            TileParamSize * (tile.x + 0.5f),
            TileParamSize * (tile.y + 0.5f),
            TileParamSize * (tile.z + 0.5f));

        /// <summary>
        /// The linear part of T_ijk: -1 on every odd axis, because a tile is the mirror
        /// image of each of its face neighbours. Also the direction of the tile's flat
        /// point normal.
        /// </summary>
        public static Vector3 AxisSigns(Vector3Int tile) => new(
            (tile.x & 1) == 0 ? 1f : -1f,
            (tile.y & 1) == 0 ? 1f : -1f,
            (tile.z & 1) == 0 ? 1f : -1f);

        /// <summary>
        /// The tile a bond step leads to. <b>Not <c>tile + delta</c>.</b>
        ///
        /// <para>Bond deltas are measured in the CANONICAL tile, and carrying one into tile
        /// (i,j,k) means composing tile transforms - which do not add. Per axis,
        /// <c>T_a(T_b(x)) = T_(a + b)</c> when a is even but <c>T_(a - b)</c> when a is odd,
        /// because an odd tile is a MIRROR image and a mirror reverses the step through it.
        /// So a bond delta is negated on exactly the axes <see cref="AxisSigns"/> negates,
        /// and the neighbour's SITE INDEX is unchanged.</para>
        ///
        /// <para>Getting this wrong is silent and survives every static check: the offsets
        /// are still exact, every prism still lands on the surface, occupancy still keys
        /// cleanly - odd-indexed tiles simply bond to the tile on the wrong side. It shows
        /// up only as geometry, as prisms with no neighbour within seven times the spacing,
        /// and it was caught by simulating a plant's growth to its authored budget rather
        /// than by reading the code.</para>
        /// </summary>
        public static Vector3Int NeighbourTile(Vector3Int tile, Vector3Int delta) => new(
            tile.x + ((tile.x & 1) == 0 ? delta.x : -delta.x),
            tile.y + ((tile.y & 1) == 0 ? delta.y : -delta.y),
            tile.z + ((tile.z & 1) == 0 ? delta.z : -delta.z));

        public static SchwarzPTileSite GetSite(int level, int site)
        {
            var sites = LevelTable[Clamp(level)].Sites;
            var s = sites[Mathf.Clamp(site, 0, sites.Length - 1)];
            return new SchwarzPTileSite(s.Offset, s.Tangent);
        }

        /// <summary>Parameter-space position of a site of a given tile. Pure arithmetic.</summary>
        public static Vector3 SiteParam(Vector3Int tile, int level, int site)
        {
            Vector3 signs = AxisSigns(tile);
            Vector3 offset = GetSite(level, site).ParamOffset;
            return TileCenterParam(tile) + new Vector3(
                signs.x * offset.x, signs.y * offset.y, signs.z * offset.z);
        }

        /// <summary>Parameter-space tangent of a site of a given tile.</summary>
        public static Vector3 SiteTangentParam(Vector3Int tile, int level, int site)
        {
            Vector3 signs = AxisSigns(tile);
            Vector3 tangent = GetSite(level, site).ParamTangent;
            return new Vector3(signs.x * tangent.x, signs.y * tangent.y, signs.z * tangent.z);
        }

        /// <summary>
        /// Unit surface normal from the closed-form gradient of
        /// <c>f = cos x + cos y + cos z</c>. Derived at the transformed point, so it is
        /// correct under the reflections half the tile transforms carry.
        /// </summary>
        public static Vector3 SurfaceNormalParam(Vector3 param)
        {
            Vector3 gradient = new(-Mathf.Sin(param.x), -Mathf.Sin(param.y), -Mathf.Sin(param.z));
            return gradient.sqrMagnitude > 1e-8f ? gradient.normalized : Vector3.up;
        }

        /// <summary>The growth steps available from a site: its touching neighbours, nearest
        /// first, each tagged with the tile it belongs to (zero for a sibling in the same
        /// tile, a unit axis step for one across a seam).</summary>
        public static SchwarzPBond[] GetBonds(int level, int site)
        {
            var bonds = BuildBonds(Clamp(level));
            return bonds[Mathf.Clamp(site, 0, bonds.Length - 1)];
        }

        static SchwarzPBond[][] BuildBonds(int level)
        {
            if (BondCache.TryGetValue(level, out var cached)) return cached;

            var sites = LevelTable[level].Sites;
            int count = sites.Length;

            // Every site of the tile and of its 26 neighbours, in parameter space. The tile
            // is only pi across, so the whole block is a few thousand points at worst.
            var deltas = new List<Vector3Int>(27);
            for (int x = -1; x <= 1; x++)
                for (int y = -1; y <= 1; y++)
                    for (int z = -1; z <= 1; z++)
                        deltas.Add(new Vector3Int(x, y, z));

            var origin = Vector3Int.zero;
            var positions = new Vector3[deltas.Count][];
            for (int d = 0; d < deltas.Count; d++)
            {
                positions[d] = new Vector3[count];
                for (int s = 0; s < count; s++)
                    positions[d][s] = SiteParam(deltas[d], level, s);
            }

            var result = new SchwarzPBond[count][];
            var scratch = new List<(float distance, int site, int delta)>(count * deltas.Count);
            for (int s = 0; s < count; s++)
            {
                Vector3 self = SiteParam(origin, level, s);
                scratch.Clear();
                float nearest = float.MaxValue;
                for (int d = 0; d < deltas.Count; d++)
                {
                    for (int other = 0; other < count; other++)
                    {
                        if (d == 13 && other == s) continue;    // deltas[13] is (0,0,0)
                        float distance = Vector3.Distance(self, positions[d][other]);
                        if (distance < 1e-5f) continue;
                        scratch.Add((distance, other, d));
                        if (distance < nearest) nearest = distance;
                    }
                }

                float limit = nearest * BondRadiusFactor;
                scratch.Sort((a, b) => a.distance.CompareTo(b.distance));

                var picked = new List<SchwarzPBond>(8);
                foreach (var (distance, other, delta) in scratch)
                {
                    if (distance > limit) break;
                    picked.Add(new SchwarzPBond(other, deltas[delta]));
                }
                result[s] = picked.ToArray();
            }

            BondCache[level] = result;
            return result;
        }
    }
}
