using System.Collections.Generic;
using CosmicShore.Data;
using CosmicShore.ScriptableObjects;
using CosmicShore.Utility;
using Unity.Netcode;
using UnityEngine;

namespace CosmicShore.Gameplay
{
    /// <summary>
    /// Skein - the Urchin-only cable race. A trefoil-knot cable of open, aimed rails hangs in the
    /// cell; every pilot threads the SAME ordered ring course, and the first domain whose LEAD
    /// RUNNER threads the last ring wins.
    ///
    /// <para><b>Ordered rings are what make it cheap.</b> A pilot may only thread their next ring,
    /// so <see cref="IRoundStats.SwitchesThreaded"/> is simultaneously the score, the progress bar,
    /// the index of the ring to test this frame, and the token the server validates a report
    /// against. One replicated int carries the race; there is no per-ring state, no bitmask, and
    /// detection is one segment test per pilot per frame rather than pilots x rings.</para>
    ///
    /// <para><b>It reuses Switchback's whole scoring spine.</b> Same metric (9), same
    /// <c>BestByDomain</c> fold, same <c>Player.ReportSwitchThreaded_ServerRpc</c> round trip, same
    /// <see cref="SwitchThreadScoring.Credit"/> validation, same objective-arrow shape. The mode
    /// claims ONE new enum member in the whole project.</para>
    ///
    /// <para><b>The course comes from the ARENA, not from a second derivation.</b> The rings are
    /// generated by <see cref="SkeinCourse"/> as a by-product of laying the cable, so this
    /// controller reads <see cref="SpawnableSkein.Gates"/> rather than regenerating them from its
    /// own copy of the numbers - two derivations of one course is precisely how a ring ends up
    /// somewhere no rail goes.</para>
    ///
    /// <para><b>The geometry travels, never the seed.</b> The server broadcasts ring positions and
    /// axes. Generating locally from a shared seed would have worked - the generator is
    /// deterministic on purpose - but it would rest on <c>Mathf.Sin</c>/<c>Acos</c> agreeing to the
    /// last bit across Mono and IL2CPP, and the trim's accept/reject decisions are BRANCHES, so one
    /// flipped bit yields a completely different course rather than a slightly different one.</para>
    /// </summary>
    public class SkeinController : MultiplayerDomainGamesController
    {
        [Header("Scoring")]
        [Tooltip("Drag SkeinScoringRule.asset - the per-mode scoring strategy.")]
        [SerializeField] ScoringRuleSO rule;

        [Header("Rings")]
        [Tooltip("Seconds a ring takes to bloom in. Detection is live at the full mouth from frame " +
                 "one; only the drawing grows into it.")]
        [SerializeField, Min(0f)] float ringBloomSeconds = 0.9f;

        [Tooltip("Seconds to keep looking for the cable before giving up. The Cell builds its " +
                 "environment behind InitDelayMs and then lays thousands of prisms, so the arena " +
                 "does not exist when this controller network-spawns.")]
        [SerializeField, Min(1f)] float arenaWaitSeconds = 30f;

        [Header("AI")]
        [Tooltip("How far down its own rail an attached AI aims. Far enough that the range falls " +
                 "every frame (which resets OrbitDetector before it can sweep) and the bearing " +
                 "stays near the tangent (which holds LookingAtCrystal, so ram keeps the grind at " +
                 "150 rather than collapsing to 30 u/s).")]
        [SerializeField, Min(1f)] float aiRailLeadDistance = 260f;

        [Tooltip("How far PAST a ring the fly-through point sits. AIPilot has no arrive-and-stop " +
                 "behaviour, so a target it has arrived at becomes one it orbits.")]
        [SerializeField, Min(1f)] float aiThroughDistance = 220f;

        [Header("Arena")]
        [Tooltip("The scene Cell that BUILDS the cable. Left empty this falls back to a scene " +
                 "search; the reference is preferred because a satellite Cell (the arcade card's " +
                 "preview) is also a Cell and a search could find the wrong one.")]
        [SerializeField] Cell arenaCell;

        [Header("Detection")]
        [Tooltip("Ignore a single frame's motion longer than the fastest Urchin could travel plus " +
                 "a margin - a respawn or an eject must never read as having threaded a ring. A " +
                 "launch carries the 150 u/s grind speed, so this sits well above it.")]
        [SerializeField, Min(1f)] float maxPlausibleSpeed = 400f;

        [Tooltip("Seconds before an unacknowledged report is assumed lost and local optimistic " +
                 "progress resyncs to the replicated value.")]
        [SerializeField, Min(0.5f)] float reportResyncSeconds = 3f;

        sealed class PilotRun
        {
            public int Optimistic;
            public Vector3 LastPosition;
            public bool HasLastPosition;
            public float LastReportTime;
        }

        readonly List<SkeinGate> _course = new();
        readonly List<SwitchbackGateRing> _rings = new();
        readonly Dictionary<IPlayer, PilotRun> _runs = new();
        readonly List<IPlayer> _stalePilots = new();

        bool _courseBuilt, _arenaBuildAnnounced, _warnedCourseMissing;
        int _litGate = -1;
        float _waitDeadline;

        protected override bool UseGolfRules => true;
        protected override bool UseSceneReloadForReplay => true;

        public override void OnNetworkSpawn()
        {
            base.OnNetworkSpawn();

            gameData.ScoringRule = rule;
            numberOfRounds = 1;
            numberOfTurnsPerRound = 1;
            _warnedCourseMissing = false;

            // The connecting panel's arena gate is held while the CABLE lays, which this mode does
            // not own - but the RINGS are laid after it, so hold the bracket until they exist too.
            // A pilot released before the rings arrive flies ring 1, is credited nothing,
            // permanently, with nothing on screen to say why.
            _arenaBuildAnnounced = true;
            PrismTrailBuilder.BeginArenaBuild();
            _waitDeadline = Time.time + arenaWaitSeconds;

            if (!IsServer) RequestCourse_ServerRpc();
        }

        public override void OnNetworkDespawn()
        {
            DisarmRacers();
            ReleaseArenaBuildAnnouncement();
            ClearCourse();
            base.OnNetworkDespawn();
        }

        void ReleaseArenaBuildAnnouncement()
        {
            if (!_arenaBuildAnnounced) return;
            _arenaBuildAnnounced = false;
            PrismTrailBuilder.EndArenaBuild();
        }

        // ── Course ────────────────────────────────────────────────────────

        /// <summary>
        /// Poll for the cable until it exists, then lay its rings. The arena is a Cell environment
        /// prefab built behind <c>InitDelayMs</c> and thousands of budgeted prism lays, so it is
        /// simply not there when this controller spawns - and there is no event to subscribe to
        /// that fires on every peer.
        /// </summary>
        bool TryAdoptArenaCourse()
        {
            // Through the CELL'S CONFIG, never a scene search for the spawnable.
            //
            // SpawnableBase.Spawn() does NOT instantiate itself: it news up a plain container
            // GameObject and lays prisms into it, so the SpawnableSkein that ran the generation
            // is the PREFAB ASSET and no such component ever exists in the scene.
            // FindAnyObjectByType therefore returned null on every frame of every match - the
            // cable built, and the rings and the objective arrow never arrived. Cell's own
            // AdoptPlantingSites reads its garden the same way, off cellConfigData.
            var cell = arenaCell != null ? arenaCell : FindAnyObjectByType<Cell>();
            if (cell == null || cell.Config == null) return false;
            if (cell.Config.EnvironmentPrefab is not SpawnableSkein arena) return false;
            if (arena.Gates.Count == 0) return false;

            var course = new List<SkeinGate>(arena.Gates.Count);
            // The generator works about the ORIGIN and Cell parents the environment container at
            // localPosition zero, so the cable's world origin is the CELL's transform - not the
            // prefab's, which is an asset and never moves.
            Vector3 centre = cell.transform.position;
            for (int i = 0; i < arena.Gates.Count; i++)
            {
                var g = arena.Gates[i];
                course.Add(new SkeinGate(g.Position + centre, g.Axis, g.Radius, g.Strand));
            }

            ApplyCourse(course);
            if (IsServer) BroadcastCourse(course, default);
            return true;
        }

        [ServerRpc(RequireOwnership = false)]
        void RequestCourse_ServerRpc(ServerRpcParams rpcParams = default)
        {
            if (!IsServer || _course.Count == 0) return;

            // Targeted reply: a client that spawned after the broadcast has no other way to learn
            // the course, and NGO only holds a message for an unspawned object for a few seconds.
            BroadcastCourse(_course, new ClientRpcParams
            {
                Send = new ClientRpcSendParams { TargetClientIds = new[] { rpcParams.Receive.SenderClientId } }
            });
        }

        void BroadcastCourse(IReadOnlyList<SkeinGate> course, ClientRpcParams target)
        {
            // Seven floats per ring interleaved into one array - the primitive-array shape this
            // project's final-score snapshots already prove.
            var packed = new float[course.Count * 7];
            for (int i = 0; i < course.Count; i++)
            {
                int o = i * 7;
                packed[o + 0] = course[i].Position.x;
                packed[o + 1] = course[i].Position.y;
                packed[o + 2] = course[i].Position.z;
                packed[o + 3] = course[i].Axis.x;
                packed[o + 4] = course[i].Axis.y;
                packed[o + 5] = course[i].Axis.z;
                packed[o + 6] = course[i].Radius;
            }
            SyncCourse_ClientRpc(packed, target);
        }

        [ClientRpc]
        void SyncCourse_ClientRpc(float[] packed, ClientRpcParams rpcParams = default)
        {
            if (IsServer) return;   // the server laid its own copy before broadcasting

            var course = new List<SkeinGate>(packed.Length / 7);
            for (int o = 0; o + 6 < packed.Length; o += 7)
                course.Add(new SkeinGate(
                    new Vector3(packed[o], packed[o + 1], packed[o + 2]),
                    new Vector3(packed[o + 3], packed[o + 4], packed[o + 5]),
                    packed[o + 6], 0));

            ApplyCourse(course);
        }

        void ApplyCourse(IReadOnlyList<SkeinGate> course)
        {
            if (_courseBuilt) return;
            _courseBuilt = true;

            var theme = gameData ? gameData.ThemeManagerData : null;
            var root = new GameObject("SkeinCourse").transform;
            root.SetParent(transform, false);

            for (int i = 0; i < course.Count; i++)
            {
                _course.Add(course[i]);

                var go = new GameObject($"Ring_{i + 1:00}");
                go.transform.SetParent(root, false);

                // SwitchbackGateRing verbatim: one renderer, ZERO colliders, drawn through
                // ToyFactory.AddSwitchRing at its own crossing radius (the switch law - a ring IS
                // its trigger volume), neutral Blue because threading one hands nobody a domain,
                // and the local pilot's next one lit lime. Prism mass in the racing line would be
                // ATTACHABLE, and a pilot latching onto a ring instead of threading it is the
                // worst failure this mode can have.
                var ring = go.AddComponent<SwitchbackGateRing>();
                ring.Build(i, new SwitchbackGate(course[i].Position, course[i].Axis, course[i].Radius),
                           theme, ringBloomSeconds);
                _rings.Add(ring);
            }

            ReleaseArenaBuildAnnouncement();
            CSDebug.Log($"[Skein] Course laid: {_rings.Count} rings.");
        }

        void ClearCourse()
        {
            // Withering rather than destroying: continuity of existence applies to a marker as
            // much as to a prism.
            for (int i = 0; i < _rings.Count; i++)
                if (_rings[i]) _rings[i].Retire(0.4f);

            _rings.Clear();
            _course.Clear();
            _runs.Clear();
            _courseBuilt = false;
            _litGate = -1;
        }

        /// <summary>The ring target this match is run against - the course's OWN length once it
        /// exists. The turn monitor reads this rather than the override directly, because a target
        /// naming a ring the course does not contain is a match that cannot end.</summary>
        public int AuthoritativeGateCount => _courseBuilt && _course.Count > 0 ? _course.Count : 0;

        /// <summary>The ring <paramref name="player"/> must thread next, or null when they have
        /// finished (or the course has not arrived).</summary>
        public bool TryGetNextGate(IPlayer player, out Transform gate)
        {
            gate = null;
            if (player?.RoundStats == null) return false;

            int index = player.RoundStats.SwitchesThreaded;
            if (index < 0 || index >= _rings.Count) return false;

            var ring = _rings[index];
            if (!ring) return false;

            gate = ring.transform;
            return true;
        }

        /// <summary>Light the LOCAL pilot's next ring lime and put the previous one back to
        /// neutral. Twenty-four identical rings on a braided cable is a course you have to be told
        /// the ORDER of. Local only - every peer builds its own rings, so this changes nothing on
        /// anyone else's screen - and driven from the pilot's live progress rather than from the
        /// crossing event, so it is correct after a rollback and for a report still in flight.</summary>
        void LightLocalNextRing()
        {
            int next = gameData.LocalPlayer?.RoundStats != null
                ? gameData.LocalPlayer.RoundStats.SwitchesThreaded
                : -1;
            if (next >= _rings.Count) next = -1;
            if (next == _litGate) return;

            if (_litGate >= 0 && _litGate < _rings.Count && _rings[_litGate])
                _rings[_litGate].SetIsNextForLocalPilot(false);
            if (next >= 0 && _rings[next])
                _rings[next].SetIsNextForLocalPilot(true);

            _litGate = next;
        }

        // ── Detection ─────────────────────────────────────────────────────

        void Update()
        {
            if (!_courseBuilt)
            {
                if (TryAdoptArenaCourse()) return;
                if (_arenaBuildAnnounced && Time.time > _waitDeadline)
                {
                    // Never hold the connecting panel forever: a bracket left open wedges it on a
                    // build that is not going to happen.
                    CSDebug.LogError("[Skein] No Skein cable appeared within " +
                                     $"{arenaWaitSeconds:F0}s - releasing the load gate. Rings " +
                                     "flown now cannot be credited. Check that the scene Cell's " +
                                     "active CellConfigDataSO carries a SpawnableSkein as its " +
                                     "EnvironmentPrefab.");
                    ReleaseArenaBuildAnnouncement();
                }
                return;
            }

            if (gameData == null || !gameData.IsTurnRunning) return;

            if (_rings.Count == 0)
            {
                if (!_warnedCourseMissing)
                {
                    _warnedCourseMissing = true;
                    CSDebug.LogError("[Skein] Turn started with no rings on this peer - rings flown " +
                                     "now cannot be credited.");
                }
                return;
            }

            LightLocalNextRing();

            float maxStep = maxPlausibleSpeed * Time.deltaTime * 2f + 5f;
            float maxStepSqr = maxStep * maxStep;

            var players = gameData.Players;
            for (int i = 0; i < players.Count; i++)
            {
                var p = players[i];

                // Only ever test a vessel THIS machine simulates. IsNetworkOwner, not IsLocalUser:
                // the host owns every AI, and the narrower test would silently never advance one.
                if (p == null || !p.IsNetworkOwner) continue;

                var vessel = p.Vessel;
                if (vessel == null) { Forget(p); continue; }
                var t = vessel.Transform;
                if (!t) { Forget(p); continue; }
                var stats = p.RoundStats;
                if (stats == null) { Forget(p); continue; }

                if (!_runs.TryGetValue(p, out var run))
                {
                    run = new PilotRun { Optimistic = stats.SwitchesThreaded };
                    _runs[p] = run;
                }
                Reconcile(run, stats.SwitchesThreaded);

                Vector3 cur = t.position;
                if (!run.HasLastPosition) { run.LastPosition = cur; run.HasLastPosition = true; continue; }

                Vector3 prev = run.LastPosition;
                run.LastPosition = cur;

                // A respawn, an eject or a frame-rate hitch is not a ring.
                if ((cur - prev).sqrMagnitude > maxStepSqr) continue;

                int index = run.Optimistic;
                if (index < 0 || index >= _rings.Count) continue;

                var ring = _rings[index];
                if (!ring || !ring.CrossedMouth(prev, cur)) continue;

                run.Optimistic = index + 1;
                run.LastReportTime = Time.time;

                if (IsServer) SwitchThreadScoring.Credit(stats, index);
                else if (p is Player netPlayer) netPlayer.ReportSwitchThreaded_ServerRpc(index);
            }

            PruneDepartedPilots(players);
        }

        /// <summary>Adopt the server's count when it catches up, and fall BACK to it when a report
        /// has gone unacknowledged for too long - without the second half a rejected or dropped
        /// report strands this pilot testing a ring the server will never credit.</summary>
        void Reconcile(PilotRun run, int confirmed)
        {
            if (confirmed >= run.Optimistic) { run.Optimistic = confirmed; return; }
            if (Time.time - run.LastReportTime > reportResyncSeconds) run.Optimistic = confirmed;
        }

        void Forget(IPlayer p)
        {
            if (_runs.TryGetValue(p, out var run)) run.HasLastPosition = false;
        }

        // ── AI ────────────────────────────────────────────────────────────

        protected override void OnCountdownTimerEnded()
        {
            if (!IsServer) return;
            base.OnCountdownTimerEnded();
            ArmRacers();
        }

        /// <summary>
        /// One steering closure per AI, through <c>AIPilot.SetExternalTargetProvider</c>.
        ///
        /// <para><b>Why this hook and not the others.</b> <c>SetDriftLookTargetProvider</c>
        /// overrides only the nose during a DRIFT, which the Urchin does not author. And
        /// installing NO hook is right only when the objective IS a crystal (Rampage's rule) -
        /// here the objective is a ring on a specific rail, so a default pilot flies at whatever
        /// crystal it can see and never races.</para>
        ///
        /// <para><b>While ATTACHED the target is a lead point down the pilot's OWN rail, and that
        /// one choice is load-bearing for two separate reasons.</b> It was the verified answer to
        /// the orbit-break question: aiming at the RING while riding leaves the range roughly
        /// constant as the cable corkscrews, and <c>OrbitDetector</c> trips on swept angle without
        /// progress - an outer strand sweeps thousands of degrees per lap, far past the detector's
        /// threshold, where Hijack's 20-degree arcs never could. When it trips, <c>_extending</c>
        /// goes true, <c>LookingAtCrystal</c> goes false, <c>ram</c> disengages and the pilot drops
        /// from 150 to 30 u/s mid-grind. A lead point down the rail makes the range fall every
        /// frame (which resets the detector before it can sweep) AND keeps the bearing near the
        /// tangent (which holds <c>LookingAtCrystal</c>, so <c>ram: 1</c> keeps XDiff at 1). One
        /// mode-side closure buys both, with no platform change - which is why the proposed
        /// <c>AIPilot.IsAttached</c> exemption was NOT taken.</para>
        ///
        /// <para>Off-rail the target is the ring itself, aimed THROUGH: AIPilot has no
        /// arrive-and-stop behaviour, so a target inside its own turning circle becomes something
        /// it orbits.</para>
        /// </summary>
        void ArmRacers()
        {
            foreach (var p in gameData.Players)
            {
                if (p == null || !p.IsInitializedAsAI) continue;
                var status = p.Vessel?.VesselStatus;
                var pilot = status?.AIPilot;
                if (pilot == null) continue;

                var captured = p;
                pilot.SetExternalTargetProvider(() =>
                {
                    var self = captured.Vessel?.VesselStatus;
                    var tf = captured.Vessel?.Transform;
                    if (self == null || tf == null) return Vector3.zero;

                    // RIDING: hold the nose down-rail. The ride constrains position, never
                    // attitude, so where the AI looks is also where it LAUNCHES when the ribbon
                    // runs out - and every break in this arena is aimed by construction, so a
                    // competent AI is one that holds the throttle.
                    if (self.IsAttached && self.AttachedPrism != null)
                    {
                        Vector3 along = self.Course.sqrMagnitude > 1e-4f
                            ? self.Course.normalized : tf.forward;
                        return tf.position + along * aiRailLeadDistance;
                    }

                    // OFF-RAIL: fly at this pilot's own next ring, and THROUGH it.
                    if (!TryGetNextGate(captured, out var ring) || ring == null)
                        return tf.position + tf.forward * aiRailLeadDistance;

                    int idx = captured.RoundStats != null ? captured.RoundStats.SwitchesThreaded : 0;
                    Vector3 axis = idx >= 0 && idx < _course.Count ? _course[idx].Axis : ring.forward;
                    return ring.position + axis * aiThroughDistance;
                });
            }
        }

        void DisarmRacers()
        {
            if (gameData?.Players == null) return;
            foreach (var p in gameData.Players)
            {
                var pilot = p?.Vessel?.VesselStatus?.AIPilot;
                // Cleared at teardown on purpose: Switchback ships without this and leaks its
                // closure across a scene-reload replay, where the captured player is destroyed.
                // The dedicated clear rather than a null provider - it is what restores AIPilot's
                // own crystal/player seeking, which is the state a pilot should return to.
                if (pilot != null) pilot.ClearExternalTargetProvider();
            }
        }

        void PruneDepartedPilots(List<IPlayer> players)
        {
            if (_runs.Count <= players.Count) return;

            _stalePilots.Clear();
            foreach (var key in _runs.Keys)
                if (!players.Contains(key)) _stalePilots.Add(key);
            for (int i = 0; i < _stalePilots.Count; i++) _runs.Remove(_stalePilots[i]);
        }
    }
}
