#if UNITY_EDITOR
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using CosmicShore.ScriptableObjects;
using NUnit.Framework;

namespace CosmicShore.Tests
{
    /// <summary>
    /// The asset-side gate for Docs/ECOSYSTEM.md §40 — lifeform LEVELS are retired, and a
    /// lifeform's HEART (the elemental crystal it drops) is sized by its species × element,
    /// authored once in that element's own variant tuning block.
    ///
    /// <para>Three things can break that silently, and each has a test here.</para>
    ///
    /// <list type="number">
    ///   <item><b>A heart authored into a DISABLED variant block.</b> This is the one that
    ///   matters most, because it is invisible from every direction: the asset shows a
    ///   perfectly good <c>HeartWorldScale</c>, the value is never wrong, and it is never
    ///   READ — <c>CellLifeSpawnerBase</c> (and <c>Fauna.AssignLineage</c>) apply a variant
    ///   tuning block only when <c>Enabled</c> is true, so the lifeform silently falls back
    ///   to <c>ElementalCrystalSetSO.DefaultHeartWorldScale</c> and every species with the
    ///   defect renders the same heart. <b>35 of these 88 assets shipped with
    ///   <c>Enabled: 0</c></b> before the authoring pass flipped them — five flora species
    ///   (three of their four elements each) and five of the six fauna species (all
    ///   four).</item>
    ///
    ///   <item><b>A heart that clips the collect reward.</b> Heart world scale is read AS
    ///   GAMEPLAY: the collect reward is <c>min(worldScale × levelPerUnitScale,
    ///   maxLevelGainPerCrystal)</c> and the live domain fauna buff is the same function
    ///   summed over a domain's living hearts. Past the saturation scale two visibly
    ///   different hearts pay the same — a size the player can see and a reward they cannot
    ///   — which is exactly the property that makes "bigger lifeform, bigger heart, bigger
    ///   kill" true. <c>ElementalCrystalSetSO.MaxSafeHeartWorldScale</c> is the margin under
    ///   it; this pins the C# constant, the authored band, AND the reward asset the constant
    ///   was derived from, so a retune of any one of the three cannot pass alone.</item>
    ///
    ///   <item><b>A retired level field coming back as data.</b> The level surface is gone
    ///   from C#, but Unity never prunes an unresolvable serialized field: an
    ///   <c>InitialLevel</c> left in an asset is dead weight that reads as live authoring
    ///   the next time somebody opens the file.</item>
    /// </list>
    ///
    /// <para>The band itself is generated by <c>Tools/Build/author_lifeform_heart_sizes.py</c>
    /// (run it with <c>--check</c>); this suite is the half of that gate which runs without
    /// Python, from assets alone — no play mode.</para>
    /// </summary>
    public class LifeformHeartSizeTests
    {
        const string LifeformDir = "Assets/_SO_Assets/Lifeforms";
        const string AssetsRoot = "Assets";

        const string RewardEffectPath =
            "Assets/_SO_Assets/Effects/Skimmer Crystal Effects/SkimmerAdjustElementLevelByCrystalEffect.asset";

        /// 22 species × 4 elements. Pinned so a rename, a move, or a parse regression cannot
        /// turn this whole suite into a green no-op over an empty set.
        const int CanonicalVariantCount = 88;

        /// The four droppable elements, as serialized (Element.None is 0, Omni 5).
        static readonly int[] DroppableElements = { 1, 2, 3, 4 };

        /// Serialized keys that the level retirement removed. A YAML key at any indentation.
        static readonly string[] RetiredLevelFields =
        {
            "InitialLevel",
            "LeafScalePerLevel",
            "BodyScalePerLevel",
            "LevelGrowSeconds",
            "FeedsPerLevel",
        };

        // ── asset reading ────────────────────────────────────────────────────

        static string Read(string path)
        {
            Assert.IsTrue(File.Exists(path), $"{path} is missing.");
            return File.ReadAllText(path).Replace("\r\n", "\n");
        }

        static bool TryInt(string body, string key, out int value)
        {
            var m = Regex.Match(body, $@"^\s+{Regex.Escape(key)}: (?<v>-?\d+)\s*$", RegexOptions.Multiline);
            value = 0;
            return m.Success && int.TryParse(m.Groups["v"].Value, out value);
        }

        static bool TryFloat(string body, string key, out float value)
        {
            var m = Regex.Match(body,
                $@"^\s+{Regex.Escape(key)}: (?<v>-?[\d.]+(?:[eE][-+]?\d+)?)\s*$", RegexOptions.Multiline);
            value = 0f;
            return m.Success && float.TryParse(
                m.Groups["v"].Value, NumberStyles.Float, CultureInfo.InvariantCulture, out value);
        }

        /// <summary>
        /// The body of the config's <c>Variant:</c> block — every line indented deeper than
        /// the block header. Scoping matters: a fauna variant nests an FMOD event several
        /// levels down, and the config carries sibling keys (SpreadElements, ElementPalette)
        /// at the block's own indentation that must NOT be swept in.
        /// </summary>
        static bool TryVariantBlock(string text, out string block)
        {
            // `\r?` / `[^\r\n]` are platform-critical, not tidiness. .gitattributes sets
            // `* text=auto`, so an .asset is LF in the repository and CRLF in a WINDOWS working
            // tree - and a literal `\n` in the pattern cannot match the `\r\n` there. Without
            // this the block was never found on Windows and every Variant assertion below passed
            // VACUOUSLY. Measured on .NET: 1 match on LF, 0 on CRLF; 1/1 once anchored this way.
            var m = Regex.Match(text, @"^  Variant:\r?\n(?<body>(?:^    [^\r\n]*\r?\n?)+)",
                                RegexOptions.Multiline);
            block = m.Success ? m.Groups["body"].Value : null;
            return m.Success;
        }

        sealed class Canonical
        {
            public string Name;
            public string Path;
            public int Element;
            public bool HasVariantBlock;
            public int Enabled;
            public bool HasHeart;
            public float Heart;
        }

        /// <summary>
        /// The canonical (species × element) assets: everything in _SO_Assets/Lifeforms that
        /// names one of the four droppable elements. Deliberately excludes the two
        /// element-less worm-colony configs: WormColonyConfig (the colony tuning SO, not a
        /// spawn config at all) and WormColonyFaunaConfig ("Worm Colony Kaiju" — Element.None,
        /// SpreadElements OFF, EMPTY palette, Variant disabled, so it rolls nothing and
        /// authors nothing). The second is a DORMANT authoring gap, and worth naming so the
        /// exclusion is not mistaken for a clean bill: nothing in Assets/ references its guid
        /// — the Lifeform Matrix toy's "Worm Colony" entry lists the four canonical
        /// "Worm Colony &lt;Element&gt;" siblings, which all author 2.277 — so nothing spawns
        /// it today, but anything that did would render the platform default heart.
        /// LifeFormCrystalValidator reports it; it is an ecology call (give it an element, or
        /// a heart, or retire it), not a test fix.
        /// </summary>
        static List<Canonical> ReadCanonical()
        {
            Assert.IsTrue(Directory.Exists(LifeformDir), $"{LifeformDir} is missing.");

            var found = new List<Canonical>();
            foreach (string path in Directory.GetFiles(LifeformDir, "*.asset").OrderBy(p => p))
            {
                string text = File.ReadAllText(path).Replace("\r\n", "\n");
                if (!TryInt(text, "Element", out int element)) continue;
                if (!DroppableElements.Contains(element)) continue;

                var entry = new Canonical
                {
                    Name = System.IO.Path.GetFileNameWithoutExtension(path),
                    Path = path.Replace('\\', '/'),
                    Element = element,
                    HasVariantBlock = TryVariantBlock(text, out string block),
                };
                if (entry.HasVariantBlock)
                {
                    entry.Enabled = TryInt(block, "Enabled", out int enabled) ? enabled : -1;
                    entry.HasHeart = TryFloat(block, "HeartWorldScale", out float heart);
                    entry.Heart = heart;
                }
                found.Add(entry);
            }
            return found;
        }

        /// <summary>The heart world scale at which the collect reward saturates, read from
        /// the shipped effect asset rather than from the SO's field initializers.</summary>
        static float RewardSaturationWorldScale()
        {
            string text = Read(RewardEffectPath);
            Assert.IsTrue(TryFloat(text, "levelPerUnitScale", out float perUnit),
                $"{RewardEffectPath} no longer authors levelPerUnitScale.");
            Assert.IsTrue(TryFloat(text, "maxLevelGainPerCrystal", out float maxGain),
                $"{RewardEffectPath} no longer authors maxLevelGainPerCrystal.");
            Assert.Greater(perUnit, 0f, "levelPerUnitScale must be positive or no crystal pays anything.");
            Assert.Greater(maxGain, 0f, "maxLevelGainPerCrystal must be positive or no crystal pays anything.");
            return maxGain / perUnit;
        }

        // ── (a) every canonical lifeform authors a heart, in a block that is READ ─────

        [Test]
        public void CanonicalLifeformSet_IsTheWholeSpeciesTimesElementMatrix()
        {
            var canonical = ReadCanonical();

            Assert.AreEqual(CanonicalVariantCount, canonical.Count,
                "The canonical (species × element) set changed size. If a species was added or " +
                "removed, update CanonicalVariantCount AND Tools/Build/author_lifeform_heart_sizes.py " +
                "together — a shrinking set silently turns every assertion below into a no-op.\n" +
                string.Join("\n", canonical.Select(c => "  " + c.Name)));

            foreach (var species in canonical.GroupBy(c => Regex.Replace(c.Name, @" (Charge|Mass|Space|Time)$", "")))
            {
                CollectionAssert.AreEquivalent(DroppableElements, species.Select(c => c.Element).ToArray(),
                    $"'{species.Key}' does not carry exactly one asset per droppable element. " +
                    "A lifeform is its species and its element — all four, or the roster has a hole.");
            }
        }

        [Test]
        public void EveryCanonicalLifeformAuthorsAHeartSize()
        {
            var offenders = ReadCanonical()
                .Where(c => !c.HasVariantBlock || !c.HasHeart || c.Heart <= 0f)
                .Select(c => $"  {c.Name}: " +
                             (!c.HasVariantBlock ? "no Variant block at all"
                              : !c.HasHeart ? "Variant block authors no HeartWorldScale"
                              : $"HeartWorldScale is {c.Heart} (0 is the 'not authored' sentinel)"))
                .ToList();

            Assert.IsEmpty(offenders,
                "Every lifeform states its own heart size — a heart is a property of the LIFEFORM, " +
                "not of a level curve. A missing one silently falls back to " +
                "ElementalCrystalSetSO.DefaultHeartWorldScale, so the species renders (and pays) " +
                "the same as every other unsized one. Re-run " +
                "Tools/Build/author_lifeform_heart_sizes.py --write.\n" + string.Join("\n", offenders));
        }

        [Test]
        public void EveryAuthoredHeartLivesInAnEnabledVariantBlock()
        {
            var offenders = ReadCanonical()
                .Where(c => c.HasHeart && c.Enabled != 1)
                .Select(c => $"  {c.Name}: Variant.Enabled is {(c.Enabled < 0 ? "absent" : c.Enabled.ToString())} " +
                             $"but it authors HeartWorldScale {c.Heart}")
                .ToList();

            Assert.IsEmpty(offenders,
                "A heart authored into a DISABLED variant block is never read. CellLifeSpawnerBase " +
                "and Fauna.AssignLineage both gate on `pick.Tuning is { Enabled: true }`, so the " +
                "whole block — heart, body scale, prism shape, survival numbers — is skipped and the " +
                "lifeform takes the platform default. Nothing logs, nothing is wrong on the asset, " +
                "and the species just quietly stops being itself.\n" + string.Join("\n", offenders));
        }

        // ── (b) the band stays under the reward cap ──────────────────────────

        [Test]
        public void SafeCeiling_SitsUnderTheCollectRewardSaturation()
        {
            float saturation = RewardSaturationWorldScale();

            Assert.Less(ElementalCrystalSetSO.MaxSafeHeartWorldScale, saturation,
                $"MaxSafeHeartWorldScale ({ElementalCrystalSetSO.MaxSafeHeartWorldScale}) must stay " +
                $"below the reward saturation scale ({saturation}, = maxLevelGainPerCrystal / " +
                "levelPerUnitScale from " + RewardEffectPath + "). It exists to hold the authored " +
                "heart band clear of the cap with margin — if the reward asset is retuned, this " +
                "constant and the authoring script's HEART_MAX move with it. Do NOT answer an " +
                "overshoot by retuning levelPerUnitScale: that constant is shared with every " +
                "non-lifeform elemental crystal (the Wanderway conveyor, Dog Fight's arena scatter).");
        }

        [Test]
        public void NoHeartExceedsTheSafeCeiling()
        {
            var offenders = ReadCanonical()
                .Where(c => c.HasHeart && c.Heart > ElementalCrystalSetSO.MaxSafeHeartWorldScale)
                .Select(c => $"  {c.Name}: {c.Heart}")
                .ToList();

            Assert.IsEmpty(offenders,
                $"Authored hearts must stay at or under ElementalCrystalSetSO.MaxSafeHeartWorldScale " +
                $"({ElementalCrystalSetSO.MaxSafeHeartWorldScale}).\n" + string.Join("\n", offenders));
        }

        [Test]
        public void NoHeartReachesTheCollectRewardCap()
        {
            float saturation = RewardSaturationWorldScale();

            var offenders = ReadCanonical()
                .Where(c => c.HasHeart && c.Heart >= saturation)
                .Select(c => $"  {c.Name}: {c.Heart} (saturates at {saturation})")
                .ToList();

            Assert.IsEmpty(offenders,
                "A heart at or past the reward cap is a size the player can see and a reward they " +
                "cannot: it pays exactly what a smaller heart pays, so the ecology stops rewarding " +
                "a bigger kill. The whole authored band must sit strictly below the saturation " +
                "scale.\n" + string.Join("\n", offenders));
        }

        [Test]
        public void EveryHeartStaysAVisiblePickup()
        {
            // Read C in the authoring script: a crystal prefab's root SphereCollider is radius
            // 1, so the world trigger radius EQUALS the root world scale. A hairline heart is
            // one a skimmer can fly through.
            // Scoped to an AUTHORED size: the 0 sentinel is 'nobody sized this yet', which is
            // EveryCanonicalLifeformAuthorsAHeartSize's finding, not this one's.
            var offenders = ReadCanonical()
                .Where(c => c.HasHeart && c.Heart > 0f && c.Heart < 1f)
                .Select(c => $"  {c.Name}: {c.Heart}")
                .ToList();

            Assert.IsEmpty(offenders,
                "A heart's root world scale IS its pickup radius (every elemental crystal prefab's " +
                "root SphereCollider is radius 1), so the authored band has a floor of 1 — " +
                "HEART_MIN in Tools/Build/author_lifeform_heart_sizes.py. Lowering the floor is a " +
                "deliberate change to both.\n" +
                string.Join("\n", offenders));
        }

        // ── (c) the retired level surface is gone from the data too ──────────

        [Test]
        public void NoAssetStillCarriesARetiredLifeformLevelField()
        {
            var pattern = new Regex(
                $@"^\s*({string.Join("|", RetiredLevelFields.Select(Regex.Escape))}):",
                RegexOptions.Multiline);

            var offenders = new List<string>();
            foreach (string path in Directory.EnumerateFiles(AssetsRoot, "*.asset", SearchOption.AllDirectories))
            {
                string text;
                try { text = File.ReadAllText(path); }
                catch (IOException) { continue; }

                foreach (Match m in pattern.Matches(text))
                    offenders.Add($"  {path.Replace('\\', '/')}: {m.Groups[1].Value}");
            }

            Assert.IsEmpty(offenders,
                "These serialized fields were removed with lifeform levels (Docs/ECOSYSTEM.md §40). " +
                "Unity never prunes a modification it cannot resolve, so they linger in the YAML and " +
                "read as live authoring to the next person who opens the file. Delete the keys.\n" +
                string.Join("\n", offenders));
        }
    }
}
#endif
