using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

namespace CosmicShore.Utility
{
    /// <summary>
    /// Editor-only preview of the shielded geometry on a prism. Drop onto
    /// any GameObject with a MeshFilter (and a BoxCollider for correct
    /// sizing) and pick a preview mode in the inspector. The MeshFilter's
    /// sharedMesh is swapped to the corresponding shield / super-shield
    /// mesh while the component is enabled; setting the mode back to
    /// <see cref="PreviewMode.None"/> - or disabling / removing the
    /// component - restores the authored mesh.
    ///
    /// The preview mesh is generated by <see cref="OctahedronMeshGenerator"/>
    /// or <see cref="StellatedOctahedronMeshGenerator"/> with the same
    /// CIRCUMSCRIBING_SCALE = 3 used at runtime, so the editor view
    /// matches what the runtime <c>PrismOctahedronShield</c> /
    /// <c>PrismStellatedOctahedronShield</c> would produce on the same
    /// box dimensions.
    ///
    /// Component is a no-op in player builds - all body work is wrapped
    /// in <c>#if UNITY_EDITOR</c>, so leaving it on a prefab is safe (it
    /// just compiles to an empty MonoBehaviour at runtime).
    /// </summary>
    [ExecuteAlways]
    [DisallowMultipleComponent]
    public class PrismShieldPreview : MonoBehaviour
    {
        public enum PreviewMode
        {
            None = 0,           // Authored cuboid mesh.
            Shielded = 1,       // Octahedron (circumscribing dual).
            SuperShielded = 2,  // Stellated octahedron (Stella Octangula).
        }

        [Tooltip("Editor-time preview of the shielded geometry. Set to None " +
                 "before committing / building. Component is a no-op at runtime.")]
        [SerializeField] private PreviewMode preview = PreviewMode.None;

        [Tooltip("Circumscribing scale factor (default 3). Matches the runtime " +
                 "PrismOctahedronShield / PrismStellatedOctahedronShield value " +
                 "so the preview mirrors the runtime appearance exactly.")]
        [SerializeField] private float shieldScale = OctahedronMeshGenerator.CIRCUMSCRIBING_SCALE;

#if UNITY_EDITOR
        // Cached so we can revert when the mode flips back to None or the
        // component is disabled. Captured once per OnEnable.
        private Mesh _originalMesh;

        // Owned by this component - generated on demand and destroyed when
        // the mode changes or the component is torn down.
        private Mesh _previewMesh;
        private PreviewMode _appliedMode = PreviewMode.None;

        private void OnEnable()
        {
            CaptureOriginal();
            EditorApplication.delayCall += DeferredApply;
        }

        private void OnDisable()
        {
            EditorApplication.delayCall -= DeferredApply;
            RestoreOriginal();
            DestroyPreviewMesh();
            _appliedMode = PreviewMode.None;
        }

        private void OnValidate()
        {
            // OnValidate runs during serialization; defer mesh ops one tick
            // so we don't allocate / destroy during a serialization pass.
            EditorApplication.delayCall += DeferredApply;
        }

        private void DeferredApply()
        {
            if (this == null) return;          // component / GO destroyed
            if (Application.isPlaying) return;  // runtime shields handle this
            ApplyPreview();
        }

        private void CaptureOriginal()
        {
            var mf = GetComponent<MeshFilter>();
            if (mf == null) return;
            // Don't recapture if we're already showing our own preview mesh.
            if (_originalMesh == null && mf.sharedMesh != _previewMesh)
                _originalMesh = mf.sharedMesh;
        }

        private void ApplyPreview()
        {
            var mf = GetComponent<MeshFilter>();
            if (mf == null) return;

            CaptureOriginal();

            if (_appliedMode == preview) return;

            DestroyPreviewMesh();

            switch (preview)
            {
                case PreviewMode.None:
                    mf.sharedMesh = _originalMesh;
                    break;
                case PreviewMode.Shielded:
                    _previewMesh = OctahedronMeshGenerator.Generate(GetHalfExtents(), shieldScale);
                    _previewMesh.name = "PrismShieldPreview_Octahedron";
                    _previewMesh.hideFlags = HideFlags.DontSave;
                    mf.sharedMesh = _previewMesh;
                    break;
                case PreviewMode.SuperShielded:
                    _previewMesh = StellatedOctahedronMeshGenerator.Generate(GetHalfExtents(), shieldScale);
                    _previewMesh.name = "PrismShieldPreview_StellatedOctahedron";
                    _previewMesh.hideFlags = HideFlags.DontSave;
                    mf.sharedMesh = _previewMesh;
                    break;
            }

            _appliedMode = preview;
        }

        private void RestoreOriginal()
        {
            var mf = GetComponent<MeshFilter>();
            if (mf == null) return;
            if (_originalMesh != null && mf.sharedMesh == _previewMesh)
                mf.sharedMesh = _originalMesh;
        }

        private void DestroyPreviewMesh()
        {
            if (_previewMesh != null)
            {
                if (Application.isPlaying)
                    Destroy(_previewMesh);
                else
                    DestroyImmediate(_previewMesh);
                _previewMesh = null;
            }
        }

        private Vector3 GetHalfExtents()
        {
            var box = GetComponent<BoxCollider>();
            return box != null ? box.size * 0.5f : Vector3.one * 0.5f;
        }
#endif
    }
}
