using System.Collections.Generic;
using CosmicShore.ScriptableObjects;
using CosmicShore.Utility;
using UnityEngine;

namespace CosmicShore.Gameplay
{
    /// <summary>
    /// Switchback - the Dolphin-only gate race. A course of randomly placed and randomly
    /// oriented SWITCH rings is scattered through the cell, and every pilot flies the SAME
    /// course in ORDER. The first domain whose lead runner threads the last gate wins.
    ///
    /// <para>Everything about running a gate race - the broadcast, the rings, the crossing
    /// detection, the optimistic report/reconcile round trip, the AI steering and the final
    /// scores - lives in <see cref="GateRaceController"/>, shared with Headlong. This class is
    /// what makes it SWITCHBACK: an open chain, flown once, generated by a walk whose constraint
    /// is REACHABILITY (can a Dolphin get from this gate to the next one without exceeding its
    /// turn cap), and which can therefore legitimately fail and back off.</para>
    ///
    /// <para><b>What the mode does NOT add:</b> no new weapon, no new ability, no cell of its
    /// own. The Dolphin's shipped kit already supplies the racing: skim to bank energy, drift to
    /// carve a corner, boost down a straight - and the crystal blast, which debuffs a rival pilot
    /// in every mode since The Bends wired it, is the interference. The passive crystal seeding
    /// keeps a handful of collectable omni crystals in the cytoplasm, so the ammunition for that
    /// is on the course rather than authored by this mode.</para>
    /// </summary>
    public class SwitchbackController : GateRaceController
    {
        [Header("Switchback course")]
        [Tooltip("Where gate 1 sits, as a distance along the spawn formation's POLE. Pilots spawn " +
                 "on an equatorial ring, so a point on that ring's axis is the only place every " +
                 "pilot is equidistant from - which is what makes the start fair.")]
        [SerializeField, Min(1f)] float firstGateDistance = 620f;

        protected override string ModeName => "Switchback";

        public override int AuthoredGateTarget()
        {
            var overrides = EndConditionOverridesSO.Instance;
            return overrides != null
                ? overrides.GetSwitchbackGateTarget()
                : EndConditionOverridesSO.DefaultSwitchbackGateTarget;
        }

        /// <summary>
        /// An open chain: the walk CAN fail (its constraint is reachability, and a shell too
        /// tight for the requested gate count is a configuration fault), so this backs off -
        /// halving the ask until the walk succeeds, floor 2 - rather than returning nothing.
        /// Whatever comes back is then the authoritative target, so a shortened course still has
        /// a finish line rather than an unreachable one.
        /// </summary>
        protected override List<RaceGate> BuildCourse(int seed, int gateCount, float inner, float outer)
        {
            var settings = SwitchbackCourseSettings.ForIntensity(Intensity);
            settings.InnerRadius = inner;
            settings.OuterRadius = outer;
            settings.FirstGateDirection = Vector3.up;   // the equatorial spawn ring's pole
            settings.FirstGateDistance = Mathf.Clamp(firstGateDistance, inner, outer);

            int ask = Mathf.Max(2, gateCount);
            while (ask >= 2)
            {
                settings.GateCount = ask;
                var course = SwitchbackCourse.Generate(seed, settings);
                if (course != null && course.Count >= ask) return course;

                if (ask == 2) return null;
                ask = Mathf.Max(2, ask / 2);
                CSDebug.LogWarning(
                    $"[Switchback] Course generation failed for {settings.GateCount} gates in shell " +
                    $"{inner:F0}..{outer:F0} (step {settings.MinStep:F0}..{settings.MaxStep:F0}, " +
                    $"separation {settings.MinSeparation:F0}); retrying with {ask}.");
            }
            return null;
        }
    }
}
