using System.Collections.Generic;
using CosmicShore.ScriptableObjects;
using CosmicShore.Utility;
using UnityEngine;

namespace CosmicShore.Gameplay
{
    /// <summary>
    /// Switchback - the Dolphin-only gate race. A course of randomly placed and randomly
    /// oriented SWITCH rings is scattered through the cell, and every pilot flies the SAME
    /// course in ORDER. The first domain whose lead runner threads the last gate wins.
    ///
    /// <para>Everything about running a gate race - the broadcast, the rings, the crossing
    /// detection, the optimistic report/reconcile round trip, the AI steering and the final
    /// scores - lives in <see cref="GateRaceController"/>, shared with Headlong. This class is
    /// what makes it SWITCHBACK: an open chain, flown once, generated by a walk whose constraint
    /// is REACHABILITY (can a Dolphin get from this gate to the next one without exceeding its
    /// turn cap), and which can therefore legitimately fail and back off.</para>
    ///
    /// <para><b>What the mode does NOT add:</b> no new weapon, no new ability, no cell of its
    /// own. The Dolphin's shipped kit already supplies the racing: skim to bank energy, drift to
    /// carve a corner, boost down a straight - and the crystal blast, which debuffs a rival pilot
    /// in every mode since The Bends wired it, is the interference. The passive crystal seeding
    /// keeps a handful of collectable omni crystals in the cytoplasm, so the ammunition for that
    /// is on the course rather than authored by this mode.</para>
    /// </summary>
    public class SwitchbackController : GateRaceController
    {
        [Header("Switchback course")]
        [Tooltip("Where gate 1 sits, as a distance along the spawn formation's POLE. Pilots spawn " +
                 "on an equatorial ring, so a point on that ring's axis is the only place every " +
                 "pilot is equidistant from - which is what makes the start fair.")]
        [SerializeField, Min(1f)] float firstGateDistance = SwitchbackCourseSource.DefaultFirstGateDistance;

        protected override string ModeName => "Switchback";

        protected override RaceCourseSource CreateCourseSource() =>
            new SwitchbackCourseSource { FirstGateDistance = firstGateDistance };
    }
}
