#!/usr/bin/env python3
"""domain_colors.py - the Vessel Studio's domain colours, taken from the GAME's palette so the studios, the project
and Amoebius show the same Jade, Ruby, Gold and Blue (the user, 2026-10-09; /vessel-studio section 1.5.5).

Source of truth: Assets/_SO_Assets/Color Palettes/OriginalColorSetSO.asset, the live SO_ColorSet (Docs/PALETTE.md).
Per domain it reads TrailHighlightColor, which is SO_ColorSet.GetDomainUIColor, "the palette's answer to what colour
is this team", and derives GetDomainSignalColor (the brightest channel driven to 1, hue kept), which the game uses
to say "this belongs to domain X" on a surface that must be unmistakable. A UI float maps 1:1 to a display byte
(Docs/PALETTE.md section 2.9), so the hex is round(float * 255).

    python3 .claude/skills/vessel-studio/domain_colors.py            # write Docs/Studios/VesselStudio/studio-domains.js
    python3 .claude/skills/vessel-studio/domain_colors.py --check    # exit 1 if the file, or Amoebius, drifted
    python3 .claude/skills/vessel-studio/domain_colors.py --self-test

--check also proves Amoebius agrees (its launcher's JADE / RUBY / GOLD accent themes, Port/src/CosmicShore.Launcher/Neon.cs,
lead with the signal colour): Port/src/CosmicShore.Client/SkimRaceTheme.cs transcribes the same asset into
the engine, and its TrailHighlightColor per domain must equal the asset's.
"""
import re
import sys

ASSET = 'Assets/_SO_Assets/Color Palettes/OriginalColorSetSO.asset'
AMOEBIUS = 'Port/src/CosmicShore.Client/SkimRaceTheme.cs'
LAUNCHER = 'Port/src/CosmicShore.Launcher/Neon.cs'   # its JADE / RUBY / GOLD accent themes lead with the signal colour
LAUNCHER_THEME = {'jade': 1, 'ruby': 2, 'gold': 3}
OUT = 'Docs/Studios/VesselStudio/studio-domains.js'
# Domains.cs: Jade = 1, Ruby = 2, Blue = 3, Gold = 4. Listed in the order a studio offers them: the three domains a
# player can fly in the game first, then Blue, which the game uses as its neutral "no team" domain (PALETTE.md 2.8).
DOMAINS = [('jade', 'Jade', 1, 'JadeColors', True), ('ruby', 'Ruby', 2, 'RubyColors', True),
           ('gold', 'Gold', 4, 'GoldColors', True), ('blue', 'Blue', 3, 'BlueColors', False)]
NUM = r'(-?[\d.]+(?:e-?\d+)?)'


def asset_colors(text):
    out = {}
    for key, _, _, block, _ in DOMAINS:
        i = text.find('  ' + block + ':')
        if i < 0:
            raise SystemExit('domain_colors: %s has no %s block' % (ASSET, block))
        m = re.search(r'TrailHighlightColor: \{r: %s, g: %s, b: %s' % (NUM, NUM, NUM), text[i:i + 6000])
        if not m:
            raise SystemExit('domain_colors: %s.%s has no TrailHighlightColor' % (ASSET, block))
        out[key] = tuple(float(x) for x in m.groups())
    return out


def amoebius_colors(text):
    out = {}
    for key, _, _, block, _ in DOMAINS:
        i = text.find('colorSet.' + block + ' = new DomainColorSet')
        if i < 0:
            continue
        m = re.search(r'TrailHighlightColor = new Color\(%sf, %sf, %sf' % (NUM, NUM, NUM), text[i:i + 3000])
        if m:
            out[key] = tuple(float(x) for x in m.groups())
    return out


def hexof(c):
    return '#%02x%02x%02x' % tuple(max(0, min(255, round(v * 255))) for v in c)


def signal(c):
    peak = max(c)
    return (1.0, 1.0, 1.0) if peak <= 0.001 else tuple(v / peak for v in c)


def make(cols):
    rows = []
    for key, name, gid, _, playable in DOMAINS:
        ui, sig = hexof(cols[key]), hexof(signal(cols[key]))
        rows.append("    { key: '%s', name: '%s', id: %d, color: '%s', hex: 0x%s, ui: '%s', playable: %s }"
                    % (key, name, gid, sig, sig[1:], ui, 'true' if playable else 'false'))
    return ('/* studio-domains.js - GENERATED by .claude/skills/vessel-studio/domain_colors.py; do not edit by hand.\n'
            ' * The game\'s four domain colours, read from ' + ASSET + '\n'
            ' * (TrailHighlightColor = SO_ColorSet.GetDomainUIColor), the same asset Amoebius renders with.\n'
            ' *   color / hex  GetDomainSignalColor: the team colour at full strength, for hulls, seats, markers, lines\n'
            ' *   ui           GetDomainUIColor: the raw UI colour, for flat text and cards\n'
            ' *   playable     false for Blue, the game\'s neutral "no team" domain (Docs/PALETTE.md 2.8)\n'
            ' * Every studio takes its domain colours from here (/vessel-studio 1.5.5), never from its own table.\n'
            ' */\n'
            '(function () {\n'
            "  'use strict';\n"
            '  var DOMAINS = [\n' + ',\n'.join(rows) + '\n  ];\n'
            '  var BY = {}; DOMAINS.forEach(function (d) { BY[d.key] = d; });\n'
            '  window.VesselStudioDomains = { list: DOMAINS, get: function (key) { return BY[key] || DOMAINS[0]; } };\n'
            '  // CSS gets them too: var(--jade), var(--ruby), var(--gold), var(--blue) match the game in every page\n'
            '  var root = document.documentElement;\n'
            "  DOMAINS.forEach(function (d) { root.style.setProperty('--' + d.key, d.color); });\n"
            '})();\n')


def launcher_colors(text):
    out = {}
    for key, n in LAUNCHER_THEME.items():
        m = re.search(r'\b%d => \(V\(%sf, %sf, %sf\)' % (n, NUM, NUM, NUM), text)
        if m:
            out[key] = tuple(float(x) for x in m.groups())
    return out


def check(asset_text, amoebius_text, have, launcher_text=None):
    errs = []
    cols = asset_colors(asset_text)
    if have != make(cols):
        errs.append(OUT + ' is stale: run domain_colors.py')
    am = amoebius_colors(amoebius_text)
    for key, name, _, _, _ in DOMAINS:
        if key not in am:
            errs.append('Amoebius (%s) has no %s TrailHighlightColor' % (AMOEBIUS, name))
        elif any(abs(a - b) > 1e-4 for a, b in zip(am[key], cols[key])):
            errs.append('Amoebius %s %s != the project asset %s' % (name, am[key], cols[key]))
    if launcher_text is not None:
        la = launcher_colors(launcher_text)
        for key in LAUNCHER_THEME:
            want = signal(cols[key])
            if key not in la or any(abs(a - b) > 0.002 for a, b in zip(la[key], want)):
                errs.append('Amoebius launcher theme %s %s != the game signal colour %s' % (key.upper(), la.get(key), tuple(round(v, 3) for v in want)))
    return errs


def self_test():
    asset = open(ASSET, encoding='utf-8').read()
    amo = open(AMOEBIUS, encoding='utf-8').read()
    good = make(asset_colors(asset))
    bad = []
    if check(asset, amo, good):
        bad.append('a clean tree reports drift: ' + repr(check(asset, amo, good)))
    if not any('stale' in e for e in check(asset, amo, good.replace("name: 'Ruby'", "name: 'Rubi'"))):
        bad.append('a hand-edited table was not caught')
    planted = re.sub(r'(colorSet\.RubyColors = new DomainColorSet[\s\S]*?TrailHighlightColor = new Color\()[\d.]+f',
                     r'\g<1>0.5f', amo, count=1)
    if not any('Amoebius Ruby' in e for e in check(asset, planted, good)):
        bad.append('an Amoebius palette drift was not caught')
    lt = open(LAUNCHER, encoding='utf-8').read()
    if check(asset, amo, good, lt):
        bad.append('the launcher reports drift: ' + repr(check(asset, amo, good, lt)))
    if not any('launcher theme RUBY' in e for e in check(asset, amo, good, lt.replace('2 => (V(1.000f', '2 => (V(0.900f'))):
        bad.append('a launcher theme drift was not caught')
    if not good.isascii():
        bad.append('the generated file is not ASCII')
    print('domain_colors self-test: ' + ('ok' if not bad else 'FAILED ' + repr(bad)))
    return 0 if not bad else 1


if __name__ == '__main__':
    if '--self-test' in sys.argv:
        sys.exit(self_test())
    asset = open(ASSET, encoding='utf-8').read()
    if '--check' in sys.argv:
        try:
            have = open(OUT, encoding='utf-8').read()
        except OSError:
            have = ''
        errs = check(asset, open(AMOEBIUS, encoding='utf-8').read(), have, open(LAUNCHER, encoding='utf-8').read())
        print('domain_colors: ' + ('project, Amoebius and the studios agree' if not errs else '; '.join(errs)))
        sys.exit(1 if errs else 0)
    open(OUT, 'w', encoding='utf-8', newline='').write(make(asset_colors(asset)))
    print('domain_colors: wrote ' + OUT)
