// Remember folks, only you can prevent Unity from arbitrarily swapping enum values in files.
// Always assign a static numeric value to your enum types
public enum MiniGames
{
    Random = 0,
    Elimination = 1,
    Rampage = 2,
    Darts = 3,
    ShootingGallery = 4,
    BlockBandit = 5,
    RiskyDriftness = 6,
    Freestyle = 7,
    CellularDuel = 8,
    DashNGrab = 9,
    CellularBrawl = 10,
    Denial = 11,
    CatNMouse = 12,
    SlipNStride = 13,
    PumpNDump = 14,
    MasterExploder = 15,
    Soar = 16,
    ObstacleCourse = 17,
    Distraction = 18,
    RhinoRun = 19,
    KickinMass = 20,
    Sidewinder = 21,
    Multipass = 22,
    BotDuel = 23,
    Curvatious = 24,
}