"""Build the flyable ecology.

    python Tools/Ecology/flight/build.py           # src/*.js -> sim.js ; index_src.html + sim.js + params.json -> index.html
    python Tools/Ecology/flight/build.py --check    # fail if sim.js / index.html are stale

sim.js is ONE file used two ways: Node `require`s it for the headless fidelity gate (fidelity_js.js), and the page
inlines it. So the page flies exactly the code the gate measured. index.html is self-contained apart from three.js
r128 from cdn.jsdelivr.net (the only external host).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src")


def sim_js():
    parts = [open(os.path.join(SRC, f)).read() for f in sorted(os.listdir(SRC)) if f.endswith(".js")]
    body = "\n".join(parts)
    exports = ("Rng, SpatialHash, Arena, Pilot, Herd, Pack, Thief, Locust, Lurker, Stampede, Leviathan, Mobber, Grazer, "
               "Fortress, SnapTrap, PlantBody, Probe, runOne, FlightWorld, SPECIES, WORLD, POLICIES, makePilot, "
               "median, mean, percentile, clamp, Stakes, TeleTrack, ELEMENTS, ELEMENT_COLOUR, STAKES_RULES, DANGER_KINDS, SPECIES_ELEMENT, PETAL, LEVEL_MAX")
    return ("// GENERATED by flight/build.py from flight/src/*.js - edit the sources, not this file.\n"
            "(function (root) {\n" + body + f"\nconst EcoSim = {{ {exports} }};\n"
            "if (typeof module !== 'undefined' && module.exports) module.exports = EcoSim; else root.EcoSim = EcoSim;\n"
            "})(typeof window !== 'undefined' ? window : globalThis);\n")


def index_html(sim):
    tpl = open(os.path.join(HERE, "index_src.html")).read()
    params = open(os.path.join(HERE, "params.json")).read()
    fid = os.path.join(HERE, "results", "fidelity.json")
    fsum = json.dumps(json.load(open(fid)).get("summary", {})) if os.path.exists(fid) else "{}"
    out = tpl.replace("/*__SIM__*/", sim).replace("/*__PARAMS__*/null", json.dumps(json.loads(params), separators=(",", ":")))
    return out.replace("/*__FIDELITY__*/null", fsum)


if __name__ == "__main__":
    sim = sim_js()
    targets = {os.path.join(HERE, "sim.js"): sim}
    if os.path.exists(os.path.join(HERE, "index_src.html")):
        targets[os.path.join(HERE, "index.html")] = index_html(sim)
    if "--check" in sys.argv:
        bad = [p for p, t in targets.items() if not os.path.exists(p) or open(p).read() != t]
        for p in bad:
            print("STALE:", os.path.relpath(p, HERE))
        sys.exit(1 if bad else 0)
    for p, t in targets.items():
        open(p, "w").write(t)
        print(os.path.relpath(p, HERE), f"{len(t) / 1024:.0f} KB")
