using System;
using UnityEngine;

namespace CosmicShore.Game
{
    /// <summary>
    /// Baked animation preset for <see cref="CapsuleMembrane"/>.
    ///
    /// Stores the membrane's static per-capsule layout and a seamless loop of
    /// per-capsule rotations, all precomputed offline. At runtime the membrane
    /// interpolates this data instead of running Perlin-noise, quaternion and
    /// matrix math for every capsule every frame.
    ///
    /// Generated by the "Bake Animation Preset" button on the CapsuleMembrane
    /// inspector - not meant to be authored by hand.
    /// </summary>
    [CreateAssetMenu(fileName = "CapsuleMembraneAnimation",
        menuName = "ScriptableObjects/Environment/Capsule Membrane Animation")]
    public class CapsuleMembraneAnimationSO : ScriptableObject
    {
        /// <summary>
        /// Fingerprint of the CapsuleMembrane settings a preset was baked from.
        /// Used to detect when the membrane has been re-tuned and the bake is stale.
        /// </summary>
        [Serializable]
        public struct BakeSignature
        {
            public int subdivisions;
            public float radius;
            public int seed;
            public float placementJitter;
            public float radialJitter;
            public float noiseFrequency;
            public float noiseAmplitude;
            public float pulseSpeed;
            public float loopDuration;
            public int bakeFps;

            public bool Matches(in BakeSignature o) =>
                subdivisions == o.subdivisions
                && radius == o.radius
                && seed == o.seed
                && placementJitter == o.placementJitter
                && radialJitter == o.radialJitter
                && noiseFrequency == o.noiseFrequency
                && noiseAmplitude == o.noiseAmplitude
                && pulseSpeed == o.pulseSpeed
                && loopDuration == o.loopDuration
                && bakeFps == o.bakeFps;
        }

        [Header("Baked data - generated by CapsuleMembrane's Bake button. Do not edit by hand.")]
        [SerializeField] int capsuleCount;
        [SerializeField] int frameCount;
        [SerializeField] float loopDuration;
        [SerializeField] BakeSignature signature;

        // Static local-space position of each capsule, relative to the membrane center.
        [HideInInspector, SerializeField] Vector3[] capsuleOffsets;

        // Per-frame, per-capsule rotations (frameCount * capsuleCount, frame-major),
        // packed as raw quaternion floats then Base64-encoded so the asset stores the
        // blob as one compact string instead of millions of YAML nodes.
        [HideInInspector, SerializeField] string rotationData;

        [NonSerialized] Quaternion[] _rotations;

        public int CapsuleCount => capsuleCount;
        public int FrameCount => frameCount;
        public float LoopDuration => loopDuration;
        public Vector3[] CapsuleOffsets => capsuleOffsets;
        public BakeSignature Signature => signature;

        /// <summary>True when this preset holds a complete, usable bake.</summary>
        public bool IsValid =>
            capsuleCount > 0
            && frameCount > 1
            && loopDuration > 0f
            && capsuleOffsets != null
            && capsuleOffsets.Length == capsuleCount
            && !string.IsNullOrEmpty(rotationData);

        /// <summary>
        /// Decoded per-frame rotations, frame-major: index <c>[frame * CapsuleCount + capsule]</c>.
        /// Decoded once on first access and cached for the asset's lifetime.
        /// </summary>
        public Quaternion[] Rotations
        {
            get
            {
                if (_rotations == null)
                    Decode();
                return _rotations;
            }
        }

        void Decode()
        {
            int n = Mathf.Max(0, frameCount * capsuleCount);
            _rotations = new Quaternion[n];
            if (n == 0 || string.IsNullOrEmpty(rotationData)) return;

            byte[] bytes = Convert.FromBase64String(rotationData);
            var floats = new float[n * 4];
            Buffer.BlockCopy(bytes, 0, floats, 0, Mathf.Min(bytes.Length, floats.Length * 4));
            for (int i = 0; i < n; i++)
            {
                int f = i * 4;
                _rotations[i] = new Quaternion(floats[f], floats[f + 1], floats[f + 2], floats[f + 3]);
            }
        }

        /// <summary>Overwrites this preset with a freshly baked animation.</summary>
        public void SetBakedData(Vector3[] offsets, Quaternion[] rotations,
                                 int count, int frames, float duration, in BakeSignature sig)
        {
            capsuleCount = count;
            frameCount = frames;
            loopDuration = duration;
            capsuleOffsets = offsets;
            signature = sig;

            int n = count * frames;
            var floats = new float[n * 4];
            for (int i = 0; i < n; i++)
            {
                int f = i * 4;
                floats[f] = rotations[i].x;
                floats[f + 1] = rotations[i].y;
                floats[f + 2] = rotations[i].z;
                floats[f + 3] = rotations[i].w;
            }
            var bytes = new byte[floats.Length * 4];
            Buffer.BlockCopy(floats, 0, bytes, 0, bytes.Length);
            rotationData = Convert.ToBase64String(bytes);

            _rotations = null;
        }
    }
}
