// <auto-generated>
// Generated by the port's math shim generator (first-party). Behavior-level re-implementation
// of the Unity.Mathematics public API surface the game compiles against; not vendored source.
// </auto-generated>
using System;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace Unity.Mathematics
{
    [Serializable]
    public partial struct bool2 : IEquatable<bool2>, IFormattable
    {
        public bool x;
        public bool y;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool2(bool x, bool y) { this.x = x; this.y = y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool2(bool2 xy) { this.x = xy.x; this.y = xy.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool2(bool v) { x = v; y = v; }
        public static implicit operator bool2(bool v) => new bool2(v);
        public static bool2 operator ==(bool2 a, bool2 b) => new bool2(a.x == b.x, a.y == b.y);
        public static bool2 operator ==(bool2 a, bool b) => new bool2(a.x == b, a.y == b);
        public static bool2 operator ==(bool a, bool2 b) => new bool2(a == b.x, a == b.y);
        public static bool2 operator !=(bool2 a, bool2 b) => new bool2(a.x != b.x, a.y != b.y);
        public static bool2 operator !=(bool2 a, bool b) => new bool2(a.x != b, a.y != b);
        public static bool2 operator !=(bool a, bool2 b) => new bool2(a != b.x, a != b.y);
        public static bool2 operator &(bool2 a, bool2 b) => new bool2(a.x & b.x, a.y & b.y);
        public static bool2 operator &(bool2 a, bool b) => new bool2(a.x & b, a.y & b);
        public static bool2 operator &(bool a, bool2 b) => new bool2(a & b.x, a & b.y);
        public static bool2 operator |(bool2 a, bool2 b) => new bool2(a.x | b.x, a.y | b.y);
        public static bool2 operator |(bool2 a, bool b) => new bool2(a.x | b, a.y | b);
        public static bool2 operator |(bool a, bool2 b) => new bool2(a | b.x, a | b.y);
        public static bool2 operator ^(bool2 a, bool2 b) => new bool2(a.x ^ b.x, a.y ^ b.y);
        public static bool2 operator ^(bool2 a, bool b) => new bool2(a.x ^ b, a.y ^ b);
        public static bool2 operator ^(bool a, bool2 b) => new bool2(a ^ b.x, a ^ b.y);
        public static bool2 operator !(bool2 v) => new bool2(!v.x, !v.y);
        public bool this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly bool2 xx => new bool2(x, x);
        public bool2 xy { readonly get => new bool2(x, y); set { x = value.x; y = value.y; } }
        public bool2 yx { readonly get => new bool2(y, x); set { y = value.x; x = value.y; } }
        public readonly bool2 yy => new bool2(y, y);
        public readonly bool3 xxx => new bool3(x, x, x);
        public readonly bool3 xxy => new bool3(x, x, y);
        public readonly bool3 xyx => new bool3(x, y, x);
        public readonly bool3 xyy => new bool3(x, y, y);
        public readonly bool3 yxx => new bool3(y, x, x);
        public readonly bool3 yxy => new bool3(y, x, y);
        public readonly bool3 yyx => new bool3(y, y, x);
        public readonly bool3 yyy => new bool3(y, y, y);
        public readonly bool4 xxxx => new bool4(x, x, x, x);
        public readonly bool4 xxxy => new bool4(x, x, x, y);
        public readonly bool4 xxyx => new bool4(x, x, y, x);
        public readonly bool4 xxyy => new bool4(x, x, y, y);
        public readonly bool4 xyxx => new bool4(x, y, x, x);
        public readonly bool4 xyxy => new bool4(x, y, x, y);
        public readonly bool4 xyyx => new bool4(x, y, y, x);
        public readonly bool4 xyyy => new bool4(x, y, y, y);
        public readonly bool4 yxxx => new bool4(y, x, x, x);
        public readonly bool4 yxxy => new bool4(y, x, x, y);
        public readonly bool4 yxyx => new bool4(y, x, y, x);
        public readonly bool4 yxyy => new bool4(y, x, y, y);
        public readonly bool4 yyxx => new bool4(y, y, x, x);
        public readonly bool4 yyxy => new bool4(y, y, x, y);
        public readonly bool4 yyyx => new bool4(y, y, y, x);
        public readonly bool4 yyyy => new bool4(y, y, y, y);
        public readonly bool Equals(bool2 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y);
        public override readonly bool Equals(object o) => o is bool2 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "bool2({0}, {1})", x, y);
        public readonly string ToString(string format, IFormatProvider formatProvider) => ToString();
    }

    [Serializable]
    public partial struct bool3 : IEquatable<bool3>, IFormattable
    {
        public bool x;
        public bool y;
        public bool z;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool3(bool x, bool y, bool z) { this.x = x; this.y = y; this.z = z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool3(bool x, bool2 yz) { this.x = x; this.y = yz.x; this.z = yz.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool3(bool2 xy, bool z) { this.x = xy.x; this.y = xy.y; this.z = z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool3(bool3 xyz) { this.x = xyz.x; this.y = xyz.y; this.z = xyz.z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool3(bool v) { x = v; y = v; z = v; }
        public static implicit operator bool3(bool v) => new bool3(v);
        public static bool3 operator ==(bool3 a, bool3 b) => new bool3(a.x == b.x, a.y == b.y, a.z == b.z);
        public static bool3 operator ==(bool3 a, bool b) => new bool3(a.x == b, a.y == b, a.z == b);
        public static bool3 operator ==(bool a, bool3 b) => new bool3(a == b.x, a == b.y, a == b.z);
        public static bool3 operator !=(bool3 a, bool3 b) => new bool3(a.x != b.x, a.y != b.y, a.z != b.z);
        public static bool3 operator !=(bool3 a, bool b) => new bool3(a.x != b, a.y != b, a.z != b);
        public static bool3 operator !=(bool a, bool3 b) => new bool3(a != b.x, a != b.y, a != b.z);
        public static bool3 operator &(bool3 a, bool3 b) => new bool3(a.x & b.x, a.y & b.y, a.z & b.z);
        public static bool3 operator &(bool3 a, bool b) => new bool3(a.x & b, a.y & b, a.z & b);
        public static bool3 operator &(bool a, bool3 b) => new bool3(a & b.x, a & b.y, a & b.z);
        public static bool3 operator |(bool3 a, bool3 b) => new bool3(a.x | b.x, a.y | b.y, a.z | b.z);
        public static bool3 operator |(bool3 a, bool b) => new bool3(a.x | b, a.y | b, a.z | b);
        public static bool3 operator |(bool a, bool3 b) => new bool3(a | b.x, a | b.y, a | b.z);
        public static bool3 operator ^(bool3 a, bool3 b) => new bool3(a.x ^ b.x, a.y ^ b.y, a.z ^ b.z);
        public static bool3 operator ^(bool3 a, bool b) => new bool3(a.x ^ b, a.y ^ b, a.z ^ b);
        public static bool3 operator ^(bool a, bool3 b) => new bool3(a ^ b.x, a ^ b.y, a ^ b.z);
        public static bool3 operator !(bool3 v) => new bool3(!v.x, !v.y, !v.z);
        public bool this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; case 2: return z; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly bool2 xx => new bool2(x, x);
        public bool2 xy { readonly get => new bool2(x, y); set { x = value.x; y = value.y; } }
        public bool2 xz { readonly get => new bool2(x, z); set { x = value.x; z = value.y; } }
        public bool2 yx { readonly get => new bool2(y, x); set { y = value.x; x = value.y; } }
        public readonly bool2 yy => new bool2(y, y);
        public bool2 yz { readonly get => new bool2(y, z); set { y = value.x; z = value.y; } }
        public bool2 zx { readonly get => new bool2(z, x); set { z = value.x; x = value.y; } }
        public bool2 zy { readonly get => new bool2(z, y); set { z = value.x; y = value.y; } }
        public readonly bool2 zz => new bool2(z, z);
        public readonly bool3 xxx => new bool3(x, x, x);
        public readonly bool3 xxy => new bool3(x, x, y);
        public readonly bool3 xxz => new bool3(x, x, z);
        public readonly bool3 xyx => new bool3(x, y, x);
        public readonly bool3 xyy => new bool3(x, y, y);
        public bool3 xyz { readonly get => new bool3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
        public readonly bool3 xzx => new bool3(x, z, x);
        public bool3 xzy { readonly get => new bool3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
        public readonly bool3 xzz => new bool3(x, z, z);
        public readonly bool3 yxx => new bool3(y, x, x);
        public readonly bool3 yxy => new bool3(y, x, y);
        public bool3 yxz { readonly get => new bool3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
        public readonly bool3 yyx => new bool3(y, y, x);
        public readonly bool3 yyy => new bool3(y, y, y);
        public readonly bool3 yyz => new bool3(y, y, z);
        public bool3 yzx { readonly get => new bool3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
        public readonly bool3 yzy => new bool3(y, z, y);
        public readonly bool3 yzz => new bool3(y, z, z);
        public readonly bool3 zxx => new bool3(z, x, x);
        public bool3 zxy { readonly get => new bool3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
        public readonly bool3 zxz => new bool3(z, x, z);
        public bool3 zyx { readonly get => new bool3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
        public readonly bool3 zyy => new bool3(z, y, y);
        public readonly bool3 zyz => new bool3(z, y, z);
        public readonly bool3 zzx => new bool3(z, z, x);
        public readonly bool3 zzy => new bool3(z, z, y);
        public readonly bool3 zzz => new bool3(z, z, z);
        public readonly bool4 xxxx => new bool4(x, x, x, x);
        public readonly bool4 xxxy => new bool4(x, x, x, y);
        public readonly bool4 xxxz => new bool4(x, x, x, z);
        public readonly bool4 xxyx => new bool4(x, x, y, x);
        public readonly bool4 xxyy => new bool4(x, x, y, y);
        public readonly bool4 xxyz => new bool4(x, x, y, z);
        public readonly bool4 xxzx => new bool4(x, x, z, x);
        public readonly bool4 xxzy => new bool4(x, x, z, y);
        public readonly bool4 xxzz => new bool4(x, x, z, z);
        public readonly bool4 xyxx => new bool4(x, y, x, x);
        public readonly bool4 xyxy => new bool4(x, y, x, y);
        public readonly bool4 xyxz => new bool4(x, y, x, z);
        public readonly bool4 xyyx => new bool4(x, y, y, x);
        public readonly bool4 xyyy => new bool4(x, y, y, y);
        public readonly bool4 xyyz => new bool4(x, y, y, z);
        public readonly bool4 xyzx => new bool4(x, y, z, x);
        public readonly bool4 xyzy => new bool4(x, y, z, y);
        public readonly bool4 xyzz => new bool4(x, y, z, z);
        public readonly bool4 xzxx => new bool4(x, z, x, x);
        public readonly bool4 xzxy => new bool4(x, z, x, y);
        public readonly bool4 xzxz => new bool4(x, z, x, z);
        public readonly bool4 xzyx => new bool4(x, z, y, x);
        public readonly bool4 xzyy => new bool4(x, z, y, y);
        public readonly bool4 xzyz => new bool4(x, z, y, z);
        public readonly bool4 xzzx => new bool4(x, z, z, x);
        public readonly bool4 xzzy => new bool4(x, z, z, y);
        public readonly bool4 xzzz => new bool4(x, z, z, z);
        public readonly bool4 yxxx => new bool4(y, x, x, x);
        public readonly bool4 yxxy => new bool4(y, x, x, y);
        public readonly bool4 yxxz => new bool4(y, x, x, z);
        public readonly bool4 yxyx => new bool4(y, x, y, x);
        public readonly bool4 yxyy => new bool4(y, x, y, y);
        public readonly bool4 yxyz => new bool4(y, x, y, z);
        public readonly bool4 yxzx => new bool4(y, x, z, x);
        public readonly bool4 yxzy => new bool4(y, x, z, y);
        public readonly bool4 yxzz => new bool4(y, x, z, z);
        public readonly bool4 yyxx => new bool4(y, y, x, x);
        public readonly bool4 yyxy => new bool4(y, y, x, y);
        public readonly bool4 yyxz => new bool4(y, y, x, z);
        public readonly bool4 yyyx => new bool4(y, y, y, x);
        public readonly bool4 yyyy => new bool4(y, y, y, y);
        public readonly bool4 yyyz => new bool4(y, y, y, z);
        public readonly bool4 yyzx => new bool4(y, y, z, x);
        public readonly bool4 yyzy => new bool4(y, y, z, y);
        public readonly bool4 yyzz => new bool4(y, y, z, z);
        public readonly bool4 yzxx => new bool4(y, z, x, x);
        public readonly bool4 yzxy => new bool4(y, z, x, y);
        public readonly bool4 yzxz => new bool4(y, z, x, z);
        public readonly bool4 yzyx => new bool4(y, z, y, x);
        public readonly bool4 yzyy => new bool4(y, z, y, y);
        public readonly bool4 yzyz => new bool4(y, z, y, z);
        public readonly bool4 yzzx => new bool4(y, z, z, x);
        public readonly bool4 yzzy => new bool4(y, z, z, y);
        public readonly bool4 yzzz => new bool4(y, z, z, z);
        public readonly bool4 zxxx => new bool4(z, x, x, x);
        public readonly bool4 zxxy => new bool4(z, x, x, y);
        public readonly bool4 zxxz => new bool4(z, x, x, z);
        public readonly bool4 zxyx => new bool4(z, x, y, x);
        public readonly bool4 zxyy => new bool4(z, x, y, y);
        public readonly bool4 zxyz => new bool4(z, x, y, z);
        public readonly bool4 zxzx => new bool4(z, x, z, x);
        public readonly bool4 zxzy => new bool4(z, x, z, y);
        public readonly bool4 zxzz => new bool4(z, x, z, z);
        public readonly bool4 zyxx => new bool4(z, y, x, x);
        public readonly bool4 zyxy => new bool4(z, y, x, y);
        public readonly bool4 zyxz => new bool4(z, y, x, z);
        public readonly bool4 zyyx => new bool4(z, y, y, x);
        public readonly bool4 zyyy => new bool4(z, y, y, y);
        public readonly bool4 zyyz => new bool4(z, y, y, z);
        public readonly bool4 zyzx => new bool4(z, y, z, x);
        public readonly bool4 zyzy => new bool4(z, y, z, y);
        public readonly bool4 zyzz => new bool4(z, y, z, z);
        public readonly bool4 zzxx => new bool4(z, z, x, x);
        public readonly bool4 zzxy => new bool4(z, z, x, y);
        public readonly bool4 zzxz => new bool4(z, z, x, z);
        public readonly bool4 zzyx => new bool4(z, z, y, x);
        public readonly bool4 zzyy => new bool4(z, z, y, y);
        public readonly bool4 zzyz => new bool4(z, z, y, z);
        public readonly bool4 zzzx => new bool4(z, z, z, x);
        public readonly bool4 zzzy => new bool4(z, z, z, y);
        public readonly bool4 zzzz => new bool4(z, z, z, z);
        public readonly bool Equals(bool3 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y) && z.Equals(rhs.z);
        public override readonly bool Equals(object o) => o is bool3 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y, z);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "bool3({0}, {1}, {2})", x, y, z);
        public readonly string ToString(string format, IFormatProvider formatProvider) => ToString();
    }

    [Serializable]
    public partial struct bool4 : IEquatable<bool4>, IFormattable
    {
        public bool x;
        public bool y;
        public bool z;
        public bool w;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool4(bool x, bool y, bool z, bool w) { this.x = x; this.y = y; this.z = z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool4(bool x, bool y, bool2 zw) { this.x = x; this.y = y; this.z = zw.x; this.w = zw.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool4(bool x, bool2 yz, bool w) { this.x = x; this.y = yz.x; this.z = yz.y; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool4(bool x, bool3 yzw) { this.x = x; this.y = yzw.x; this.z = yzw.y; this.w = yzw.z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool4(bool2 xy, bool z, bool w) { this.x = xy.x; this.y = xy.y; this.z = z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool4(bool2 xy, bool2 zw) { this.x = xy.x; this.y = xy.y; this.z = zw.x; this.w = zw.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool4(bool3 xyz, bool w) { this.x = xyz.x; this.y = xyz.y; this.z = xyz.z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool4(bool4 xyzw) { this.x = xyzw.x; this.y = xyzw.y; this.z = xyzw.z; this.w = xyzw.w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public bool4(bool v) { x = v; y = v; z = v; w = v; }
        public static implicit operator bool4(bool v) => new bool4(v);
        public static bool4 operator ==(bool4 a, bool4 b) => new bool4(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
        public static bool4 operator ==(bool4 a, bool b) => new bool4(a.x == b, a.y == b, a.z == b, a.w == b);
        public static bool4 operator ==(bool a, bool4 b) => new bool4(a == b.x, a == b.y, a == b.z, a == b.w);
        public static bool4 operator !=(bool4 a, bool4 b) => new bool4(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
        public static bool4 operator !=(bool4 a, bool b) => new bool4(a.x != b, a.y != b, a.z != b, a.w != b);
        public static bool4 operator !=(bool a, bool4 b) => new bool4(a != b.x, a != b.y, a != b.z, a != b.w);
        public static bool4 operator &(bool4 a, bool4 b) => new bool4(a.x & b.x, a.y & b.y, a.z & b.z, a.w & b.w);
        public static bool4 operator &(bool4 a, bool b) => new bool4(a.x & b, a.y & b, a.z & b, a.w & b);
        public static bool4 operator &(bool a, bool4 b) => new bool4(a & b.x, a & b.y, a & b.z, a & b.w);
        public static bool4 operator |(bool4 a, bool4 b) => new bool4(a.x | b.x, a.y | b.y, a.z | b.z, a.w | b.w);
        public static bool4 operator |(bool4 a, bool b) => new bool4(a.x | b, a.y | b, a.z | b, a.w | b);
        public static bool4 operator |(bool a, bool4 b) => new bool4(a | b.x, a | b.y, a | b.z, a | b.w);
        public static bool4 operator ^(bool4 a, bool4 b) => new bool4(a.x ^ b.x, a.y ^ b.y, a.z ^ b.z, a.w ^ b.w);
        public static bool4 operator ^(bool4 a, bool b) => new bool4(a.x ^ b, a.y ^ b, a.z ^ b, a.w ^ b);
        public static bool4 operator ^(bool a, bool4 b) => new bool4(a ^ b.x, a ^ b.y, a ^ b.z, a ^ b.w);
        public static bool4 operator !(bool4 v) => new bool4(!v.x, !v.y, !v.z, !v.w);
        public bool this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; case 2: return z; case 3: return w; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; case 3: w = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly bool2 xx => new bool2(x, x);
        public bool2 xy { readonly get => new bool2(x, y); set { x = value.x; y = value.y; } }
        public bool2 xz { readonly get => new bool2(x, z); set { x = value.x; z = value.y; } }
        public bool2 xw { readonly get => new bool2(x, w); set { x = value.x; w = value.y; } }
        public bool2 yx { readonly get => new bool2(y, x); set { y = value.x; x = value.y; } }
        public readonly bool2 yy => new bool2(y, y);
        public bool2 yz { readonly get => new bool2(y, z); set { y = value.x; z = value.y; } }
        public bool2 yw { readonly get => new bool2(y, w); set { y = value.x; w = value.y; } }
        public bool2 zx { readonly get => new bool2(z, x); set { z = value.x; x = value.y; } }
        public bool2 zy { readonly get => new bool2(z, y); set { z = value.x; y = value.y; } }
        public readonly bool2 zz => new bool2(z, z);
        public bool2 zw { readonly get => new bool2(z, w); set { z = value.x; w = value.y; } }
        public bool2 wx { readonly get => new bool2(w, x); set { w = value.x; x = value.y; } }
        public bool2 wy { readonly get => new bool2(w, y); set { w = value.x; y = value.y; } }
        public bool2 wz { readonly get => new bool2(w, z); set { w = value.x; z = value.y; } }
        public readonly bool2 ww => new bool2(w, w);
        public readonly bool3 xxx => new bool3(x, x, x);
        public readonly bool3 xxy => new bool3(x, x, y);
        public readonly bool3 xxz => new bool3(x, x, z);
        public readonly bool3 xxw => new bool3(x, x, w);
        public readonly bool3 xyx => new bool3(x, y, x);
        public readonly bool3 xyy => new bool3(x, y, y);
        public bool3 xyz { readonly get => new bool3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
        public bool3 xyw { readonly get => new bool3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
        public readonly bool3 xzx => new bool3(x, z, x);
        public bool3 xzy { readonly get => new bool3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
        public readonly bool3 xzz => new bool3(x, z, z);
        public bool3 xzw { readonly get => new bool3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
        public readonly bool3 xwx => new bool3(x, w, x);
        public bool3 xwy { readonly get => new bool3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
        public bool3 xwz { readonly get => new bool3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
        public readonly bool3 xww => new bool3(x, w, w);
        public readonly bool3 yxx => new bool3(y, x, x);
        public readonly bool3 yxy => new bool3(y, x, y);
        public bool3 yxz { readonly get => new bool3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
        public bool3 yxw { readonly get => new bool3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
        public readonly bool3 yyx => new bool3(y, y, x);
        public readonly bool3 yyy => new bool3(y, y, y);
        public readonly bool3 yyz => new bool3(y, y, z);
        public readonly bool3 yyw => new bool3(y, y, w);
        public bool3 yzx { readonly get => new bool3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
        public readonly bool3 yzy => new bool3(y, z, y);
        public readonly bool3 yzz => new bool3(y, z, z);
        public bool3 yzw { readonly get => new bool3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
        public bool3 ywx { readonly get => new bool3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
        public readonly bool3 ywy => new bool3(y, w, y);
        public bool3 ywz { readonly get => new bool3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
        public readonly bool3 yww => new bool3(y, w, w);
        public readonly bool3 zxx => new bool3(z, x, x);
        public bool3 zxy { readonly get => new bool3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
        public readonly bool3 zxz => new bool3(z, x, z);
        public bool3 zxw { readonly get => new bool3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
        public bool3 zyx { readonly get => new bool3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
        public readonly bool3 zyy => new bool3(z, y, y);
        public readonly bool3 zyz => new bool3(z, y, z);
        public bool3 zyw { readonly get => new bool3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
        public readonly bool3 zzx => new bool3(z, z, x);
        public readonly bool3 zzy => new bool3(z, z, y);
        public readonly bool3 zzz => new bool3(z, z, z);
        public readonly bool3 zzw => new bool3(z, z, w);
        public bool3 zwx { readonly get => new bool3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
        public bool3 zwy { readonly get => new bool3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
        public readonly bool3 zwz => new bool3(z, w, z);
        public readonly bool3 zww => new bool3(z, w, w);
        public readonly bool3 wxx => new bool3(w, x, x);
        public bool3 wxy { readonly get => new bool3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
        public bool3 wxz { readonly get => new bool3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
        public readonly bool3 wxw => new bool3(w, x, w);
        public bool3 wyx { readonly get => new bool3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
        public readonly bool3 wyy => new bool3(w, y, y);
        public bool3 wyz { readonly get => new bool3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
        public readonly bool3 wyw => new bool3(w, y, w);
        public bool3 wzx { readonly get => new bool3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
        public bool3 wzy { readonly get => new bool3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
        public readonly bool3 wzz => new bool3(w, z, z);
        public readonly bool3 wzw => new bool3(w, z, w);
        public readonly bool3 wwx => new bool3(w, w, x);
        public readonly bool3 wwy => new bool3(w, w, y);
        public readonly bool3 wwz => new bool3(w, w, z);
        public readonly bool3 www => new bool3(w, w, w);
        public readonly bool4 xxxx => new bool4(x, x, x, x);
        public readonly bool4 xxxy => new bool4(x, x, x, y);
        public readonly bool4 xxxz => new bool4(x, x, x, z);
        public readonly bool4 xxxw => new bool4(x, x, x, w);
        public readonly bool4 xxyx => new bool4(x, x, y, x);
        public readonly bool4 xxyy => new bool4(x, x, y, y);
        public readonly bool4 xxyz => new bool4(x, x, y, z);
        public readonly bool4 xxyw => new bool4(x, x, y, w);
        public readonly bool4 xxzx => new bool4(x, x, z, x);
        public readonly bool4 xxzy => new bool4(x, x, z, y);
        public readonly bool4 xxzz => new bool4(x, x, z, z);
        public readonly bool4 xxzw => new bool4(x, x, z, w);
        public readonly bool4 xxwx => new bool4(x, x, w, x);
        public readonly bool4 xxwy => new bool4(x, x, w, y);
        public readonly bool4 xxwz => new bool4(x, x, w, z);
        public readonly bool4 xxww => new bool4(x, x, w, w);
        public readonly bool4 xyxx => new bool4(x, y, x, x);
        public readonly bool4 xyxy => new bool4(x, y, x, y);
        public readonly bool4 xyxz => new bool4(x, y, x, z);
        public readonly bool4 xyxw => new bool4(x, y, x, w);
        public readonly bool4 xyyx => new bool4(x, y, y, x);
        public readonly bool4 xyyy => new bool4(x, y, y, y);
        public readonly bool4 xyyz => new bool4(x, y, y, z);
        public readonly bool4 xyyw => new bool4(x, y, y, w);
        public readonly bool4 xyzx => new bool4(x, y, z, x);
        public readonly bool4 xyzy => new bool4(x, y, z, y);
        public readonly bool4 xyzz => new bool4(x, y, z, z);
        public bool4 xyzw { readonly get => new bool4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
        public readonly bool4 xywx => new bool4(x, y, w, x);
        public readonly bool4 xywy => new bool4(x, y, w, y);
        public bool4 xywz { readonly get => new bool4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
        public readonly bool4 xyww => new bool4(x, y, w, w);
        public readonly bool4 xzxx => new bool4(x, z, x, x);
        public readonly bool4 xzxy => new bool4(x, z, x, y);
        public readonly bool4 xzxz => new bool4(x, z, x, z);
        public readonly bool4 xzxw => new bool4(x, z, x, w);
        public readonly bool4 xzyx => new bool4(x, z, y, x);
        public readonly bool4 xzyy => new bool4(x, z, y, y);
        public readonly bool4 xzyz => new bool4(x, z, y, z);
        public bool4 xzyw { readonly get => new bool4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
        public readonly bool4 xzzx => new bool4(x, z, z, x);
        public readonly bool4 xzzy => new bool4(x, z, z, y);
        public readonly bool4 xzzz => new bool4(x, z, z, z);
        public readonly bool4 xzzw => new bool4(x, z, z, w);
        public readonly bool4 xzwx => new bool4(x, z, w, x);
        public bool4 xzwy { readonly get => new bool4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
        public readonly bool4 xzwz => new bool4(x, z, w, z);
        public readonly bool4 xzww => new bool4(x, z, w, w);
        public readonly bool4 xwxx => new bool4(x, w, x, x);
        public readonly bool4 xwxy => new bool4(x, w, x, y);
        public readonly bool4 xwxz => new bool4(x, w, x, z);
        public readonly bool4 xwxw => new bool4(x, w, x, w);
        public readonly bool4 xwyx => new bool4(x, w, y, x);
        public readonly bool4 xwyy => new bool4(x, w, y, y);
        public bool4 xwyz { readonly get => new bool4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
        public readonly bool4 xwyw => new bool4(x, w, y, w);
        public readonly bool4 xwzx => new bool4(x, w, z, x);
        public bool4 xwzy { readonly get => new bool4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
        public readonly bool4 xwzz => new bool4(x, w, z, z);
        public readonly bool4 xwzw => new bool4(x, w, z, w);
        public readonly bool4 xwwx => new bool4(x, w, w, x);
        public readonly bool4 xwwy => new bool4(x, w, w, y);
        public readonly bool4 xwwz => new bool4(x, w, w, z);
        public readonly bool4 xwww => new bool4(x, w, w, w);
        public readonly bool4 yxxx => new bool4(y, x, x, x);
        public readonly bool4 yxxy => new bool4(y, x, x, y);
        public readonly bool4 yxxz => new bool4(y, x, x, z);
        public readonly bool4 yxxw => new bool4(y, x, x, w);
        public readonly bool4 yxyx => new bool4(y, x, y, x);
        public readonly bool4 yxyy => new bool4(y, x, y, y);
        public readonly bool4 yxyz => new bool4(y, x, y, z);
        public readonly bool4 yxyw => new bool4(y, x, y, w);
        public readonly bool4 yxzx => new bool4(y, x, z, x);
        public readonly bool4 yxzy => new bool4(y, x, z, y);
        public readonly bool4 yxzz => new bool4(y, x, z, z);
        public bool4 yxzw { readonly get => new bool4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
        public readonly bool4 yxwx => new bool4(y, x, w, x);
        public readonly bool4 yxwy => new bool4(y, x, w, y);
        public bool4 yxwz { readonly get => new bool4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
        public readonly bool4 yxww => new bool4(y, x, w, w);
        public readonly bool4 yyxx => new bool4(y, y, x, x);
        public readonly bool4 yyxy => new bool4(y, y, x, y);
        public readonly bool4 yyxz => new bool4(y, y, x, z);
        public readonly bool4 yyxw => new bool4(y, y, x, w);
        public readonly bool4 yyyx => new bool4(y, y, y, x);
        public readonly bool4 yyyy => new bool4(y, y, y, y);
        public readonly bool4 yyyz => new bool4(y, y, y, z);
        public readonly bool4 yyyw => new bool4(y, y, y, w);
        public readonly bool4 yyzx => new bool4(y, y, z, x);
        public readonly bool4 yyzy => new bool4(y, y, z, y);
        public readonly bool4 yyzz => new bool4(y, y, z, z);
        public readonly bool4 yyzw => new bool4(y, y, z, w);
        public readonly bool4 yywx => new bool4(y, y, w, x);
        public readonly bool4 yywy => new bool4(y, y, w, y);
        public readonly bool4 yywz => new bool4(y, y, w, z);
        public readonly bool4 yyww => new bool4(y, y, w, w);
        public readonly bool4 yzxx => new bool4(y, z, x, x);
        public readonly bool4 yzxy => new bool4(y, z, x, y);
        public readonly bool4 yzxz => new bool4(y, z, x, z);
        public bool4 yzxw { readonly get => new bool4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
        public readonly bool4 yzyx => new bool4(y, z, y, x);
        public readonly bool4 yzyy => new bool4(y, z, y, y);
        public readonly bool4 yzyz => new bool4(y, z, y, z);
        public readonly bool4 yzyw => new bool4(y, z, y, w);
        public readonly bool4 yzzx => new bool4(y, z, z, x);
        public readonly bool4 yzzy => new bool4(y, z, z, y);
        public readonly bool4 yzzz => new bool4(y, z, z, z);
        public readonly bool4 yzzw => new bool4(y, z, z, w);
        public bool4 yzwx { readonly get => new bool4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
        public readonly bool4 yzwy => new bool4(y, z, w, y);
        public readonly bool4 yzwz => new bool4(y, z, w, z);
        public readonly bool4 yzww => new bool4(y, z, w, w);
        public readonly bool4 ywxx => new bool4(y, w, x, x);
        public readonly bool4 ywxy => new bool4(y, w, x, y);
        public bool4 ywxz { readonly get => new bool4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
        public readonly bool4 ywxw => new bool4(y, w, x, w);
        public readonly bool4 ywyx => new bool4(y, w, y, x);
        public readonly bool4 ywyy => new bool4(y, w, y, y);
        public readonly bool4 ywyz => new bool4(y, w, y, z);
        public readonly bool4 ywyw => new bool4(y, w, y, w);
        public bool4 ywzx { readonly get => new bool4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
        public readonly bool4 ywzy => new bool4(y, w, z, y);
        public readonly bool4 ywzz => new bool4(y, w, z, z);
        public readonly bool4 ywzw => new bool4(y, w, z, w);
        public readonly bool4 ywwx => new bool4(y, w, w, x);
        public readonly bool4 ywwy => new bool4(y, w, w, y);
        public readonly bool4 ywwz => new bool4(y, w, w, z);
        public readonly bool4 ywww => new bool4(y, w, w, w);
        public readonly bool4 zxxx => new bool4(z, x, x, x);
        public readonly bool4 zxxy => new bool4(z, x, x, y);
        public readonly bool4 zxxz => new bool4(z, x, x, z);
        public readonly bool4 zxxw => new bool4(z, x, x, w);
        public readonly bool4 zxyx => new bool4(z, x, y, x);
        public readonly bool4 zxyy => new bool4(z, x, y, y);
        public readonly bool4 zxyz => new bool4(z, x, y, z);
        public bool4 zxyw { readonly get => new bool4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
        public readonly bool4 zxzx => new bool4(z, x, z, x);
        public readonly bool4 zxzy => new bool4(z, x, z, y);
        public readonly bool4 zxzz => new bool4(z, x, z, z);
        public readonly bool4 zxzw => new bool4(z, x, z, w);
        public readonly bool4 zxwx => new bool4(z, x, w, x);
        public bool4 zxwy { readonly get => new bool4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
        public readonly bool4 zxwz => new bool4(z, x, w, z);
        public readonly bool4 zxww => new bool4(z, x, w, w);
        public readonly bool4 zyxx => new bool4(z, y, x, x);
        public readonly bool4 zyxy => new bool4(z, y, x, y);
        public readonly bool4 zyxz => new bool4(z, y, x, z);
        public bool4 zyxw { readonly get => new bool4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
        public readonly bool4 zyyx => new bool4(z, y, y, x);
        public readonly bool4 zyyy => new bool4(z, y, y, y);
        public readonly bool4 zyyz => new bool4(z, y, y, z);
        public readonly bool4 zyyw => new bool4(z, y, y, w);
        public readonly bool4 zyzx => new bool4(z, y, z, x);
        public readonly bool4 zyzy => new bool4(z, y, z, y);
        public readonly bool4 zyzz => new bool4(z, y, z, z);
        public readonly bool4 zyzw => new bool4(z, y, z, w);
        public bool4 zywx { readonly get => new bool4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
        public readonly bool4 zywy => new bool4(z, y, w, y);
        public readonly bool4 zywz => new bool4(z, y, w, z);
        public readonly bool4 zyww => new bool4(z, y, w, w);
        public readonly bool4 zzxx => new bool4(z, z, x, x);
        public readonly bool4 zzxy => new bool4(z, z, x, y);
        public readonly bool4 zzxz => new bool4(z, z, x, z);
        public readonly bool4 zzxw => new bool4(z, z, x, w);
        public readonly bool4 zzyx => new bool4(z, z, y, x);
        public readonly bool4 zzyy => new bool4(z, z, y, y);
        public readonly bool4 zzyz => new bool4(z, z, y, z);
        public readonly bool4 zzyw => new bool4(z, z, y, w);
        public readonly bool4 zzzx => new bool4(z, z, z, x);
        public readonly bool4 zzzy => new bool4(z, z, z, y);
        public readonly bool4 zzzz => new bool4(z, z, z, z);
        public readonly bool4 zzzw => new bool4(z, z, z, w);
        public readonly bool4 zzwx => new bool4(z, z, w, x);
        public readonly bool4 zzwy => new bool4(z, z, w, y);
        public readonly bool4 zzwz => new bool4(z, z, w, z);
        public readonly bool4 zzww => new bool4(z, z, w, w);
        public readonly bool4 zwxx => new bool4(z, w, x, x);
        public bool4 zwxy { readonly get => new bool4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
        public readonly bool4 zwxz => new bool4(z, w, x, z);
        public readonly bool4 zwxw => new bool4(z, w, x, w);
        public bool4 zwyx { readonly get => new bool4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
        public readonly bool4 zwyy => new bool4(z, w, y, y);
        public readonly bool4 zwyz => new bool4(z, w, y, z);
        public readonly bool4 zwyw => new bool4(z, w, y, w);
        public readonly bool4 zwzx => new bool4(z, w, z, x);
        public readonly bool4 zwzy => new bool4(z, w, z, y);
        public readonly bool4 zwzz => new bool4(z, w, z, z);
        public readonly bool4 zwzw => new bool4(z, w, z, w);
        public readonly bool4 zwwx => new bool4(z, w, w, x);
        public readonly bool4 zwwy => new bool4(z, w, w, y);
        public readonly bool4 zwwz => new bool4(z, w, w, z);
        public readonly bool4 zwww => new bool4(z, w, w, w);
        public readonly bool4 wxxx => new bool4(w, x, x, x);
        public readonly bool4 wxxy => new bool4(w, x, x, y);
        public readonly bool4 wxxz => new bool4(w, x, x, z);
        public readonly bool4 wxxw => new bool4(w, x, x, w);
        public readonly bool4 wxyx => new bool4(w, x, y, x);
        public readonly bool4 wxyy => new bool4(w, x, y, y);
        public bool4 wxyz { readonly get => new bool4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
        public readonly bool4 wxyw => new bool4(w, x, y, w);
        public readonly bool4 wxzx => new bool4(w, x, z, x);
        public bool4 wxzy { readonly get => new bool4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
        public readonly bool4 wxzz => new bool4(w, x, z, z);
        public readonly bool4 wxzw => new bool4(w, x, z, w);
        public readonly bool4 wxwx => new bool4(w, x, w, x);
        public readonly bool4 wxwy => new bool4(w, x, w, y);
        public readonly bool4 wxwz => new bool4(w, x, w, z);
        public readonly bool4 wxww => new bool4(w, x, w, w);
        public readonly bool4 wyxx => new bool4(w, y, x, x);
        public readonly bool4 wyxy => new bool4(w, y, x, y);
        public bool4 wyxz { readonly get => new bool4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
        public readonly bool4 wyxw => new bool4(w, y, x, w);
        public readonly bool4 wyyx => new bool4(w, y, y, x);
        public readonly bool4 wyyy => new bool4(w, y, y, y);
        public readonly bool4 wyyz => new bool4(w, y, y, z);
        public readonly bool4 wyyw => new bool4(w, y, y, w);
        public bool4 wyzx { readonly get => new bool4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
        public readonly bool4 wyzy => new bool4(w, y, z, y);
        public readonly bool4 wyzz => new bool4(w, y, z, z);
        public readonly bool4 wyzw => new bool4(w, y, z, w);
        public readonly bool4 wywx => new bool4(w, y, w, x);
        public readonly bool4 wywy => new bool4(w, y, w, y);
        public readonly bool4 wywz => new bool4(w, y, w, z);
        public readonly bool4 wyww => new bool4(w, y, w, w);
        public readonly bool4 wzxx => new bool4(w, z, x, x);
        public bool4 wzxy { readonly get => new bool4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
        public readonly bool4 wzxz => new bool4(w, z, x, z);
        public readonly bool4 wzxw => new bool4(w, z, x, w);
        public bool4 wzyx { readonly get => new bool4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
        public readonly bool4 wzyy => new bool4(w, z, y, y);
        public readonly bool4 wzyz => new bool4(w, z, y, z);
        public readonly bool4 wzyw => new bool4(w, z, y, w);
        public readonly bool4 wzzx => new bool4(w, z, z, x);
        public readonly bool4 wzzy => new bool4(w, z, z, y);
        public readonly bool4 wzzz => new bool4(w, z, z, z);
        public readonly bool4 wzzw => new bool4(w, z, z, w);
        public readonly bool4 wzwx => new bool4(w, z, w, x);
        public readonly bool4 wzwy => new bool4(w, z, w, y);
        public readonly bool4 wzwz => new bool4(w, z, w, z);
        public readonly bool4 wzww => new bool4(w, z, w, w);
        public readonly bool4 wwxx => new bool4(w, w, x, x);
        public readonly bool4 wwxy => new bool4(w, w, x, y);
        public readonly bool4 wwxz => new bool4(w, w, x, z);
        public readonly bool4 wwxw => new bool4(w, w, x, w);
        public readonly bool4 wwyx => new bool4(w, w, y, x);
        public readonly bool4 wwyy => new bool4(w, w, y, y);
        public readonly bool4 wwyz => new bool4(w, w, y, z);
        public readonly bool4 wwyw => new bool4(w, w, y, w);
        public readonly bool4 wwzx => new bool4(w, w, z, x);
        public readonly bool4 wwzy => new bool4(w, w, z, y);
        public readonly bool4 wwzz => new bool4(w, w, z, z);
        public readonly bool4 wwzw => new bool4(w, w, z, w);
        public readonly bool4 wwwx => new bool4(w, w, w, x);
        public readonly bool4 wwwy => new bool4(w, w, w, y);
        public readonly bool4 wwwz => new bool4(w, w, w, z);
        public readonly bool4 wwww => new bool4(w, w, w, w);
        public readonly bool Equals(bool4 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y) && z.Equals(rhs.z) && w.Equals(rhs.w);
        public override readonly bool Equals(object o) => o is bool4 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y, z, w);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "bool4({0}, {1}, {2}, {3})", x, y, z, w);
        public readonly string ToString(string format, IFormatProvider formatProvider) => ToString();
    }
}
