// <auto-generated>
// Generated by the port's math shim generator (first-party). Behavior-level re-implementation
// of the Unity.Mathematics public API surface the game compiles against; not vendored source.
// </auto-generated>
using System;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace Unity.Mathematics
{
    [Serializable]
    public partial struct float2 : IEquatable<float2>, IFormattable
    {
        public float x;
        public float y;
        public static readonly float2 zero;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float2(float x, float y) { this.x = x; this.y = y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float2(float2 xy) { this.x = xy.x; this.y = xy.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float2(float v) { x = v; y = v; }
        public float2(double v) { x = (float)(v); y = (float)(v); }
        public float2(double2 v) { x = (float)(v.x); y = (float)(v.y); }
        public float2(int v) { x = (float)(v); y = (float)(v); }
        public float2(int2 v) { x = (float)(v.x); y = (float)(v.y); }
        public float2(uint v) { x = (float)(v); y = (float)(v); }
        public float2(uint2 v) { x = (float)(v.x); y = (float)(v.y); }
        public float2(bool v) { x = (v ? 1f : 0f); y = (v ? 1f : 0f); }
        public float2(bool2 v) { x = (v.x ? 1f : 0f); y = (v.y ? 1f : 0f); }
        public static implicit operator float2(float v) => new float2(v);
        public static explicit operator float2(double v) => new float2(v);
        public static explicit operator float2(double2 v) => new float2(v);
        public static implicit operator float2(int v) => new float2(v);
        public static implicit operator float2(int2 v) => new float2(v);
        public static implicit operator float2(uint v) => new float2(v);
        public static implicit operator float2(uint2 v) => new float2(v);
        public static explicit operator float2(bool v) => new float2(v);
        public static explicit operator float2(bool2 v) => new float2(v);
        public static float2 operator +(float2 a, float2 b) => new float2(a.x + b.x, a.y + b.y);
        public static float2 operator +(float2 a, float b) => new float2(a.x + b, a.y + b);
        public static float2 operator +(float a, float2 b) => new float2(a + b.x, a + b.y);
        public static float2 operator -(float2 a, float2 b) => new float2(a.x - b.x, a.y - b.y);
        public static float2 operator -(float2 a, float b) => new float2(a.x - b, a.y - b);
        public static float2 operator -(float a, float2 b) => new float2(a - b.x, a - b.y);
        public static float2 operator *(float2 a, float2 b) => new float2(a.x * b.x, a.y * b.y);
        public static float2 operator *(float2 a, float b) => new float2(a.x * b, a.y * b);
        public static float2 operator *(float a, float2 b) => new float2(a * b.x, a * b.y);
        public static float2 operator /(float2 a, float2 b) => new float2(a.x / b.x, a.y / b.y);
        public static float2 operator /(float2 a, float b) => new float2(a.x / b, a.y / b);
        public static float2 operator /(float a, float2 b) => new float2(a / b.x, a / b.y);
        public static float2 operator %(float2 a, float2 b) => new float2(a.x % b.x, a.y % b.y);
        public static float2 operator %(float2 a, float b) => new float2(a.x % b, a.y % b);
        public static float2 operator %(float a, float2 b) => new float2(a % b.x, a % b.y);
        public static float2 operator ++(float2 v) => new float2(v.x + 1f, v.y + 1f);
        public static float2 operator --(float2 v) => new float2(v.x - 1f, v.y - 1f);
        public static float2 operator +(float2 v) => v;
        public static float2 operator -(float2 v) => new float2(-v.x, -v.y);
        public static bool2 operator <(float2 a, float2 b) => new bool2(a.x < b.x, a.y < b.y);
        public static bool2 operator <(float2 a, float b) => new bool2(a.x < b, a.y < b);
        public static bool2 operator <(float a, float2 b) => new bool2(a < b.x, a < b.y);
        public static bool2 operator <=(float2 a, float2 b) => new bool2(a.x <= b.x, a.y <= b.y);
        public static bool2 operator <=(float2 a, float b) => new bool2(a.x <= b, a.y <= b);
        public static bool2 operator <=(float a, float2 b) => new bool2(a <= b.x, a <= b.y);
        public static bool2 operator >(float2 a, float2 b) => new bool2(a.x > b.x, a.y > b.y);
        public static bool2 operator >(float2 a, float b) => new bool2(a.x > b, a.y > b);
        public static bool2 operator >(float a, float2 b) => new bool2(a > b.x, a > b.y);
        public static bool2 operator >=(float2 a, float2 b) => new bool2(a.x >= b.x, a.y >= b.y);
        public static bool2 operator >=(float2 a, float b) => new bool2(a.x >= b, a.y >= b);
        public static bool2 operator >=(float a, float2 b) => new bool2(a >= b.x, a >= b.y);
        public static bool2 operator ==(float2 a, float2 b) => new bool2(a.x == b.x, a.y == b.y);
        public static bool2 operator ==(float2 a, float b) => new bool2(a.x == b, a.y == b);
        public static bool2 operator ==(float a, float2 b) => new bool2(a == b.x, a == b.y);
        public static bool2 operator !=(float2 a, float2 b) => new bool2(a.x != b.x, a.y != b.y);
        public static bool2 operator !=(float2 a, float b) => new bool2(a.x != b, a.y != b);
        public static bool2 operator !=(float a, float2 b) => new bool2(a != b.x, a != b.y);
        public float this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly float2 xx => new float2(x, x);
        public float2 xy { readonly get => new float2(x, y); set { x = value.x; y = value.y; } }
        public float2 yx { readonly get => new float2(y, x); set { y = value.x; x = value.y; } }
        public readonly float2 yy => new float2(y, y);
        public readonly float3 xxx => new float3(x, x, x);
        public readonly float3 xxy => new float3(x, x, y);
        public readonly float3 xyx => new float3(x, y, x);
        public readonly float3 xyy => new float3(x, y, y);
        public readonly float3 yxx => new float3(y, x, x);
        public readonly float3 yxy => new float3(y, x, y);
        public readonly float3 yyx => new float3(y, y, x);
        public readonly float3 yyy => new float3(y, y, y);
        public readonly float4 xxxx => new float4(x, x, x, x);
        public readonly float4 xxxy => new float4(x, x, x, y);
        public readonly float4 xxyx => new float4(x, x, y, x);
        public readonly float4 xxyy => new float4(x, x, y, y);
        public readonly float4 xyxx => new float4(x, y, x, x);
        public readonly float4 xyxy => new float4(x, y, x, y);
        public readonly float4 xyyx => new float4(x, y, y, x);
        public readonly float4 xyyy => new float4(x, y, y, y);
        public readonly float4 yxxx => new float4(y, x, x, x);
        public readonly float4 yxxy => new float4(y, x, x, y);
        public readonly float4 yxyx => new float4(y, x, y, x);
        public readonly float4 yxyy => new float4(y, x, y, y);
        public readonly float4 yyxx => new float4(y, y, x, x);
        public readonly float4 yyxy => new float4(y, y, x, y);
        public readonly float4 yyyx => new float4(y, y, y, x);
        public readonly float4 yyyy => new float4(y, y, y, y);
        public readonly bool Equals(float2 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y);
        public override readonly bool Equals(object o) => o is float2 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "float2({0}f, {1}f)", x, y);
        public readonly string ToString(string format, IFormatProvider formatProvider) => string.Format("float2({0}f, {1}f)", x.ToString(format, formatProvider), y.ToString(format, formatProvider));
    }

    [Serializable]
    public partial struct float3 : IEquatable<float3>, IFormattable
    {
        public float x;
        public float y;
        public float z;
        public static readonly float3 zero;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float3(float x, float y, float z) { this.x = x; this.y = y; this.z = z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float3(float x, float2 yz) { this.x = x; this.y = yz.x; this.z = yz.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float3(float2 xy, float z) { this.x = xy.x; this.y = xy.y; this.z = z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float3(float3 xyz) { this.x = xyz.x; this.y = xyz.y; this.z = xyz.z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float3(float v) { x = v; y = v; z = v; }
        public float3(double v) { x = (float)(v); y = (float)(v); z = (float)(v); }
        public float3(double3 v) { x = (float)(v.x); y = (float)(v.y); z = (float)(v.z); }
        public float3(int v) { x = (float)(v); y = (float)(v); z = (float)(v); }
        public float3(int3 v) { x = (float)(v.x); y = (float)(v.y); z = (float)(v.z); }
        public float3(uint v) { x = (float)(v); y = (float)(v); z = (float)(v); }
        public float3(uint3 v) { x = (float)(v.x); y = (float)(v.y); z = (float)(v.z); }
        public float3(bool v) { x = (v ? 1f : 0f); y = (v ? 1f : 0f); z = (v ? 1f : 0f); }
        public float3(bool3 v) { x = (v.x ? 1f : 0f); y = (v.y ? 1f : 0f); z = (v.z ? 1f : 0f); }
        public static implicit operator float3(float v) => new float3(v);
        public static explicit operator float3(double v) => new float3(v);
        public static explicit operator float3(double3 v) => new float3(v);
        public static implicit operator float3(int v) => new float3(v);
        public static implicit operator float3(int3 v) => new float3(v);
        public static implicit operator float3(uint v) => new float3(v);
        public static implicit operator float3(uint3 v) => new float3(v);
        public static explicit operator float3(bool v) => new float3(v);
        public static explicit operator float3(bool3 v) => new float3(v);
        public static float3 operator +(float3 a, float3 b) => new float3(a.x + b.x, a.y + b.y, a.z + b.z);
        public static float3 operator +(float3 a, float b) => new float3(a.x + b, a.y + b, a.z + b);
        public static float3 operator +(float a, float3 b) => new float3(a + b.x, a + b.y, a + b.z);
        public static float3 operator -(float3 a, float3 b) => new float3(a.x - b.x, a.y - b.y, a.z - b.z);
        public static float3 operator -(float3 a, float b) => new float3(a.x - b, a.y - b, a.z - b);
        public static float3 operator -(float a, float3 b) => new float3(a - b.x, a - b.y, a - b.z);
        public static float3 operator *(float3 a, float3 b) => new float3(a.x * b.x, a.y * b.y, a.z * b.z);
        public static float3 operator *(float3 a, float b) => new float3(a.x * b, a.y * b, a.z * b);
        public static float3 operator *(float a, float3 b) => new float3(a * b.x, a * b.y, a * b.z);
        public static float3 operator /(float3 a, float3 b) => new float3(a.x / b.x, a.y / b.y, a.z / b.z);
        public static float3 operator /(float3 a, float b) => new float3(a.x / b, a.y / b, a.z / b);
        public static float3 operator /(float a, float3 b) => new float3(a / b.x, a / b.y, a / b.z);
        public static float3 operator %(float3 a, float3 b) => new float3(a.x % b.x, a.y % b.y, a.z % b.z);
        public static float3 operator %(float3 a, float b) => new float3(a.x % b, a.y % b, a.z % b);
        public static float3 operator %(float a, float3 b) => new float3(a % b.x, a % b.y, a % b.z);
        public static float3 operator ++(float3 v) => new float3(v.x + 1f, v.y + 1f, v.z + 1f);
        public static float3 operator --(float3 v) => new float3(v.x - 1f, v.y - 1f, v.z - 1f);
        public static float3 operator +(float3 v) => v;
        public static float3 operator -(float3 v) => new float3(-v.x, -v.y, -v.z);
        public static bool3 operator <(float3 a, float3 b) => new bool3(a.x < b.x, a.y < b.y, a.z < b.z);
        public static bool3 operator <(float3 a, float b) => new bool3(a.x < b, a.y < b, a.z < b);
        public static bool3 operator <(float a, float3 b) => new bool3(a < b.x, a < b.y, a < b.z);
        public static bool3 operator <=(float3 a, float3 b) => new bool3(a.x <= b.x, a.y <= b.y, a.z <= b.z);
        public static bool3 operator <=(float3 a, float b) => new bool3(a.x <= b, a.y <= b, a.z <= b);
        public static bool3 operator <=(float a, float3 b) => new bool3(a <= b.x, a <= b.y, a <= b.z);
        public static bool3 operator >(float3 a, float3 b) => new bool3(a.x > b.x, a.y > b.y, a.z > b.z);
        public static bool3 operator >(float3 a, float b) => new bool3(a.x > b, a.y > b, a.z > b);
        public static bool3 operator >(float a, float3 b) => new bool3(a > b.x, a > b.y, a > b.z);
        public static bool3 operator >=(float3 a, float3 b) => new bool3(a.x >= b.x, a.y >= b.y, a.z >= b.z);
        public static bool3 operator >=(float3 a, float b) => new bool3(a.x >= b, a.y >= b, a.z >= b);
        public static bool3 operator >=(float a, float3 b) => new bool3(a >= b.x, a >= b.y, a >= b.z);
        public static bool3 operator ==(float3 a, float3 b) => new bool3(a.x == b.x, a.y == b.y, a.z == b.z);
        public static bool3 operator ==(float3 a, float b) => new bool3(a.x == b, a.y == b, a.z == b);
        public static bool3 operator ==(float a, float3 b) => new bool3(a == b.x, a == b.y, a == b.z);
        public static bool3 operator !=(float3 a, float3 b) => new bool3(a.x != b.x, a.y != b.y, a.z != b.z);
        public static bool3 operator !=(float3 a, float b) => new bool3(a.x != b, a.y != b, a.z != b);
        public static bool3 operator !=(float a, float3 b) => new bool3(a != b.x, a != b.y, a != b.z);
        public float this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; case 2: return z; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly float2 xx => new float2(x, x);
        public float2 xy { readonly get => new float2(x, y); set { x = value.x; y = value.y; } }
        public float2 xz { readonly get => new float2(x, z); set { x = value.x; z = value.y; } }
        public float2 yx { readonly get => new float2(y, x); set { y = value.x; x = value.y; } }
        public readonly float2 yy => new float2(y, y);
        public float2 yz { readonly get => new float2(y, z); set { y = value.x; z = value.y; } }
        public float2 zx { readonly get => new float2(z, x); set { z = value.x; x = value.y; } }
        public float2 zy { readonly get => new float2(z, y); set { z = value.x; y = value.y; } }
        public readonly float2 zz => new float2(z, z);
        public readonly float3 xxx => new float3(x, x, x);
        public readonly float3 xxy => new float3(x, x, y);
        public readonly float3 xxz => new float3(x, x, z);
        public readonly float3 xyx => new float3(x, y, x);
        public readonly float3 xyy => new float3(x, y, y);
        public float3 xyz { readonly get => new float3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
        public readonly float3 xzx => new float3(x, z, x);
        public float3 xzy { readonly get => new float3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
        public readonly float3 xzz => new float3(x, z, z);
        public readonly float3 yxx => new float3(y, x, x);
        public readonly float3 yxy => new float3(y, x, y);
        public float3 yxz { readonly get => new float3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
        public readonly float3 yyx => new float3(y, y, x);
        public readonly float3 yyy => new float3(y, y, y);
        public readonly float3 yyz => new float3(y, y, z);
        public float3 yzx { readonly get => new float3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
        public readonly float3 yzy => new float3(y, z, y);
        public readonly float3 yzz => new float3(y, z, z);
        public readonly float3 zxx => new float3(z, x, x);
        public float3 zxy { readonly get => new float3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
        public readonly float3 zxz => new float3(z, x, z);
        public float3 zyx { readonly get => new float3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
        public readonly float3 zyy => new float3(z, y, y);
        public readonly float3 zyz => new float3(z, y, z);
        public readonly float3 zzx => new float3(z, z, x);
        public readonly float3 zzy => new float3(z, z, y);
        public readonly float3 zzz => new float3(z, z, z);
        public readonly float4 xxxx => new float4(x, x, x, x);
        public readonly float4 xxxy => new float4(x, x, x, y);
        public readonly float4 xxxz => new float4(x, x, x, z);
        public readonly float4 xxyx => new float4(x, x, y, x);
        public readonly float4 xxyy => new float4(x, x, y, y);
        public readonly float4 xxyz => new float4(x, x, y, z);
        public readonly float4 xxzx => new float4(x, x, z, x);
        public readonly float4 xxzy => new float4(x, x, z, y);
        public readonly float4 xxzz => new float4(x, x, z, z);
        public readonly float4 xyxx => new float4(x, y, x, x);
        public readonly float4 xyxy => new float4(x, y, x, y);
        public readonly float4 xyxz => new float4(x, y, x, z);
        public readonly float4 xyyx => new float4(x, y, y, x);
        public readonly float4 xyyy => new float4(x, y, y, y);
        public readonly float4 xyyz => new float4(x, y, y, z);
        public readonly float4 xyzx => new float4(x, y, z, x);
        public readonly float4 xyzy => new float4(x, y, z, y);
        public readonly float4 xyzz => new float4(x, y, z, z);
        public readonly float4 xzxx => new float4(x, z, x, x);
        public readonly float4 xzxy => new float4(x, z, x, y);
        public readonly float4 xzxz => new float4(x, z, x, z);
        public readonly float4 xzyx => new float4(x, z, y, x);
        public readonly float4 xzyy => new float4(x, z, y, y);
        public readonly float4 xzyz => new float4(x, z, y, z);
        public readonly float4 xzzx => new float4(x, z, z, x);
        public readonly float4 xzzy => new float4(x, z, z, y);
        public readonly float4 xzzz => new float4(x, z, z, z);
        public readonly float4 yxxx => new float4(y, x, x, x);
        public readonly float4 yxxy => new float4(y, x, x, y);
        public readonly float4 yxxz => new float4(y, x, x, z);
        public readonly float4 yxyx => new float4(y, x, y, x);
        public readonly float4 yxyy => new float4(y, x, y, y);
        public readonly float4 yxyz => new float4(y, x, y, z);
        public readonly float4 yxzx => new float4(y, x, z, x);
        public readonly float4 yxzy => new float4(y, x, z, y);
        public readonly float4 yxzz => new float4(y, x, z, z);
        public readonly float4 yyxx => new float4(y, y, x, x);
        public readonly float4 yyxy => new float4(y, y, x, y);
        public readonly float4 yyxz => new float4(y, y, x, z);
        public readonly float4 yyyx => new float4(y, y, y, x);
        public readonly float4 yyyy => new float4(y, y, y, y);
        public readonly float4 yyyz => new float4(y, y, y, z);
        public readonly float4 yyzx => new float4(y, y, z, x);
        public readonly float4 yyzy => new float4(y, y, z, y);
        public readonly float4 yyzz => new float4(y, y, z, z);
        public readonly float4 yzxx => new float4(y, z, x, x);
        public readonly float4 yzxy => new float4(y, z, x, y);
        public readonly float4 yzxz => new float4(y, z, x, z);
        public readonly float4 yzyx => new float4(y, z, y, x);
        public readonly float4 yzyy => new float4(y, z, y, y);
        public readonly float4 yzyz => new float4(y, z, y, z);
        public readonly float4 yzzx => new float4(y, z, z, x);
        public readonly float4 yzzy => new float4(y, z, z, y);
        public readonly float4 yzzz => new float4(y, z, z, z);
        public readonly float4 zxxx => new float4(z, x, x, x);
        public readonly float4 zxxy => new float4(z, x, x, y);
        public readonly float4 zxxz => new float4(z, x, x, z);
        public readonly float4 zxyx => new float4(z, x, y, x);
        public readonly float4 zxyy => new float4(z, x, y, y);
        public readonly float4 zxyz => new float4(z, x, y, z);
        public readonly float4 zxzx => new float4(z, x, z, x);
        public readonly float4 zxzy => new float4(z, x, z, y);
        public readonly float4 zxzz => new float4(z, x, z, z);
        public readonly float4 zyxx => new float4(z, y, x, x);
        public readonly float4 zyxy => new float4(z, y, x, y);
        public readonly float4 zyxz => new float4(z, y, x, z);
        public readonly float4 zyyx => new float4(z, y, y, x);
        public readonly float4 zyyy => new float4(z, y, y, y);
        public readonly float4 zyyz => new float4(z, y, y, z);
        public readonly float4 zyzx => new float4(z, y, z, x);
        public readonly float4 zyzy => new float4(z, y, z, y);
        public readonly float4 zyzz => new float4(z, y, z, z);
        public readonly float4 zzxx => new float4(z, z, x, x);
        public readonly float4 zzxy => new float4(z, z, x, y);
        public readonly float4 zzxz => new float4(z, z, x, z);
        public readonly float4 zzyx => new float4(z, z, y, x);
        public readonly float4 zzyy => new float4(z, z, y, y);
        public readonly float4 zzyz => new float4(z, z, y, z);
        public readonly float4 zzzx => new float4(z, z, z, x);
        public readonly float4 zzzy => new float4(z, z, z, y);
        public readonly float4 zzzz => new float4(z, z, z, z);
        public readonly bool Equals(float3 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y) && z.Equals(rhs.z);
        public override readonly bool Equals(object o) => o is float3 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y, z);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "float3({0}f, {1}f, {2}f)", x, y, z);
        public readonly string ToString(string format, IFormatProvider formatProvider) => string.Format("float3({0}f, {1}f, {2}f)", x.ToString(format, formatProvider), y.ToString(format, formatProvider), z.ToString(format, formatProvider));
    }

    [Serializable]
    public partial struct float4 : IEquatable<float4>, IFormattable
    {
        public float x;
        public float y;
        public float z;
        public float w;
        public static readonly float4 zero;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float4(float x, float y, float z, float w) { this.x = x; this.y = y; this.z = z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float4(float x, float y, float2 zw) { this.x = x; this.y = y; this.z = zw.x; this.w = zw.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float4(float x, float2 yz, float w) { this.x = x; this.y = yz.x; this.z = yz.y; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float4(float x, float3 yzw) { this.x = x; this.y = yzw.x; this.z = yzw.y; this.w = yzw.z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float4(float2 xy, float z, float w) { this.x = xy.x; this.y = xy.y; this.z = z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float4(float2 xy, float2 zw) { this.x = xy.x; this.y = xy.y; this.z = zw.x; this.w = zw.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float4(float3 xyz, float w) { this.x = xyz.x; this.y = xyz.y; this.z = xyz.z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float4(float4 xyzw) { this.x = xyzw.x; this.y = xyzw.y; this.z = xyzw.z; this.w = xyzw.w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public float4(float v) { x = v; y = v; z = v; w = v; }
        public float4(double v) { x = (float)(v); y = (float)(v); z = (float)(v); w = (float)(v); }
        public float4(double4 v) { x = (float)(v.x); y = (float)(v.y); z = (float)(v.z); w = (float)(v.w); }
        public float4(int v) { x = (float)(v); y = (float)(v); z = (float)(v); w = (float)(v); }
        public float4(int4 v) { x = (float)(v.x); y = (float)(v.y); z = (float)(v.z); w = (float)(v.w); }
        public float4(uint v) { x = (float)(v); y = (float)(v); z = (float)(v); w = (float)(v); }
        public float4(uint4 v) { x = (float)(v.x); y = (float)(v.y); z = (float)(v.z); w = (float)(v.w); }
        public float4(bool v) { x = (v ? 1f : 0f); y = (v ? 1f : 0f); z = (v ? 1f : 0f); w = (v ? 1f : 0f); }
        public float4(bool4 v) { x = (v.x ? 1f : 0f); y = (v.y ? 1f : 0f); z = (v.z ? 1f : 0f); w = (v.w ? 1f : 0f); }
        public static implicit operator float4(float v) => new float4(v);
        public static explicit operator float4(double v) => new float4(v);
        public static explicit operator float4(double4 v) => new float4(v);
        public static implicit operator float4(int v) => new float4(v);
        public static implicit operator float4(int4 v) => new float4(v);
        public static implicit operator float4(uint v) => new float4(v);
        public static implicit operator float4(uint4 v) => new float4(v);
        public static explicit operator float4(bool v) => new float4(v);
        public static explicit operator float4(bool4 v) => new float4(v);
        public static float4 operator +(float4 a, float4 b) => new float4(a.x + b.x, a.y + b.y, a.z + b.z, a.w + b.w);
        public static float4 operator +(float4 a, float b) => new float4(a.x + b, a.y + b, a.z + b, a.w + b);
        public static float4 operator +(float a, float4 b) => new float4(a + b.x, a + b.y, a + b.z, a + b.w);
        public static float4 operator -(float4 a, float4 b) => new float4(a.x - b.x, a.y - b.y, a.z - b.z, a.w - b.w);
        public static float4 operator -(float4 a, float b) => new float4(a.x - b, a.y - b, a.z - b, a.w - b);
        public static float4 operator -(float a, float4 b) => new float4(a - b.x, a - b.y, a - b.z, a - b.w);
        public static float4 operator *(float4 a, float4 b) => new float4(a.x * b.x, a.y * b.y, a.z * b.z, a.w * b.w);
        public static float4 operator *(float4 a, float b) => new float4(a.x * b, a.y * b, a.z * b, a.w * b);
        public static float4 operator *(float a, float4 b) => new float4(a * b.x, a * b.y, a * b.z, a * b.w);
        public static float4 operator /(float4 a, float4 b) => new float4(a.x / b.x, a.y / b.y, a.z / b.z, a.w / b.w);
        public static float4 operator /(float4 a, float b) => new float4(a.x / b, a.y / b, a.z / b, a.w / b);
        public static float4 operator /(float a, float4 b) => new float4(a / b.x, a / b.y, a / b.z, a / b.w);
        public static float4 operator %(float4 a, float4 b) => new float4(a.x % b.x, a.y % b.y, a.z % b.z, a.w % b.w);
        public static float4 operator %(float4 a, float b) => new float4(a.x % b, a.y % b, a.z % b, a.w % b);
        public static float4 operator %(float a, float4 b) => new float4(a % b.x, a % b.y, a % b.z, a % b.w);
        public static float4 operator ++(float4 v) => new float4(v.x + 1f, v.y + 1f, v.z + 1f, v.w + 1f);
        public static float4 operator --(float4 v) => new float4(v.x - 1f, v.y - 1f, v.z - 1f, v.w - 1f);
        public static float4 operator +(float4 v) => v;
        public static float4 operator -(float4 v) => new float4(-v.x, -v.y, -v.z, -v.w);
        public static bool4 operator <(float4 a, float4 b) => new bool4(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
        public static bool4 operator <(float4 a, float b) => new bool4(a.x < b, a.y < b, a.z < b, a.w < b);
        public static bool4 operator <(float a, float4 b) => new bool4(a < b.x, a < b.y, a < b.z, a < b.w);
        public static bool4 operator <=(float4 a, float4 b) => new bool4(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
        public static bool4 operator <=(float4 a, float b) => new bool4(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
        public static bool4 operator <=(float a, float4 b) => new bool4(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
        public static bool4 operator >(float4 a, float4 b) => new bool4(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
        public static bool4 operator >(float4 a, float b) => new bool4(a.x > b, a.y > b, a.z > b, a.w > b);
        public static bool4 operator >(float a, float4 b) => new bool4(a > b.x, a > b.y, a > b.z, a > b.w);
        public static bool4 operator >=(float4 a, float4 b) => new bool4(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
        public static bool4 operator >=(float4 a, float b) => new bool4(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
        public static bool4 operator >=(float a, float4 b) => new bool4(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
        public static bool4 operator ==(float4 a, float4 b) => new bool4(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
        public static bool4 operator ==(float4 a, float b) => new bool4(a.x == b, a.y == b, a.z == b, a.w == b);
        public static bool4 operator ==(float a, float4 b) => new bool4(a == b.x, a == b.y, a == b.z, a == b.w);
        public static bool4 operator !=(float4 a, float4 b) => new bool4(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
        public static bool4 operator !=(float4 a, float b) => new bool4(a.x != b, a.y != b, a.z != b, a.w != b);
        public static bool4 operator !=(float a, float4 b) => new bool4(a != b.x, a != b.y, a != b.z, a != b.w);
        public float this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; case 2: return z; case 3: return w; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; case 3: w = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly float2 xx => new float2(x, x);
        public float2 xy { readonly get => new float2(x, y); set { x = value.x; y = value.y; } }
        public float2 xz { readonly get => new float2(x, z); set { x = value.x; z = value.y; } }
        public float2 xw { readonly get => new float2(x, w); set { x = value.x; w = value.y; } }
        public float2 yx { readonly get => new float2(y, x); set { y = value.x; x = value.y; } }
        public readonly float2 yy => new float2(y, y);
        public float2 yz { readonly get => new float2(y, z); set { y = value.x; z = value.y; } }
        public float2 yw { readonly get => new float2(y, w); set { y = value.x; w = value.y; } }
        public float2 zx { readonly get => new float2(z, x); set { z = value.x; x = value.y; } }
        public float2 zy { readonly get => new float2(z, y); set { z = value.x; y = value.y; } }
        public readonly float2 zz => new float2(z, z);
        public float2 zw { readonly get => new float2(z, w); set { z = value.x; w = value.y; } }
        public float2 wx { readonly get => new float2(w, x); set { w = value.x; x = value.y; } }
        public float2 wy { readonly get => new float2(w, y); set { w = value.x; y = value.y; } }
        public float2 wz { readonly get => new float2(w, z); set { w = value.x; z = value.y; } }
        public readonly float2 ww => new float2(w, w);
        public readonly float3 xxx => new float3(x, x, x);
        public readonly float3 xxy => new float3(x, x, y);
        public readonly float3 xxz => new float3(x, x, z);
        public readonly float3 xxw => new float3(x, x, w);
        public readonly float3 xyx => new float3(x, y, x);
        public readonly float3 xyy => new float3(x, y, y);
        public float3 xyz { readonly get => new float3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
        public float3 xyw { readonly get => new float3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
        public readonly float3 xzx => new float3(x, z, x);
        public float3 xzy { readonly get => new float3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
        public readonly float3 xzz => new float3(x, z, z);
        public float3 xzw { readonly get => new float3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
        public readonly float3 xwx => new float3(x, w, x);
        public float3 xwy { readonly get => new float3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
        public float3 xwz { readonly get => new float3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
        public readonly float3 xww => new float3(x, w, w);
        public readonly float3 yxx => new float3(y, x, x);
        public readonly float3 yxy => new float3(y, x, y);
        public float3 yxz { readonly get => new float3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
        public float3 yxw { readonly get => new float3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
        public readonly float3 yyx => new float3(y, y, x);
        public readonly float3 yyy => new float3(y, y, y);
        public readonly float3 yyz => new float3(y, y, z);
        public readonly float3 yyw => new float3(y, y, w);
        public float3 yzx { readonly get => new float3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
        public readonly float3 yzy => new float3(y, z, y);
        public readonly float3 yzz => new float3(y, z, z);
        public float3 yzw { readonly get => new float3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
        public float3 ywx { readonly get => new float3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
        public readonly float3 ywy => new float3(y, w, y);
        public float3 ywz { readonly get => new float3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
        public readonly float3 yww => new float3(y, w, w);
        public readonly float3 zxx => new float3(z, x, x);
        public float3 zxy { readonly get => new float3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
        public readonly float3 zxz => new float3(z, x, z);
        public float3 zxw { readonly get => new float3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
        public float3 zyx { readonly get => new float3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
        public readonly float3 zyy => new float3(z, y, y);
        public readonly float3 zyz => new float3(z, y, z);
        public float3 zyw { readonly get => new float3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
        public readonly float3 zzx => new float3(z, z, x);
        public readonly float3 zzy => new float3(z, z, y);
        public readonly float3 zzz => new float3(z, z, z);
        public readonly float3 zzw => new float3(z, z, w);
        public float3 zwx { readonly get => new float3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
        public float3 zwy { readonly get => new float3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
        public readonly float3 zwz => new float3(z, w, z);
        public readonly float3 zww => new float3(z, w, w);
        public readonly float3 wxx => new float3(w, x, x);
        public float3 wxy { readonly get => new float3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
        public float3 wxz { readonly get => new float3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
        public readonly float3 wxw => new float3(w, x, w);
        public float3 wyx { readonly get => new float3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
        public readonly float3 wyy => new float3(w, y, y);
        public float3 wyz { readonly get => new float3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
        public readonly float3 wyw => new float3(w, y, w);
        public float3 wzx { readonly get => new float3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
        public float3 wzy { readonly get => new float3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
        public readonly float3 wzz => new float3(w, z, z);
        public readonly float3 wzw => new float3(w, z, w);
        public readonly float3 wwx => new float3(w, w, x);
        public readonly float3 wwy => new float3(w, w, y);
        public readonly float3 wwz => new float3(w, w, z);
        public readonly float3 www => new float3(w, w, w);
        public readonly float4 xxxx => new float4(x, x, x, x);
        public readonly float4 xxxy => new float4(x, x, x, y);
        public readonly float4 xxxz => new float4(x, x, x, z);
        public readonly float4 xxxw => new float4(x, x, x, w);
        public readonly float4 xxyx => new float4(x, x, y, x);
        public readonly float4 xxyy => new float4(x, x, y, y);
        public readonly float4 xxyz => new float4(x, x, y, z);
        public readonly float4 xxyw => new float4(x, x, y, w);
        public readonly float4 xxzx => new float4(x, x, z, x);
        public readonly float4 xxzy => new float4(x, x, z, y);
        public readonly float4 xxzz => new float4(x, x, z, z);
        public readonly float4 xxzw => new float4(x, x, z, w);
        public readonly float4 xxwx => new float4(x, x, w, x);
        public readonly float4 xxwy => new float4(x, x, w, y);
        public readonly float4 xxwz => new float4(x, x, w, z);
        public readonly float4 xxww => new float4(x, x, w, w);
        public readonly float4 xyxx => new float4(x, y, x, x);
        public readonly float4 xyxy => new float4(x, y, x, y);
        public readonly float4 xyxz => new float4(x, y, x, z);
        public readonly float4 xyxw => new float4(x, y, x, w);
        public readonly float4 xyyx => new float4(x, y, y, x);
        public readonly float4 xyyy => new float4(x, y, y, y);
        public readonly float4 xyyz => new float4(x, y, y, z);
        public readonly float4 xyyw => new float4(x, y, y, w);
        public readonly float4 xyzx => new float4(x, y, z, x);
        public readonly float4 xyzy => new float4(x, y, z, y);
        public readonly float4 xyzz => new float4(x, y, z, z);
        public float4 xyzw { readonly get => new float4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
        public readonly float4 xywx => new float4(x, y, w, x);
        public readonly float4 xywy => new float4(x, y, w, y);
        public float4 xywz { readonly get => new float4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
        public readonly float4 xyww => new float4(x, y, w, w);
        public readonly float4 xzxx => new float4(x, z, x, x);
        public readonly float4 xzxy => new float4(x, z, x, y);
        public readonly float4 xzxz => new float4(x, z, x, z);
        public readonly float4 xzxw => new float4(x, z, x, w);
        public readonly float4 xzyx => new float4(x, z, y, x);
        public readonly float4 xzyy => new float4(x, z, y, y);
        public readonly float4 xzyz => new float4(x, z, y, z);
        public float4 xzyw { readonly get => new float4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
        public readonly float4 xzzx => new float4(x, z, z, x);
        public readonly float4 xzzy => new float4(x, z, z, y);
        public readonly float4 xzzz => new float4(x, z, z, z);
        public readonly float4 xzzw => new float4(x, z, z, w);
        public readonly float4 xzwx => new float4(x, z, w, x);
        public float4 xzwy { readonly get => new float4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
        public readonly float4 xzwz => new float4(x, z, w, z);
        public readonly float4 xzww => new float4(x, z, w, w);
        public readonly float4 xwxx => new float4(x, w, x, x);
        public readonly float4 xwxy => new float4(x, w, x, y);
        public readonly float4 xwxz => new float4(x, w, x, z);
        public readonly float4 xwxw => new float4(x, w, x, w);
        public readonly float4 xwyx => new float4(x, w, y, x);
        public readonly float4 xwyy => new float4(x, w, y, y);
        public float4 xwyz { readonly get => new float4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
        public readonly float4 xwyw => new float4(x, w, y, w);
        public readonly float4 xwzx => new float4(x, w, z, x);
        public float4 xwzy { readonly get => new float4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
        public readonly float4 xwzz => new float4(x, w, z, z);
        public readonly float4 xwzw => new float4(x, w, z, w);
        public readonly float4 xwwx => new float4(x, w, w, x);
        public readonly float4 xwwy => new float4(x, w, w, y);
        public readonly float4 xwwz => new float4(x, w, w, z);
        public readonly float4 xwww => new float4(x, w, w, w);
        public readonly float4 yxxx => new float4(y, x, x, x);
        public readonly float4 yxxy => new float4(y, x, x, y);
        public readonly float4 yxxz => new float4(y, x, x, z);
        public readonly float4 yxxw => new float4(y, x, x, w);
        public readonly float4 yxyx => new float4(y, x, y, x);
        public readonly float4 yxyy => new float4(y, x, y, y);
        public readonly float4 yxyz => new float4(y, x, y, z);
        public readonly float4 yxyw => new float4(y, x, y, w);
        public readonly float4 yxzx => new float4(y, x, z, x);
        public readonly float4 yxzy => new float4(y, x, z, y);
        public readonly float4 yxzz => new float4(y, x, z, z);
        public float4 yxzw { readonly get => new float4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
        public readonly float4 yxwx => new float4(y, x, w, x);
        public readonly float4 yxwy => new float4(y, x, w, y);
        public float4 yxwz { readonly get => new float4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
        public readonly float4 yxww => new float4(y, x, w, w);
        public readonly float4 yyxx => new float4(y, y, x, x);
        public readonly float4 yyxy => new float4(y, y, x, y);
        public readonly float4 yyxz => new float4(y, y, x, z);
        public readonly float4 yyxw => new float4(y, y, x, w);
        public readonly float4 yyyx => new float4(y, y, y, x);
        public readonly float4 yyyy => new float4(y, y, y, y);
        public readonly float4 yyyz => new float4(y, y, y, z);
        public readonly float4 yyyw => new float4(y, y, y, w);
        public readonly float4 yyzx => new float4(y, y, z, x);
        public readonly float4 yyzy => new float4(y, y, z, y);
        public readonly float4 yyzz => new float4(y, y, z, z);
        public readonly float4 yyzw => new float4(y, y, z, w);
        public readonly float4 yywx => new float4(y, y, w, x);
        public readonly float4 yywy => new float4(y, y, w, y);
        public readonly float4 yywz => new float4(y, y, w, z);
        public readonly float4 yyww => new float4(y, y, w, w);
        public readonly float4 yzxx => new float4(y, z, x, x);
        public readonly float4 yzxy => new float4(y, z, x, y);
        public readonly float4 yzxz => new float4(y, z, x, z);
        public float4 yzxw { readonly get => new float4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
        public readonly float4 yzyx => new float4(y, z, y, x);
        public readonly float4 yzyy => new float4(y, z, y, y);
        public readonly float4 yzyz => new float4(y, z, y, z);
        public readonly float4 yzyw => new float4(y, z, y, w);
        public readonly float4 yzzx => new float4(y, z, z, x);
        public readonly float4 yzzy => new float4(y, z, z, y);
        public readonly float4 yzzz => new float4(y, z, z, z);
        public readonly float4 yzzw => new float4(y, z, z, w);
        public float4 yzwx { readonly get => new float4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
        public readonly float4 yzwy => new float4(y, z, w, y);
        public readonly float4 yzwz => new float4(y, z, w, z);
        public readonly float4 yzww => new float4(y, z, w, w);
        public readonly float4 ywxx => new float4(y, w, x, x);
        public readonly float4 ywxy => new float4(y, w, x, y);
        public float4 ywxz { readonly get => new float4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
        public readonly float4 ywxw => new float4(y, w, x, w);
        public readonly float4 ywyx => new float4(y, w, y, x);
        public readonly float4 ywyy => new float4(y, w, y, y);
        public readonly float4 ywyz => new float4(y, w, y, z);
        public readonly float4 ywyw => new float4(y, w, y, w);
        public float4 ywzx { readonly get => new float4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
        public readonly float4 ywzy => new float4(y, w, z, y);
        public readonly float4 ywzz => new float4(y, w, z, z);
        public readonly float4 ywzw => new float4(y, w, z, w);
        public readonly float4 ywwx => new float4(y, w, w, x);
        public readonly float4 ywwy => new float4(y, w, w, y);
        public readonly float4 ywwz => new float4(y, w, w, z);
        public readonly float4 ywww => new float4(y, w, w, w);
        public readonly float4 zxxx => new float4(z, x, x, x);
        public readonly float4 zxxy => new float4(z, x, x, y);
        public readonly float4 zxxz => new float4(z, x, x, z);
        public readonly float4 zxxw => new float4(z, x, x, w);
        public readonly float4 zxyx => new float4(z, x, y, x);
        public readonly float4 zxyy => new float4(z, x, y, y);
        public readonly float4 zxyz => new float4(z, x, y, z);
        public float4 zxyw { readonly get => new float4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
        public readonly float4 zxzx => new float4(z, x, z, x);
        public readonly float4 zxzy => new float4(z, x, z, y);
        public readonly float4 zxzz => new float4(z, x, z, z);
        public readonly float4 zxzw => new float4(z, x, z, w);
        public readonly float4 zxwx => new float4(z, x, w, x);
        public float4 zxwy { readonly get => new float4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
        public readonly float4 zxwz => new float4(z, x, w, z);
        public readonly float4 zxww => new float4(z, x, w, w);
        public readonly float4 zyxx => new float4(z, y, x, x);
        public readonly float4 zyxy => new float4(z, y, x, y);
        public readonly float4 zyxz => new float4(z, y, x, z);
        public float4 zyxw { readonly get => new float4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
        public readonly float4 zyyx => new float4(z, y, y, x);
        public readonly float4 zyyy => new float4(z, y, y, y);
        public readonly float4 zyyz => new float4(z, y, y, z);
        public readonly float4 zyyw => new float4(z, y, y, w);
        public readonly float4 zyzx => new float4(z, y, z, x);
        public readonly float4 zyzy => new float4(z, y, z, y);
        public readonly float4 zyzz => new float4(z, y, z, z);
        public readonly float4 zyzw => new float4(z, y, z, w);
        public float4 zywx { readonly get => new float4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
        public readonly float4 zywy => new float4(z, y, w, y);
        public readonly float4 zywz => new float4(z, y, w, z);
        public readonly float4 zyww => new float4(z, y, w, w);
        public readonly float4 zzxx => new float4(z, z, x, x);
        public readonly float4 zzxy => new float4(z, z, x, y);
        public readonly float4 zzxz => new float4(z, z, x, z);
        public readonly float4 zzxw => new float4(z, z, x, w);
        public readonly float4 zzyx => new float4(z, z, y, x);
        public readonly float4 zzyy => new float4(z, z, y, y);
        public readonly float4 zzyz => new float4(z, z, y, z);
        public readonly float4 zzyw => new float4(z, z, y, w);
        public readonly float4 zzzx => new float4(z, z, z, x);
        public readonly float4 zzzy => new float4(z, z, z, y);
        public readonly float4 zzzz => new float4(z, z, z, z);
        public readonly float4 zzzw => new float4(z, z, z, w);
        public readonly float4 zzwx => new float4(z, z, w, x);
        public readonly float4 zzwy => new float4(z, z, w, y);
        public readonly float4 zzwz => new float4(z, z, w, z);
        public readonly float4 zzww => new float4(z, z, w, w);
        public readonly float4 zwxx => new float4(z, w, x, x);
        public float4 zwxy { readonly get => new float4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
        public readonly float4 zwxz => new float4(z, w, x, z);
        public readonly float4 zwxw => new float4(z, w, x, w);
        public float4 zwyx { readonly get => new float4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
        public readonly float4 zwyy => new float4(z, w, y, y);
        public readonly float4 zwyz => new float4(z, w, y, z);
        public readonly float4 zwyw => new float4(z, w, y, w);
        public readonly float4 zwzx => new float4(z, w, z, x);
        public readonly float4 zwzy => new float4(z, w, z, y);
        public readonly float4 zwzz => new float4(z, w, z, z);
        public readonly float4 zwzw => new float4(z, w, z, w);
        public readonly float4 zwwx => new float4(z, w, w, x);
        public readonly float4 zwwy => new float4(z, w, w, y);
        public readonly float4 zwwz => new float4(z, w, w, z);
        public readonly float4 zwww => new float4(z, w, w, w);
        public readonly float4 wxxx => new float4(w, x, x, x);
        public readonly float4 wxxy => new float4(w, x, x, y);
        public readonly float4 wxxz => new float4(w, x, x, z);
        public readonly float4 wxxw => new float4(w, x, x, w);
        public readonly float4 wxyx => new float4(w, x, y, x);
        public readonly float4 wxyy => new float4(w, x, y, y);
        public float4 wxyz { readonly get => new float4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
        public readonly float4 wxyw => new float4(w, x, y, w);
        public readonly float4 wxzx => new float4(w, x, z, x);
        public float4 wxzy { readonly get => new float4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
        public readonly float4 wxzz => new float4(w, x, z, z);
        public readonly float4 wxzw => new float4(w, x, z, w);
        public readonly float4 wxwx => new float4(w, x, w, x);
        public readonly float4 wxwy => new float4(w, x, w, y);
        public readonly float4 wxwz => new float4(w, x, w, z);
        public readonly float4 wxww => new float4(w, x, w, w);
        public readonly float4 wyxx => new float4(w, y, x, x);
        public readonly float4 wyxy => new float4(w, y, x, y);
        public float4 wyxz { readonly get => new float4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
        public readonly float4 wyxw => new float4(w, y, x, w);
        public readonly float4 wyyx => new float4(w, y, y, x);
        public readonly float4 wyyy => new float4(w, y, y, y);
        public readonly float4 wyyz => new float4(w, y, y, z);
        public readonly float4 wyyw => new float4(w, y, y, w);
        public float4 wyzx { readonly get => new float4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
        public readonly float4 wyzy => new float4(w, y, z, y);
        public readonly float4 wyzz => new float4(w, y, z, z);
        public readonly float4 wyzw => new float4(w, y, z, w);
        public readonly float4 wywx => new float4(w, y, w, x);
        public readonly float4 wywy => new float4(w, y, w, y);
        public readonly float4 wywz => new float4(w, y, w, z);
        public readonly float4 wyww => new float4(w, y, w, w);
        public readonly float4 wzxx => new float4(w, z, x, x);
        public float4 wzxy { readonly get => new float4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
        public readonly float4 wzxz => new float4(w, z, x, z);
        public readonly float4 wzxw => new float4(w, z, x, w);
        public float4 wzyx { readonly get => new float4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
        public readonly float4 wzyy => new float4(w, z, y, y);
        public readonly float4 wzyz => new float4(w, z, y, z);
        public readonly float4 wzyw => new float4(w, z, y, w);
        public readonly float4 wzzx => new float4(w, z, z, x);
        public readonly float4 wzzy => new float4(w, z, z, y);
        public readonly float4 wzzz => new float4(w, z, z, z);
        public readonly float4 wzzw => new float4(w, z, z, w);
        public readonly float4 wzwx => new float4(w, z, w, x);
        public readonly float4 wzwy => new float4(w, z, w, y);
        public readonly float4 wzwz => new float4(w, z, w, z);
        public readonly float4 wzww => new float4(w, z, w, w);
        public readonly float4 wwxx => new float4(w, w, x, x);
        public readonly float4 wwxy => new float4(w, w, x, y);
        public readonly float4 wwxz => new float4(w, w, x, z);
        public readonly float4 wwxw => new float4(w, w, x, w);
        public readonly float4 wwyx => new float4(w, w, y, x);
        public readonly float4 wwyy => new float4(w, w, y, y);
        public readonly float4 wwyz => new float4(w, w, y, z);
        public readonly float4 wwyw => new float4(w, w, y, w);
        public readonly float4 wwzx => new float4(w, w, z, x);
        public readonly float4 wwzy => new float4(w, w, z, y);
        public readonly float4 wwzz => new float4(w, w, z, z);
        public readonly float4 wwzw => new float4(w, w, z, w);
        public readonly float4 wwwx => new float4(w, w, w, x);
        public readonly float4 wwwy => new float4(w, w, w, y);
        public readonly float4 wwwz => new float4(w, w, w, z);
        public readonly float4 wwww => new float4(w, w, w, w);
        public readonly bool Equals(float4 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y) && z.Equals(rhs.z) && w.Equals(rhs.w);
        public override readonly bool Equals(object o) => o is float4 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y, z, w);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "float4({0}f, {1}f, {2}f, {3}f)", x, y, z, w);
        public readonly string ToString(string format, IFormatProvider formatProvider) => string.Format("float4({0}f, {1}f, {2}f, {3}f)", x.ToString(format, formatProvider), y.ToString(format, formatProvider), z.ToString(format, formatProvider), w.ToString(format, formatProvider));
    }
}
