// <auto-generated>
// Generated by the port's math shim generator (first-party). Behavior-level re-implementation
// of the Unity.Mathematics public API surface the game compiles against; not vendored source.
// </auto-generated>
using System;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace Unity.Mathematics
{
    [Serializable]
    public partial struct int2 : IEquatable<int2>, IFormattable
    {
        public int x;
        public int y;
        public static readonly int2 zero;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int2(int x, int y) { this.x = x; this.y = y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int2(int2 xy) { this.x = xy.x; this.y = xy.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int2(int v) { x = v; y = v; }
        public int2(float v) { x = (int)(v); y = (int)(v); }
        public int2(float2 v) { x = (int)(v.x); y = (int)(v.y); }
        public int2(double v) { x = (int)(v); y = (int)(v); }
        public int2(double2 v) { x = (int)(v.x); y = (int)(v.y); }
        public int2(uint v) { x = (int)(v); y = (int)(v); }
        public int2(uint2 v) { x = (int)(v.x); y = (int)(v.y); }
        public int2(bool v) { x = (v ? 1 : 0); y = (v ? 1 : 0); }
        public int2(bool2 v) { x = (v.x ? 1 : 0); y = (v.y ? 1 : 0); }
        public static implicit operator int2(int v) => new int2(v);
        public static explicit operator int2(float v) => new int2(v);
        public static explicit operator int2(float2 v) => new int2(v);
        public static explicit operator int2(double v) => new int2(v);
        public static explicit operator int2(double2 v) => new int2(v);
        public static explicit operator int2(uint v) => new int2(v);
        public static explicit operator int2(uint2 v) => new int2(v);
        public static explicit operator int2(bool v) => new int2(v);
        public static explicit operator int2(bool2 v) => new int2(v);
        public static int2 operator +(int2 a, int2 b) => new int2(a.x + b.x, a.y + b.y);
        public static int2 operator +(int2 a, int b) => new int2(a.x + b, a.y + b);
        public static int2 operator +(int a, int2 b) => new int2(a + b.x, a + b.y);
        public static int2 operator -(int2 a, int2 b) => new int2(a.x - b.x, a.y - b.y);
        public static int2 operator -(int2 a, int b) => new int2(a.x - b, a.y - b);
        public static int2 operator -(int a, int2 b) => new int2(a - b.x, a - b.y);
        public static int2 operator *(int2 a, int2 b) => new int2(a.x * b.x, a.y * b.y);
        public static int2 operator *(int2 a, int b) => new int2(a.x * b, a.y * b);
        public static int2 operator *(int a, int2 b) => new int2(a * b.x, a * b.y);
        public static int2 operator /(int2 a, int2 b) => new int2(a.x / b.x, a.y / b.y);
        public static int2 operator /(int2 a, int b) => new int2(a.x / b, a.y / b);
        public static int2 operator /(int a, int2 b) => new int2(a / b.x, a / b.y);
        public static int2 operator %(int2 a, int2 b) => new int2(a.x % b.x, a.y % b.y);
        public static int2 operator %(int2 a, int b) => new int2(a.x % b, a.y % b);
        public static int2 operator %(int a, int2 b) => new int2(a % b.x, a % b.y);
        public static int2 operator ++(int2 v) => new int2(v.x + 1, v.y + 1);
        public static int2 operator --(int2 v) => new int2(v.x - 1, v.y - 1);
        public static int2 operator +(int2 v) => v;
        public static int2 operator -(int2 v) => new int2(-v.x, -v.y);
        public static bool2 operator <(int2 a, int2 b) => new bool2(a.x < b.x, a.y < b.y);
        public static bool2 operator <(int2 a, int b) => new bool2(a.x < b, a.y < b);
        public static bool2 operator <(int a, int2 b) => new bool2(a < b.x, a < b.y);
        public static bool2 operator <=(int2 a, int2 b) => new bool2(a.x <= b.x, a.y <= b.y);
        public static bool2 operator <=(int2 a, int b) => new bool2(a.x <= b, a.y <= b);
        public static bool2 operator <=(int a, int2 b) => new bool2(a <= b.x, a <= b.y);
        public static bool2 operator >(int2 a, int2 b) => new bool2(a.x > b.x, a.y > b.y);
        public static bool2 operator >(int2 a, int b) => new bool2(a.x > b, a.y > b);
        public static bool2 operator >(int a, int2 b) => new bool2(a > b.x, a > b.y);
        public static bool2 operator >=(int2 a, int2 b) => new bool2(a.x >= b.x, a.y >= b.y);
        public static bool2 operator >=(int2 a, int b) => new bool2(a.x >= b, a.y >= b);
        public static bool2 operator >=(int a, int2 b) => new bool2(a >= b.x, a >= b.y);
        public static bool2 operator ==(int2 a, int2 b) => new bool2(a.x == b.x, a.y == b.y);
        public static bool2 operator ==(int2 a, int b) => new bool2(a.x == b, a.y == b);
        public static bool2 operator ==(int a, int2 b) => new bool2(a == b.x, a == b.y);
        public static bool2 operator !=(int2 a, int2 b) => new bool2(a.x != b.x, a.y != b.y);
        public static bool2 operator !=(int2 a, int b) => new bool2(a.x != b, a.y != b);
        public static bool2 operator !=(int a, int2 b) => new bool2(a != b.x, a != b.y);
        public static int2 operator &(int2 a, int2 b) => new int2(a.x & b.x, a.y & b.y);
        public static int2 operator &(int2 a, int b) => new int2(a.x & b, a.y & b);
        public static int2 operator &(int a, int2 b) => new int2(a & b.x, a & b.y);
        public static int2 operator |(int2 a, int2 b) => new int2(a.x | b.x, a.y | b.y);
        public static int2 operator |(int2 a, int b) => new int2(a.x | b, a.y | b);
        public static int2 operator |(int a, int2 b) => new int2(a | b.x, a | b.y);
        public static int2 operator ^(int2 a, int2 b) => new int2(a.x ^ b.x, a.y ^ b.y);
        public static int2 operator ^(int2 a, int b) => new int2(a.x ^ b, a.y ^ b);
        public static int2 operator ^(int a, int2 b) => new int2(a ^ b.x, a ^ b.y);
        public static int2 operator ~(int2 v) => new int2(~v.x, ~v.y);
        public static int2 operator <<(int2 v, int n) => new int2(v.x << n, v.y << n);
        public static int2 operator >>(int2 v, int n) => new int2(v.x >> n, v.y >> n);
        public int this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly int2 xx => new int2(x, x);
        public int2 xy { readonly get => new int2(x, y); set { x = value.x; y = value.y; } }
        public int2 yx { readonly get => new int2(y, x); set { y = value.x; x = value.y; } }
        public readonly int2 yy => new int2(y, y);
        public readonly int3 xxx => new int3(x, x, x);
        public readonly int3 xxy => new int3(x, x, y);
        public readonly int3 xyx => new int3(x, y, x);
        public readonly int3 xyy => new int3(x, y, y);
        public readonly int3 yxx => new int3(y, x, x);
        public readonly int3 yxy => new int3(y, x, y);
        public readonly int3 yyx => new int3(y, y, x);
        public readonly int3 yyy => new int3(y, y, y);
        public readonly int4 xxxx => new int4(x, x, x, x);
        public readonly int4 xxxy => new int4(x, x, x, y);
        public readonly int4 xxyx => new int4(x, x, y, x);
        public readonly int4 xxyy => new int4(x, x, y, y);
        public readonly int4 xyxx => new int4(x, y, x, x);
        public readonly int4 xyxy => new int4(x, y, x, y);
        public readonly int4 xyyx => new int4(x, y, y, x);
        public readonly int4 xyyy => new int4(x, y, y, y);
        public readonly int4 yxxx => new int4(y, x, x, x);
        public readonly int4 yxxy => new int4(y, x, x, y);
        public readonly int4 yxyx => new int4(y, x, y, x);
        public readonly int4 yxyy => new int4(y, x, y, y);
        public readonly int4 yyxx => new int4(y, y, x, x);
        public readonly int4 yyxy => new int4(y, y, x, y);
        public readonly int4 yyyx => new int4(y, y, y, x);
        public readonly int4 yyyy => new int4(y, y, y, y);
        public readonly bool Equals(int2 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y);
        public override readonly bool Equals(object o) => o is int2 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "int2({0}, {1})", x, y);
        public readonly string ToString(string format, IFormatProvider formatProvider) => string.Format("int2({0}, {1})", x.ToString(format, formatProvider), y.ToString(format, formatProvider));
    }

    [Serializable]
    public partial struct int3 : IEquatable<int3>, IFormattable
    {
        public int x;
        public int y;
        public int z;
        public static readonly int3 zero;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int3(int x, int y, int z) { this.x = x; this.y = y; this.z = z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int3(int x, int2 yz) { this.x = x; this.y = yz.x; this.z = yz.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int3(int2 xy, int z) { this.x = xy.x; this.y = xy.y; this.z = z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int3(int3 xyz) { this.x = xyz.x; this.y = xyz.y; this.z = xyz.z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int3(int v) { x = v; y = v; z = v; }
        public int3(float v) { x = (int)(v); y = (int)(v); z = (int)(v); }
        public int3(float3 v) { x = (int)(v.x); y = (int)(v.y); z = (int)(v.z); }
        public int3(double v) { x = (int)(v); y = (int)(v); z = (int)(v); }
        public int3(double3 v) { x = (int)(v.x); y = (int)(v.y); z = (int)(v.z); }
        public int3(uint v) { x = (int)(v); y = (int)(v); z = (int)(v); }
        public int3(uint3 v) { x = (int)(v.x); y = (int)(v.y); z = (int)(v.z); }
        public int3(bool v) { x = (v ? 1 : 0); y = (v ? 1 : 0); z = (v ? 1 : 0); }
        public int3(bool3 v) { x = (v.x ? 1 : 0); y = (v.y ? 1 : 0); z = (v.z ? 1 : 0); }
        public static implicit operator int3(int v) => new int3(v);
        public static explicit operator int3(float v) => new int3(v);
        public static explicit operator int3(float3 v) => new int3(v);
        public static explicit operator int3(double v) => new int3(v);
        public static explicit operator int3(double3 v) => new int3(v);
        public static explicit operator int3(uint v) => new int3(v);
        public static explicit operator int3(uint3 v) => new int3(v);
        public static explicit operator int3(bool v) => new int3(v);
        public static explicit operator int3(bool3 v) => new int3(v);
        public static int3 operator +(int3 a, int3 b) => new int3(a.x + b.x, a.y + b.y, a.z + b.z);
        public static int3 operator +(int3 a, int b) => new int3(a.x + b, a.y + b, a.z + b);
        public static int3 operator +(int a, int3 b) => new int3(a + b.x, a + b.y, a + b.z);
        public static int3 operator -(int3 a, int3 b) => new int3(a.x - b.x, a.y - b.y, a.z - b.z);
        public static int3 operator -(int3 a, int b) => new int3(a.x - b, a.y - b, a.z - b);
        public static int3 operator -(int a, int3 b) => new int3(a - b.x, a - b.y, a - b.z);
        public static int3 operator *(int3 a, int3 b) => new int3(a.x * b.x, a.y * b.y, a.z * b.z);
        public static int3 operator *(int3 a, int b) => new int3(a.x * b, a.y * b, a.z * b);
        public static int3 operator *(int a, int3 b) => new int3(a * b.x, a * b.y, a * b.z);
        public static int3 operator /(int3 a, int3 b) => new int3(a.x / b.x, a.y / b.y, a.z / b.z);
        public static int3 operator /(int3 a, int b) => new int3(a.x / b, a.y / b, a.z / b);
        public static int3 operator /(int a, int3 b) => new int3(a / b.x, a / b.y, a / b.z);
        public static int3 operator %(int3 a, int3 b) => new int3(a.x % b.x, a.y % b.y, a.z % b.z);
        public static int3 operator %(int3 a, int b) => new int3(a.x % b, a.y % b, a.z % b);
        public static int3 operator %(int a, int3 b) => new int3(a % b.x, a % b.y, a % b.z);
        public static int3 operator ++(int3 v) => new int3(v.x + 1, v.y + 1, v.z + 1);
        public static int3 operator --(int3 v) => new int3(v.x - 1, v.y - 1, v.z - 1);
        public static int3 operator +(int3 v) => v;
        public static int3 operator -(int3 v) => new int3(-v.x, -v.y, -v.z);
        public static bool3 operator <(int3 a, int3 b) => new bool3(a.x < b.x, a.y < b.y, a.z < b.z);
        public static bool3 operator <(int3 a, int b) => new bool3(a.x < b, a.y < b, a.z < b);
        public static bool3 operator <(int a, int3 b) => new bool3(a < b.x, a < b.y, a < b.z);
        public static bool3 operator <=(int3 a, int3 b) => new bool3(a.x <= b.x, a.y <= b.y, a.z <= b.z);
        public static bool3 operator <=(int3 a, int b) => new bool3(a.x <= b, a.y <= b, a.z <= b);
        public static bool3 operator <=(int a, int3 b) => new bool3(a <= b.x, a <= b.y, a <= b.z);
        public static bool3 operator >(int3 a, int3 b) => new bool3(a.x > b.x, a.y > b.y, a.z > b.z);
        public static bool3 operator >(int3 a, int b) => new bool3(a.x > b, a.y > b, a.z > b);
        public static bool3 operator >(int a, int3 b) => new bool3(a > b.x, a > b.y, a > b.z);
        public static bool3 operator >=(int3 a, int3 b) => new bool3(a.x >= b.x, a.y >= b.y, a.z >= b.z);
        public static bool3 operator >=(int3 a, int b) => new bool3(a.x >= b, a.y >= b, a.z >= b);
        public static bool3 operator >=(int a, int3 b) => new bool3(a >= b.x, a >= b.y, a >= b.z);
        public static bool3 operator ==(int3 a, int3 b) => new bool3(a.x == b.x, a.y == b.y, a.z == b.z);
        public static bool3 operator ==(int3 a, int b) => new bool3(a.x == b, a.y == b, a.z == b);
        public static bool3 operator ==(int a, int3 b) => new bool3(a == b.x, a == b.y, a == b.z);
        public static bool3 operator !=(int3 a, int3 b) => new bool3(a.x != b.x, a.y != b.y, a.z != b.z);
        public static bool3 operator !=(int3 a, int b) => new bool3(a.x != b, a.y != b, a.z != b);
        public static bool3 operator !=(int a, int3 b) => new bool3(a != b.x, a != b.y, a != b.z);
        public static int3 operator &(int3 a, int3 b) => new int3(a.x & b.x, a.y & b.y, a.z & b.z);
        public static int3 operator &(int3 a, int b) => new int3(a.x & b, a.y & b, a.z & b);
        public static int3 operator &(int a, int3 b) => new int3(a & b.x, a & b.y, a & b.z);
        public static int3 operator |(int3 a, int3 b) => new int3(a.x | b.x, a.y | b.y, a.z | b.z);
        public static int3 operator |(int3 a, int b) => new int3(a.x | b, a.y | b, a.z | b);
        public static int3 operator |(int a, int3 b) => new int3(a | b.x, a | b.y, a | b.z);
        public static int3 operator ^(int3 a, int3 b) => new int3(a.x ^ b.x, a.y ^ b.y, a.z ^ b.z);
        public static int3 operator ^(int3 a, int b) => new int3(a.x ^ b, a.y ^ b, a.z ^ b);
        public static int3 operator ^(int a, int3 b) => new int3(a ^ b.x, a ^ b.y, a ^ b.z);
        public static int3 operator ~(int3 v) => new int3(~v.x, ~v.y, ~v.z);
        public static int3 operator <<(int3 v, int n) => new int3(v.x << n, v.y << n, v.z << n);
        public static int3 operator >>(int3 v, int n) => new int3(v.x >> n, v.y >> n, v.z >> n);
        public int this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; case 2: return z; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly int2 xx => new int2(x, x);
        public int2 xy { readonly get => new int2(x, y); set { x = value.x; y = value.y; } }
        public int2 xz { readonly get => new int2(x, z); set { x = value.x; z = value.y; } }
        public int2 yx { readonly get => new int2(y, x); set { y = value.x; x = value.y; } }
        public readonly int2 yy => new int2(y, y);
        public int2 yz { readonly get => new int2(y, z); set { y = value.x; z = value.y; } }
        public int2 zx { readonly get => new int2(z, x); set { z = value.x; x = value.y; } }
        public int2 zy { readonly get => new int2(z, y); set { z = value.x; y = value.y; } }
        public readonly int2 zz => new int2(z, z);
        public readonly int3 xxx => new int3(x, x, x);
        public readonly int3 xxy => new int3(x, x, y);
        public readonly int3 xxz => new int3(x, x, z);
        public readonly int3 xyx => new int3(x, y, x);
        public readonly int3 xyy => new int3(x, y, y);
        public int3 xyz { readonly get => new int3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
        public readonly int3 xzx => new int3(x, z, x);
        public int3 xzy { readonly get => new int3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
        public readonly int3 xzz => new int3(x, z, z);
        public readonly int3 yxx => new int3(y, x, x);
        public readonly int3 yxy => new int3(y, x, y);
        public int3 yxz { readonly get => new int3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
        public readonly int3 yyx => new int3(y, y, x);
        public readonly int3 yyy => new int3(y, y, y);
        public readonly int3 yyz => new int3(y, y, z);
        public int3 yzx { readonly get => new int3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
        public readonly int3 yzy => new int3(y, z, y);
        public readonly int3 yzz => new int3(y, z, z);
        public readonly int3 zxx => new int3(z, x, x);
        public int3 zxy { readonly get => new int3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
        public readonly int3 zxz => new int3(z, x, z);
        public int3 zyx { readonly get => new int3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
        public readonly int3 zyy => new int3(z, y, y);
        public readonly int3 zyz => new int3(z, y, z);
        public readonly int3 zzx => new int3(z, z, x);
        public readonly int3 zzy => new int3(z, z, y);
        public readonly int3 zzz => new int3(z, z, z);
        public readonly int4 xxxx => new int4(x, x, x, x);
        public readonly int4 xxxy => new int4(x, x, x, y);
        public readonly int4 xxxz => new int4(x, x, x, z);
        public readonly int4 xxyx => new int4(x, x, y, x);
        public readonly int4 xxyy => new int4(x, x, y, y);
        public readonly int4 xxyz => new int4(x, x, y, z);
        public readonly int4 xxzx => new int4(x, x, z, x);
        public readonly int4 xxzy => new int4(x, x, z, y);
        public readonly int4 xxzz => new int4(x, x, z, z);
        public readonly int4 xyxx => new int4(x, y, x, x);
        public readonly int4 xyxy => new int4(x, y, x, y);
        public readonly int4 xyxz => new int4(x, y, x, z);
        public readonly int4 xyyx => new int4(x, y, y, x);
        public readonly int4 xyyy => new int4(x, y, y, y);
        public readonly int4 xyyz => new int4(x, y, y, z);
        public readonly int4 xyzx => new int4(x, y, z, x);
        public readonly int4 xyzy => new int4(x, y, z, y);
        public readonly int4 xyzz => new int4(x, y, z, z);
        public readonly int4 xzxx => new int4(x, z, x, x);
        public readonly int4 xzxy => new int4(x, z, x, y);
        public readonly int4 xzxz => new int4(x, z, x, z);
        public readonly int4 xzyx => new int4(x, z, y, x);
        public readonly int4 xzyy => new int4(x, z, y, y);
        public readonly int4 xzyz => new int4(x, z, y, z);
        public readonly int4 xzzx => new int4(x, z, z, x);
        public readonly int4 xzzy => new int4(x, z, z, y);
        public readonly int4 xzzz => new int4(x, z, z, z);
        public readonly int4 yxxx => new int4(y, x, x, x);
        public readonly int4 yxxy => new int4(y, x, x, y);
        public readonly int4 yxxz => new int4(y, x, x, z);
        public readonly int4 yxyx => new int4(y, x, y, x);
        public readonly int4 yxyy => new int4(y, x, y, y);
        public readonly int4 yxyz => new int4(y, x, y, z);
        public readonly int4 yxzx => new int4(y, x, z, x);
        public readonly int4 yxzy => new int4(y, x, z, y);
        public readonly int4 yxzz => new int4(y, x, z, z);
        public readonly int4 yyxx => new int4(y, y, x, x);
        public readonly int4 yyxy => new int4(y, y, x, y);
        public readonly int4 yyxz => new int4(y, y, x, z);
        public readonly int4 yyyx => new int4(y, y, y, x);
        public readonly int4 yyyy => new int4(y, y, y, y);
        public readonly int4 yyyz => new int4(y, y, y, z);
        public readonly int4 yyzx => new int4(y, y, z, x);
        public readonly int4 yyzy => new int4(y, y, z, y);
        public readonly int4 yyzz => new int4(y, y, z, z);
        public readonly int4 yzxx => new int4(y, z, x, x);
        public readonly int4 yzxy => new int4(y, z, x, y);
        public readonly int4 yzxz => new int4(y, z, x, z);
        public readonly int4 yzyx => new int4(y, z, y, x);
        public readonly int4 yzyy => new int4(y, z, y, y);
        public readonly int4 yzyz => new int4(y, z, y, z);
        public readonly int4 yzzx => new int4(y, z, z, x);
        public readonly int4 yzzy => new int4(y, z, z, y);
        public readonly int4 yzzz => new int4(y, z, z, z);
        public readonly int4 zxxx => new int4(z, x, x, x);
        public readonly int4 zxxy => new int4(z, x, x, y);
        public readonly int4 zxxz => new int4(z, x, x, z);
        public readonly int4 zxyx => new int4(z, x, y, x);
        public readonly int4 zxyy => new int4(z, x, y, y);
        public readonly int4 zxyz => new int4(z, x, y, z);
        public readonly int4 zxzx => new int4(z, x, z, x);
        public readonly int4 zxzy => new int4(z, x, z, y);
        public readonly int4 zxzz => new int4(z, x, z, z);
        public readonly int4 zyxx => new int4(z, y, x, x);
        public readonly int4 zyxy => new int4(z, y, x, y);
        public readonly int4 zyxz => new int4(z, y, x, z);
        public readonly int4 zyyx => new int4(z, y, y, x);
        public readonly int4 zyyy => new int4(z, y, y, y);
        public readonly int4 zyyz => new int4(z, y, y, z);
        public readonly int4 zyzx => new int4(z, y, z, x);
        public readonly int4 zyzy => new int4(z, y, z, y);
        public readonly int4 zyzz => new int4(z, y, z, z);
        public readonly int4 zzxx => new int4(z, z, x, x);
        public readonly int4 zzxy => new int4(z, z, x, y);
        public readonly int4 zzxz => new int4(z, z, x, z);
        public readonly int4 zzyx => new int4(z, z, y, x);
        public readonly int4 zzyy => new int4(z, z, y, y);
        public readonly int4 zzyz => new int4(z, z, y, z);
        public readonly int4 zzzx => new int4(z, z, z, x);
        public readonly int4 zzzy => new int4(z, z, z, y);
        public readonly int4 zzzz => new int4(z, z, z, z);
        public readonly bool Equals(int3 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y) && z.Equals(rhs.z);
        public override readonly bool Equals(object o) => o is int3 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y, z);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "int3({0}, {1}, {2})", x, y, z);
        public readonly string ToString(string format, IFormatProvider formatProvider) => string.Format("int3({0}, {1}, {2})", x.ToString(format, formatProvider), y.ToString(format, formatProvider), z.ToString(format, formatProvider));
    }

    [Serializable]
    public partial struct int4 : IEquatable<int4>, IFormattable
    {
        public int x;
        public int y;
        public int z;
        public int w;
        public static readonly int4 zero;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int4(int x, int y, int z, int w) { this.x = x; this.y = y; this.z = z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int4(int x, int y, int2 zw) { this.x = x; this.y = y; this.z = zw.x; this.w = zw.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int4(int x, int2 yz, int w) { this.x = x; this.y = yz.x; this.z = yz.y; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int4(int x, int3 yzw) { this.x = x; this.y = yzw.x; this.z = yzw.y; this.w = yzw.z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int4(int2 xy, int z, int w) { this.x = xy.x; this.y = xy.y; this.z = z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int4(int2 xy, int2 zw) { this.x = xy.x; this.y = xy.y; this.z = zw.x; this.w = zw.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int4(int3 xyz, int w) { this.x = xyz.x; this.y = xyz.y; this.z = xyz.z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int4(int4 xyzw) { this.x = xyzw.x; this.y = xyzw.y; this.z = xyzw.z; this.w = xyzw.w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public int4(int v) { x = v; y = v; z = v; w = v; }
        public int4(float v) { x = (int)(v); y = (int)(v); z = (int)(v); w = (int)(v); }
        public int4(float4 v) { x = (int)(v.x); y = (int)(v.y); z = (int)(v.z); w = (int)(v.w); }
        public int4(double v) { x = (int)(v); y = (int)(v); z = (int)(v); w = (int)(v); }
        public int4(double4 v) { x = (int)(v.x); y = (int)(v.y); z = (int)(v.z); w = (int)(v.w); }
        public int4(uint v) { x = (int)(v); y = (int)(v); z = (int)(v); w = (int)(v); }
        public int4(uint4 v) { x = (int)(v.x); y = (int)(v.y); z = (int)(v.z); w = (int)(v.w); }
        public int4(bool v) { x = (v ? 1 : 0); y = (v ? 1 : 0); z = (v ? 1 : 0); w = (v ? 1 : 0); }
        public int4(bool4 v) { x = (v.x ? 1 : 0); y = (v.y ? 1 : 0); z = (v.z ? 1 : 0); w = (v.w ? 1 : 0); }
        public static implicit operator int4(int v) => new int4(v);
        public static explicit operator int4(float v) => new int4(v);
        public static explicit operator int4(float4 v) => new int4(v);
        public static explicit operator int4(double v) => new int4(v);
        public static explicit operator int4(double4 v) => new int4(v);
        public static explicit operator int4(uint v) => new int4(v);
        public static explicit operator int4(uint4 v) => new int4(v);
        public static explicit operator int4(bool v) => new int4(v);
        public static explicit operator int4(bool4 v) => new int4(v);
        public static int4 operator +(int4 a, int4 b) => new int4(a.x + b.x, a.y + b.y, a.z + b.z, a.w + b.w);
        public static int4 operator +(int4 a, int b) => new int4(a.x + b, a.y + b, a.z + b, a.w + b);
        public static int4 operator +(int a, int4 b) => new int4(a + b.x, a + b.y, a + b.z, a + b.w);
        public static int4 operator -(int4 a, int4 b) => new int4(a.x - b.x, a.y - b.y, a.z - b.z, a.w - b.w);
        public static int4 operator -(int4 a, int b) => new int4(a.x - b, a.y - b, a.z - b, a.w - b);
        public static int4 operator -(int a, int4 b) => new int4(a - b.x, a - b.y, a - b.z, a - b.w);
        public static int4 operator *(int4 a, int4 b) => new int4(a.x * b.x, a.y * b.y, a.z * b.z, a.w * b.w);
        public static int4 operator *(int4 a, int b) => new int4(a.x * b, a.y * b, a.z * b, a.w * b);
        public static int4 operator *(int a, int4 b) => new int4(a * b.x, a * b.y, a * b.z, a * b.w);
        public static int4 operator /(int4 a, int4 b) => new int4(a.x / b.x, a.y / b.y, a.z / b.z, a.w / b.w);
        public static int4 operator /(int4 a, int b) => new int4(a.x / b, a.y / b, a.z / b, a.w / b);
        public static int4 operator /(int a, int4 b) => new int4(a / b.x, a / b.y, a / b.z, a / b.w);
        public static int4 operator %(int4 a, int4 b) => new int4(a.x % b.x, a.y % b.y, a.z % b.z, a.w % b.w);
        public static int4 operator %(int4 a, int b) => new int4(a.x % b, a.y % b, a.z % b, a.w % b);
        public static int4 operator %(int a, int4 b) => new int4(a % b.x, a % b.y, a % b.z, a % b.w);
        public static int4 operator ++(int4 v) => new int4(v.x + 1, v.y + 1, v.z + 1, v.w + 1);
        public static int4 operator --(int4 v) => new int4(v.x - 1, v.y - 1, v.z - 1, v.w - 1);
        public static int4 operator +(int4 v) => v;
        public static int4 operator -(int4 v) => new int4(-v.x, -v.y, -v.z, -v.w);
        public static bool4 operator <(int4 a, int4 b) => new bool4(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
        public static bool4 operator <(int4 a, int b) => new bool4(a.x < b, a.y < b, a.z < b, a.w < b);
        public static bool4 operator <(int a, int4 b) => new bool4(a < b.x, a < b.y, a < b.z, a < b.w);
        public static bool4 operator <=(int4 a, int4 b) => new bool4(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
        public static bool4 operator <=(int4 a, int b) => new bool4(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
        public static bool4 operator <=(int a, int4 b) => new bool4(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
        public static bool4 operator >(int4 a, int4 b) => new bool4(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
        public static bool4 operator >(int4 a, int b) => new bool4(a.x > b, a.y > b, a.z > b, a.w > b);
        public static bool4 operator >(int a, int4 b) => new bool4(a > b.x, a > b.y, a > b.z, a > b.w);
        public static bool4 operator >=(int4 a, int4 b) => new bool4(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
        public static bool4 operator >=(int4 a, int b) => new bool4(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
        public static bool4 operator >=(int a, int4 b) => new bool4(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
        public static bool4 operator ==(int4 a, int4 b) => new bool4(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
        public static bool4 operator ==(int4 a, int b) => new bool4(a.x == b, a.y == b, a.z == b, a.w == b);
        public static bool4 operator ==(int a, int4 b) => new bool4(a == b.x, a == b.y, a == b.z, a == b.w);
        public static bool4 operator !=(int4 a, int4 b) => new bool4(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
        public static bool4 operator !=(int4 a, int b) => new bool4(a.x != b, a.y != b, a.z != b, a.w != b);
        public static bool4 operator !=(int a, int4 b) => new bool4(a != b.x, a != b.y, a != b.z, a != b.w);
        public static int4 operator &(int4 a, int4 b) => new int4(a.x & b.x, a.y & b.y, a.z & b.z, a.w & b.w);
        public static int4 operator &(int4 a, int b) => new int4(a.x & b, a.y & b, a.z & b, a.w & b);
        public static int4 operator &(int a, int4 b) => new int4(a & b.x, a & b.y, a & b.z, a & b.w);
        public static int4 operator |(int4 a, int4 b) => new int4(a.x | b.x, a.y | b.y, a.z | b.z, a.w | b.w);
        public static int4 operator |(int4 a, int b) => new int4(a.x | b, a.y | b, a.z | b, a.w | b);
        public static int4 operator |(int a, int4 b) => new int4(a | b.x, a | b.y, a | b.z, a | b.w);
        public static int4 operator ^(int4 a, int4 b) => new int4(a.x ^ b.x, a.y ^ b.y, a.z ^ b.z, a.w ^ b.w);
        public static int4 operator ^(int4 a, int b) => new int4(a.x ^ b, a.y ^ b, a.z ^ b, a.w ^ b);
        public static int4 operator ^(int a, int4 b) => new int4(a ^ b.x, a ^ b.y, a ^ b.z, a ^ b.w);
        public static int4 operator ~(int4 v) => new int4(~v.x, ~v.y, ~v.z, ~v.w);
        public static int4 operator <<(int4 v, int n) => new int4(v.x << n, v.y << n, v.z << n, v.w << n);
        public static int4 operator >>(int4 v, int n) => new int4(v.x >> n, v.y >> n, v.z >> n, v.w >> n);
        public int this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; case 2: return z; case 3: return w; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; case 3: w = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly int2 xx => new int2(x, x);
        public int2 xy { readonly get => new int2(x, y); set { x = value.x; y = value.y; } }
        public int2 xz { readonly get => new int2(x, z); set { x = value.x; z = value.y; } }
        public int2 xw { readonly get => new int2(x, w); set { x = value.x; w = value.y; } }
        public int2 yx { readonly get => new int2(y, x); set { y = value.x; x = value.y; } }
        public readonly int2 yy => new int2(y, y);
        public int2 yz { readonly get => new int2(y, z); set { y = value.x; z = value.y; } }
        public int2 yw { readonly get => new int2(y, w); set { y = value.x; w = value.y; } }
        public int2 zx { readonly get => new int2(z, x); set { z = value.x; x = value.y; } }
        public int2 zy { readonly get => new int2(z, y); set { z = value.x; y = value.y; } }
        public readonly int2 zz => new int2(z, z);
        public int2 zw { readonly get => new int2(z, w); set { z = value.x; w = value.y; } }
        public int2 wx { readonly get => new int2(w, x); set { w = value.x; x = value.y; } }
        public int2 wy { readonly get => new int2(w, y); set { w = value.x; y = value.y; } }
        public int2 wz { readonly get => new int2(w, z); set { w = value.x; z = value.y; } }
        public readonly int2 ww => new int2(w, w);
        public readonly int3 xxx => new int3(x, x, x);
        public readonly int3 xxy => new int3(x, x, y);
        public readonly int3 xxz => new int3(x, x, z);
        public readonly int3 xxw => new int3(x, x, w);
        public readonly int3 xyx => new int3(x, y, x);
        public readonly int3 xyy => new int3(x, y, y);
        public int3 xyz { readonly get => new int3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
        public int3 xyw { readonly get => new int3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
        public readonly int3 xzx => new int3(x, z, x);
        public int3 xzy { readonly get => new int3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
        public readonly int3 xzz => new int3(x, z, z);
        public int3 xzw { readonly get => new int3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
        public readonly int3 xwx => new int3(x, w, x);
        public int3 xwy { readonly get => new int3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
        public int3 xwz { readonly get => new int3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
        public readonly int3 xww => new int3(x, w, w);
        public readonly int3 yxx => new int3(y, x, x);
        public readonly int3 yxy => new int3(y, x, y);
        public int3 yxz { readonly get => new int3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
        public int3 yxw { readonly get => new int3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
        public readonly int3 yyx => new int3(y, y, x);
        public readonly int3 yyy => new int3(y, y, y);
        public readonly int3 yyz => new int3(y, y, z);
        public readonly int3 yyw => new int3(y, y, w);
        public int3 yzx { readonly get => new int3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
        public readonly int3 yzy => new int3(y, z, y);
        public readonly int3 yzz => new int3(y, z, z);
        public int3 yzw { readonly get => new int3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
        public int3 ywx { readonly get => new int3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
        public readonly int3 ywy => new int3(y, w, y);
        public int3 ywz { readonly get => new int3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
        public readonly int3 yww => new int3(y, w, w);
        public readonly int3 zxx => new int3(z, x, x);
        public int3 zxy { readonly get => new int3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
        public readonly int3 zxz => new int3(z, x, z);
        public int3 zxw { readonly get => new int3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
        public int3 zyx { readonly get => new int3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
        public readonly int3 zyy => new int3(z, y, y);
        public readonly int3 zyz => new int3(z, y, z);
        public int3 zyw { readonly get => new int3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
        public readonly int3 zzx => new int3(z, z, x);
        public readonly int3 zzy => new int3(z, z, y);
        public readonly int3 zzz => new int3(z, z, z);
        public readonly int3 zzw => new int3(z, z, w);
        public int3 zwx { readonly get => new int3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
        public int3 zwy { readonly get => new int3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
        public readonly int3 zwz => new int3(z, w, z);
        public readonly int3 zww => new int3(z, w, w);
        public readonly int3 wxx => new int3(w, x, x);
        public int3 wxy { readonly get => new int3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
        public int3 wxz { readonly get => new int3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
        public readonly int3 wxw => new int3(w, x, w);
        public int3 wyx { readonly get => new int3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
        public readonly int3 wyy => new int3(w, y, y);
        public int3 wyz { readonly get => new int3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
        public readonly int3 wyw => new int3(w, y, w);
        public int3 wzx { readonly get => new int3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
        public int3 wzy { readonly get => new int3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
        public readonly int3 wzz => new int3(w, z, z);
        public readonly int3 wzw => new int3(w, z, w);
        public readonly int3 wwx => new int3(w, w, x);
        public readonly int3 wwy => new int3(w, w, y);
        public readonly int3 wwz => new int3(w, w, z);
        public readonly int3 www => new int3(w, w, w);
        public readonly int4 xxxx => new int4(x, x, x, x);
        public readonly int4 xxxy => new int4(x, x, x, y);
        public readonly int4 xxxz => new int4(x, x, x, z);
        public readonly int4 xxxw => new int4(x, x, x, w);
        public readonly int4 xxyx => new int4(x, x, y, x);
        public readonly int4 xxyy => new int4(x, x, y, y);
        public readonly int4 xxyz => new int4(x, x, y, z);
        public readonly int4 xxyw => new int4(x, x, y, w);
        public readonly int4 xxzx => new int4(x, x, z, x);
        public readonly int4 xxzy => new int4(x, x, z, y);
        public readonly int4 xxzz => new int4(x, x, z, z);
        public readonly int4 xxzw => new int4(x, x, z, w);
        public readonly int4 xxwx => new int4(x, x, w, x);
        public readonly int4 xxwy => new int4(x, x, w, y);
        public readonly int4 xxwz => new int4(x, x, w, z);
        public readonly int4 xxww => new int4(x, x, w, w);
        public readonly int4 xyxx => new int4(x, y, x, x);
        public readonly int4 xyxy => new int4(x, y, x, y);
        public readonly int4 xyxz => new int4(x, y, x, z);
        public readonly int4 xyxw => new int4(x, y, x, w);
        public readonly int4 xyyx => new int4(x, y, y, x);
        public readonly int4 xyyy => new int4(x, y, y, y);
        public readonly int4 xyyz => new int4(x, y, y, z);
        public readonly int4 xyyw => new int4(x, y, y, w);
        public readonly int4 xyzx => new int4(x, y, z, x);
        public readonly int4 xyzy => new int4(x, y, z, y);
        public readonly int4 xyzz => new int4(x, y, z, z);
        public int4 xyzw { readonly get => new int4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
        public readonly int4 xywx => new int4(x, y, w, x);
        public readonly int4 xywy => new int4(x, y, w, y);
        public int4 xywz { readonly get => new int4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
        public readonly int4 xyww => new int4(x, y, w, w);
        public readonly int4 xzxx => new int4(x, z, x, x);
        public readonly int4 xzxy => new int4(x, z, x, y);
        public readonly int4 xzxz => new int4(x, z, x, z);
        public readonly int4 xzxw => new int4(x, z, x, w);
        public readonly int4 xzyx => new int4(x, z, y, x);
        public readonly int4 xzyy => new int4(x, z, y, y);
        public readonly int4 xzyz => new int4(x, z, y, z);
        public int4 xzyw { readonly get => new int4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
        public readonly int4 xzzx => new int4(x, z, z, x);
        public readonly int4 xzzy => new int4(x, z, z, y);
        public readonly int4 xzzz => new int4(x, z, z, z);
        public readonly int4 xzzw => new int4(x, z, z, w);
        public readonly int4 xzwx => new int4(x, z, w, x);
        public int4 xzwy { readonly get => new int4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
        public readonly int4 xzwz => new int4(x, z, w, z);
        public readonly int4 xzww => new int4(x, z, w, w);
        public readonly int4 xwxx => new int4(x, w, x, x);
        public readonly int4 xwxy => new int4(x, w, x, y);
        public readonly int4 xwxz => new int4(x, w, x, z);
        public readonly int4 xwxw => new int4(x, w, x, w);
        public readonly int4 xwyx => new int4(x, w, y, x);
        public readonly int4 xwyy => new int4(x, w, y, y);
        public int4 xwyz { readonly get => new int4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
        public readonly int4 xwyw => new int4(x, w, y, w);
        public readonly int4 xwzx => new int4(x, w, z, x);
        public int4 xwzy { readonly get => new int4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
        public readonly int4 xwzz => new int4(x, w, z, z);
        public readonly int4 xwzw => new int4(x, w, z, w);
        public readonly int4 xwwx => new int4(x, w, w, x);
        public readonly int4 xwwy => new int4(x, w, w, y);
        public readonly int4 xwwz => new int4(x, w, w, z);
        public readonly int4 xwww => new int4(x, w, w, w);
        public readonly int4 yxxx => new int4(y, x, x, x);
        public readonly int4 yxxy => new int4(y, x, x, y);
        public readonly int4 yxxz => new int4(y, x, x, z);
        public readonly int4 yxxw => new int4(y, x, x, w);
        public readonly int4 yxyx => new int4(y, x, y, x);
        public readonly int4 yxyy => new int4(y, x, y, y);
        public readonly int4 yxyz => new int4(y, x, y, z);
        public readonly int4 yxyw => new int4(y, x, y, w);
        public readonly int4 yxzx => new int4(y, x, z, x);
        public readonly int4 yxzy => new int4(y, x, z, y);
        public readonly int4 yxzz => new int4(y, x, z, z);
        public int4 yxzw { readonly get => new int4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
        public readonly int4 yxwx => new int4(y, x, w, x);
        public readonly int4 yxwy => new int4(y, x, w, y);
        public int4 yxwz { readonly get => new int4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
        public readonly int4 yxww => new int4(y, x, w, w);
        public readonly int4 yyxx => new int4(y, y, x, x);
        public readonly int4 yyxy => new int4(y, y, x, y);
        public readonly int4 yyxz => new int4(y, y, x, z);
        public readonly int4 yyxw => new int4(y, y, x, w);
        public readonly int4 yyyx => new int4(y, y, y, x);
        public readonly int4 yyyy => new int4(y, y, y, y);
        public readonly int4 yyyz => new int4(y, y, y, z);
        public readonly int4 yyyw => new int4(y, y, y, w);
        public readonly int4 yyzx => new int4(y, y, z, x);
        public readonly int4 yyzy => new int4(y, y, z, y);
        public readonly int4 yyzz => new int4(y, y, z, z);
        public readonly int4 yyzw => new int4(y, y, z, w);
        public readonly int4 yywx => new int4(y, y, w, x);
        public readonly int4 yywy => new int4(y, y, w, y);
        public readonly int4 yywz => new int4(y, y, w, z);
        public readonly int4 yyww => new int4(y, y, w, w);
        public readonly int4 yzxx => new int4(y, z, x, x);
        public readonly int4 yzxy => new int4(y, z, x, y);
        public readonly int4 yzxz => new int4(y, z, x, z);
        public int4 yzxw { readonly get => new int4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
        public readonly int4 yzyx => new int4(y, z, y, x);
        public readonly int4 yzyy => new int4(y, z, y, y);
        public readonly int4 yzyz => new int4(y, z, y, z);
        public readonly int4 yzyw => new int4(y, z, y, w);
        public readonly int4 yzzx => new int4(y, z, z, x);
        public readonly int4 yzzy => new int4(y, z, z, y);
        public readonly int4 yzzz => new int4(y, z, z, z);
        public readonly int4 yzzw => new int4(y, z, z, w);
        public int4 yzwx { readonly get => new int4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
        public readonly int4 yzwy => new int4(y, z, w, y);
        public readonly int4 yzwz => new int4(y, z, w, z);
        public readonly int4 yzww => new int4(y, z, w, w);
        public readonly int4 ywxx => new int4(y, w, x, x);
        public readonly int4 ywxy => new int4(y, w, x, y);
        public int4 ywxz { readonly get => new int4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
        public readonly int4 ywxw => new int4(y, w, x, w);
        public readonly int4 ywyx => new int4(y, w, y, x);
        public readonly int4 ywyy => new int4(y, w, y, y);
        public readonly int4 ywyz => new int4(y, w, y, z);
        public readonly int4 ywyw => new int4(y, w, y, w);
        public int4 ywzx { readonly get => new int4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
        public readonly int4 ywzy => new int4(y, w, z, y);
        public readonly int4 ywzz => new int4(y, w, z, z);
        public readonly int4 ywzw => new int4(y, w, z, w);
        public readonly int4 ywwx => new int4(y, w, w, x);
        public readonly int4 ywwy => new int4(y, w, w, y);
        public readonly int4 ywwz => new int4(y, w, w, z);
        public readonly int4 ywww => new int4(y, w, w, w);
        public readonly int4 zxxx => new int4(z, x, x, x);
        public readonly int4 zxxy => new int4(z, x, x, y);
        public readonly int4 zxxz => new int4(z, x, x, z);
        public readonly int4 zxxw => new int4(z, x, x, w);
        public readonly int4 zxyx => new int4(z, x, y, x);
        public readonly int4 zxyy => new int4(z, x, y, y);
        public readonly int4 zxyz => new int4(z, x, y, z);
        public int4 zxyw { readonly get => new int4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
        public readonly int4 zxzx => new int4(z, x, z, x);
        public readonly int4 zxzy => new int4(z, x, z, y);
        public readonly int4 zxzz => new int4(z, x, z, z);
        public readonly int4 zxzw => new int4(z, x, z, w);
        public readonly int4 zxwx => new int4(z, x, w, x);
        public int4 zxwy { readonly get => new int4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
        public readonly int4 zxwz => new int4(z, x, w, z);
        public readonly int4 zxww => new int4(z, x, w, w);
        public readonly int4 zyxx => new int4(z, y, x, x);
        public readonly int4 zyxy => new int4(z, y, x, y);
        public readonly int4 zyxz => new int4(z, y, x, z);
        public int4 zyxw { readonly get => new int4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
        public readonly int4 zyyx => new int4(z, y, y, x);
        public readonly int4 zyyy => new int4(z, y, y, y);
        public readonly int4 zyyz => new int4(z, y, y, z);
        public readonly int4 zyyw => new int4(z, y, y, w);
        public readonly int4 zyzx => new int4(z, y, z, x);
        public readonly int4 zyzy => new int4(z, y, z, y);
        public readonly int4 zyzz => new int4(z, y, z, z);
        public readonly int4 zyzw => new int4(z, y, z, w);
        public int4 zywx { readonly get => new int4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
        public readonly int4 zywy => new int4(z, y, w, y);
        public readonly int4 zywz => new int4(z, y, w, z);
        public readonly int4 zyww => new int4(z, y, w, w);
        public readonly int4 zzxx => new int4(z, z, x, x);
        public readonly int4 zzxy => new int4(z, z, x, y);
        public readonly int4 zzxz => new int4(z, z, x, z);
        public readonly int4 zzxw => new int4(z, z, x, w);
        public readonly int4 zzyx => new int4(z, z, y, x);
        public readonly int4 zzyy => new int4(z, z, y, y);
        public readonly int4 zzyz => new int4(z, z, y, z);
        public readonly int4 zzyw => new int4(z, z, y, w);
        public readonly int4 zzzx => new int4(z, z, z, x);
        public readonly int4 zzzy => new int4(z, z, z, y);
        public readonly int4 zzzz => new int4(z, z, z, z);
        public readonly int4 zzzw => new int4(z, z, z, w);
        public readonly int4 zzwx => new int4(z, z, w, x);
        public readonly int4 zzwy => new int4(z, z, w, y);
        public readonly int4 zzwz => new int4(z, z, w, z);
        public readonly int4 zzww => new int4(z, z, w, w);
        public readonly int4 zwxx => new int4(z, w, x, x);
        public int4 zwxy { readonly get => new int4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
        public readonly int4 zwxz => new int4(z, w, x, z);
        public readonly int4 zwxw => new int4(z, w, x, w);
        public int4 zwyx { readonly get => new int4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
        public readonly int4 zwyy => new int4(z, w, y, y);
        public readonly int4 zwyz => new int4(z, w, y, z);
        public readonly int4 zwyw => new int4(z, w, y, w);
        public readonly int4 zwzx => new int4(z, w, z, x);
        public readonly int4 zwzy => new int4(z, w, z, y);
        public readonly int4 zwzz => new int4(z, w, z, z);
        public readonly int4 zwzw => new int4(z, w, z, w);
        public readonly int4 zwwx => new int4(z, w, w, x);
        public readonly int4 zwwy => new int4(z, w, w, y);
        public readonly int4 zwwz => new int4(z, w, w, z);
        public readonly int4 zwww => new int4(z, w, w, w);
        public readonly int4 wxxx => new int4(w, x, x, x);
        public readonly int4 wxxy => new int4(w, x, x, y);
        public readonly int4 wxxz => new int4(w, x, x, z);
        public readonly int4 wxxw => new int4(w, x, x, w);
        public readonly int4 wxyx => new int4(w, x, y, x);
        public readonly int4 wxyy => new int4(w, x, y, y);
        public int4 wxyz { readonly get => new int4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
        public readonly int4 wxyw => new int4(w, x, y, w);
        public readonly int4 wxzx => new int4(w, x, z, x);
        public int4 wxzy { readonly get => new int4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
        public readonly int4 wxzz => new int4(w, x, z, z);
        public readonly int4 wxzw => new int4(w, x, z, w);
        public readonly int4 wxwx => new int4(w, x, w, x);
        public readonly int4 wxwy => new int4(w, x, w, y);
        public readonly int4 wxwz => new int4(w, x, w, z);
        public readonly int4 wxww => new int4(w, x, w, w);
        public readonly int4 wyxx => new int4(w, y, x, x);
        public readonly int4 wyxy => new int4(w, y, x, y);
        public int4 wyxz { readonly get => new int4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
        public readonly int4 wyxw => new int4(w, y, x, w);
        public readonly int4 wyyx => new int4(w, y, y, x);
        public readonly int4 wyyy => new int4(w, y, y, y);
        public readonly int4 wyyz => new int4(w, y, y, z);
        public readonly int4 wyyw => new int4(w, y, y, w);
        public int4 wyzx { readonly get => new int4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
        public readonly int4 wyzy => new int4(w, y, z, y);
        public readonly int4 wyzz => new int4(w, y, z, z);
        public readonly int4 wyzw => new int4(w, y, z, w);
        public readonly int4 wywx => new int4(w, y, w, x);
        public readonly int4 wywy => new int4(w, y, w, y);
        public readonly int4 wywz => new int4(w, y, w, z);
        public readonly int4 wyww => new int4(w, y, w, w);
        public readonly int4 wzxx => new int4(w, z, x, x);
        public int4 wzxy { readonly get => new int4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
        public readonly int4 wzxz => new int4(w, z, x, z);
        public readonly int4 wzxw => new int4(w, z, x, w);
        public int4 wzyx { readonly get => new int4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
        public readonly int4 wzyy => new int4(w, z, y, y);
        public readonly int4 wzyz => new int4(w, z, y, z);
        public readonly int4 wzyw => new int4(w, z, y, w);
        public readonly int4 wzzx => new int4(w, z, z, x);
        public readonly int4 wzzy => new int4(w, z, z, y);
        public readonly int4 wzzz => new int4(w, z, z, z);
        public readonly int4 wzzw => new int4(w, z, z, w);
        public readonly int4 wzwx => new int4(w, z, w, x);
        public readonly int4 wzwy => new int4(w, z, w, y);
        public readonly int4 wzwz => new int4(w, z, w, z);
        public readonly int4 wzww => new int4(w, z, w, w);
        public readonly int4 wwxx => new int4(w, w, x, x);
        public readonly int4 wwxy => new int4(w, w, x, y);
        public readonly int4 wwxz => new int4(w, w, x, z);
        public readonly int4 wwxw => new int4(w, w, x, w);
        public readonly int4 wwyx => new int4(w, w, y, x);
        public readonly int4 wwyy => new int4(w, w, y, y);
        public readonly int4 wwyz => new int4(w, w, y, z);
        public readonly int4 wwyw => new int4(w, w, y, w);
        public readonly int4 wwzx => new int4(w, w, z, x);
        public readonly int4 wwzy => new int4(w, w, z, y);
        public readonly int4 wwzz => new int4(w, w, z, z);
        public readonly int4 wwzw => new int4(w, w, z, w);
        public readonly int4 wwwx => new int4(w, w, w, x);
        public readonly int4 wwwy => new int4(w, w, w, y);
        public readonly int4 wwwz => new int4(w, w, w, z);
        public readonly int4 wwww => new int4(w, w, w, w);
        public readonly bool Equals(int4 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y) && z.Equals(rhs.z) && w.Equals(rhs.w);
        public override readonly bool Equals(object o) => o is int4 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y, z, w);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "int4({0}, {1}, {2}, {3})", x, y, z, w);
        public readonly string ToString(string format, IFormatProvider formatProvider) => string.Format("int4({0}, {1}, {2}, {3})", x.ToString(format, formatProvider), y.ToString(format, formatProvider), z.ToString(format, formatProvider), w.ToString(format, formatProvider));
    }
}
