// <auto-generated>
// Generated by the port's math shim generator (first-party). Behavior-level re-implementation
// of the Unity.Mathematics public API surface the game compiles against; not vendored source.
// </auto-generated>
using System;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace Unity.Mathematics
{
    [Serializable]
    public partial struct uint2 : IEquatable<uint2>, IFormattable
    {
        public uint x;
        public uint y;
        public static readonly uint2 zero;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint2(uint x, uint y) { this.x = x; this.y = y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint2(uint2 xy) { this.x = xy.x; this.y = xy.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint2(uint v) { x = v; y = v; }
        public uint2(float v) { x = (uint)(v); y = (uint)(v); }
        public uint2(float2 v) { x = (uint)(v.x); y = (uint)(v.y); }
        public uint2(double v) { x = (uint)(v); y = (uint)(v); }
        public uint2(double2 v) { x = (uint)(v.x); y = (uint)(v.y); }
        public uint2(int v) { x = (uint)(v); y = (uint)(v); }
        public uint2(int2 v) { x = (uint)(v.x); y = (uint)(v.y); }
        public uint2(bool v) { x = (v ? 1u : 0u); y = (v ? 1u : 0u); }
        public uint2(bool2 v) { x = (v.x ? 1u : 0u); y = (v.y ? 1u : 0u); }
        public static implicit operator uint2(uint v) => new uint2(v);
        public static explicit operator uint2(float v) => new uint2(v);
        public static explicit operator uint2(float2 v) => new uint2(v);
        public static explicit operator uint2(double v) => new uint2(v);
        public static explicit operator uint2(double2 v) => new uint2(v);
        public static explicit operator uint2(int v) => new uint2(v);
        public static explicit operator uint2(int2 v) => new uint2(v);
        public static explicit operator uint2(bool v) => new uint2(v);
        public static explicit operator uint2(bool2 v) => new uint2(v);
        public static uint2 operator +(uint2 a, uint2 b) => new uint2(a.x + b.x, a.y + b.y);
        public static uint2 operator +(uint2 a, uint b) => new uint2(a.x + b, a.y + b);
        public static uint2 operator +(uint a, uint2 b) => new uint2(a + b.x, a + b.y);
        public static uint2 operator -(uint2 a, uint2 b) => new uint2(a.x - b.x, a.y - b.y);
        public static uint2 operator -(uint2 a, uint b) => new uint2(a.x - b, a.y - b);
        public static uint2 operator -(uint a, uint2 b) => new uint2(a - b.x, a - b.y);
        public static uint2 operator *(uint2 a, uint2 b) => new uint2(a.x * b.x, a.y * b.y);
        public static uint2 operator *(uint2 a, uint b) => new uint2(a.x * b, a.y * b);
        public static uint2 operator *(uint a, uint2 b) => new uint2(a * b.x, a * b.y);
        public static uint2 operator /(uint2 a, uint2 b) => new uint2(a.x / b.x, a.y / b.y);
        public static uint2 operator /(uint2 a, uint b) => new uint2(a.x / b, a.y / b);
        public static uint2 operator /(uint a, uint2 b) => new uint2(a / b.x, a / b.y);
        public static uint2 operator %(uint2 a, uint2 b) => new uint2(a.x % b.x, a.y % b.y);
        public static uint2 operator %(uint2 a, uint b) => new uint2(a.x % b, a.y % b);
        public static uint2 operator %(uint a, uint2 b) => new uint2(a % b.x, a % b.y);
        public static uint2 operator ++(uint2 v) => new uint2(v.x + 1u, v.y + 1u);
        public static uint2 operator --(uint2 v) => new uint2(v.x - 1u, v.y - 1u);
        public static uint2 operator +(uint2 v) => v;
        public static uint2 operator -(uint2 v) => new uint2((uint)-(int)v.x, (uint)-(int)v.y);
        public static bool2 operator <(uint2 a, uint2 b) => new bool2(a.x < b.x, a.y < b.y);
        public static bool2 operator <(uint2 a, uint b) => new bool2(a.x < b, a.y < b);
        public static bool2 operator <(uint a, uint2 b) => new bool2(a < b.x, a < b.y);
        public static bool2 operator <=(uint2 a, uint2 b) => new bool2(a.x <= b.x, a.y <= b.y);
        public static bool2 operator <=(uint2 a, uint b) => new bool2(a.x <= b, a.y <= b);
        public static bool2 operator <=(uint a, uint2 b) => new bool2(a <= b.x, a <= b.y);
        public static bool2 operator >(uint2 a, uint2 b) => new bool2(a.x > b.x, a.y > b.y);
        public static bool2 operator >(uint2 a, uint b) => new bool2(a.x > b, a.y > b);
        public static bool2 operator >(uint a, uint2 b) => new bool2(a > b.x, a > b.y);
        public static bool2 operator >=(uint2 a, uint2 b) => new bool2(a.x >= b.x, a.y >= b.y);
        public static bool2 operator >=(uint2 a, uint b) => new bool2(a.x >= b, a.y >= b);
        public static bool2 operator >=(uint a, uint2 b) => new bool2(a >= b.x, a >= b.y);
        public static bool2 operator ==(uint2 a, uint2 b) => new bool2(a.x == b.x, a.y == b.y);
        public static bool2 operator ==(uint2 a, uint b) => new bool2(a.x == b, a.y == b);
        public static bool2 operator ==(uint a, uint2 b) => new bool2(a == b.x, a == b.y);
        public static bool2 operator !=(uint2 a, uint2 b) => new bool2(a.x != b.x, a.y != b.y);
        public static bool2 operator !=(uint2 a, uint b) => new bool2(a.x != b, a.y != b);
        public static bool2 operator !=(uint a, uint2 b) => new bool2(a != b.x, a != b.y);
        public static uint2 operator &(uint2 a, uint2 b) => new uint2(a.x & b.x, a.y & b.y);
        public static uint2 operator &(uint2 a, uint b) => new uint2(a.x & b, a.y & b);
        public static uint2 operator &(uint a, uint2 b) => new uint2(a & b.x, a & b.y);
        public static uint2 operator |(uint2 a, uint2 b) => new uint2(a.x | b.x, a.y | b.y);
        public static uint2 operator |(uint2 a, uint b) => new uint2(a.x | b, a.y | b);
        public static uint2 operator |(uint a, uint2 b) => new uint2(a | b.x, a | b.y);
        public static uint2 operator ^(uint2 a, uint2 b) => new uint2(a.x ^ b.x, a.y ^ b.y);
        public static uint2 operator ^(uint2 a, uint b) => new uint2(a.x ^ b, a.y ^ b);
        public static uint2 operator ^(uint a, uint2 b) => new uint2(a ^ b.x, a ^ b.y);
        public static uint2 operator ~(uint2 v) => new uint2(~v.x, ~v.y);
        public static uint2 operator <<(uint2 v, int n) => new uint2(v.x << n, v.y << n);
        public static uint2 operator >>(uint2 v, int n) => new uint2(v.x >> n, v.y >> n);
        public uint this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly uint2 xx => new uint2(x, x);
        public uint2 xy { readonly get => new uint2(x, y); set { x = value.x; y = value.y; } }
        public uint2 yx { readonly get => new uint2(y, x); set { y = value.x; x = value.y; } }
        public readonly uint2 yy => new uint2(y, y);
        public readonly uint3 xxx => new uint3(x, x, x);
        public readonly uint3 xxy => new uint3(x, x, y);
        public readonly uint3 xyx => new uint3(x, y, x);
        public readonly uint3 xyy => new uint3(x, y, y);
        public readonly uint3 yxx => new uint3(y, x, x);
        public readonly uint3 yxy => new uint3(y, x, y);
        public readonly uint3 yyx => new uint3(y, y, x);
        public readonly uint3 yyy => new uint3(y, y, y);
        public readonly uint4 xxxx => new uint4(x, x, x, x);
        public readonly uint4 xxxy => new uint4(x, x, x, y);
        public readonly uint4 xxyx => new uint4(x, x, y, x);
        public readonly uint4 xxyy => new uint4(x, x, y, y);
        public readonly uint4 xyxx => new uint4(x, y, x, x);
        public readonly uint4 xyxy => new uint4(x, y, x, y);
        public readonly uint4 xyyx => new uint4(x, y, y, x);
        public readonly uint4 xyyy => new uint4(x, y, y, y);
        public readonly uint4 yxxx => new uint4(y, x, x, x);
        public readonly uint4 yxxy => new uint4(y, x, x, y);
        public readonly uint4 yxyx => new uint4(y, x, y, x);
        public readonly uint4 yxyy => new uint4(y, x, y, y);
        public readonly uint4 yyxx => new uint4(y, y, x, x);
        public readonly uint4 yyxy => new uint4(y, y, x, y);
        public readonly uint4 yyyx => new uint4(y, y, y, x);
        public readonly uint4 yyyy => new uint4(y, y, y, y);
        public readonly bool Equals(uint2 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y);
        public override readonly bool Equals(object o) => o is uint2 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "uint2({0}, {1})", x, y);
        public readonly string ToString(string format, IFormatProvider formatProvider) => string.Format("uint2({0}, {1})", x.ToString(format, formatProvider), y.ToString(format, formatProvider));
    }

    [Serializable]
    public partial struct uint3 : IEquatable<uint3>, IFormattable
    {
        public uint x;
        public uint y;
        public uint z;
        public static readonly uint3 zero;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint3(uint x, uint y, uint z) { this.x = x; this.y = y; this.z = z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint3(uint x, uint2 yz) { this.x = x; this.y = yz.x; this.z = yz.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint3(uint2 xy, uint z) { this.x = xy.x; this.y = xy.y; this.z = z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint3(uint3 xyz) { this.x = xyz.x; this.y = xyz.y; this.z = xyz.z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint3(uint v) { x = v; y = v; z = v; }
        public uint3(float v) { x = (uint)(v); y = (uint)(v); z = (uint)(v); }
        public uint3(float3 v) { x = (uint)(v.x); y = (uint)(v.y); z = (uint)(v.z); }
        public uint3(double v) { x = (uint)(v); y = (uint)(v); z = (uint)(v); }
        public uint3(double3 v) { x = (uint)(v.x); y = (uint)(v.y); z = (uint)(v.z); }
        public uint3(int v) { x = (uint)(v); y = (uint)(v); z = (uint)(v); }
        public uint3(int3 v) { x = (uint)(v.x); y = (uint)(v.y); z = (uint)(v.z); }
        public uint3(bool v) { x = (v ? 1u : 0u); y = (v ? 1u : 0u); z = (v ? 1u : 0u); }
        public uint3(bool3 v) { x = (v.x ? 1u : 0u); y = (v.y ? 1u : 0u); z = (v.z ? 1u : 0u); }
        public static implicit operator uint3(uint v) => new uint3(v);
        public static explicit operator uint3(float v) => new uint3(v);
        public static explicit operator uint3(float3 v) => new uint3(v);
        public static explicit operator uint3(double v) => new uint3(v);
        public static explicit operator uint3(double3 v) => new uint3(v);
        public static explicit operator uint3(int v) => new uint3(v);
        public static explicit operator uint3(int3 v) => new uint3(v);
        public static explicit operator uint3(bool v) => new uint3(v);
        public static explicit operator uint3(bool3 v) => new uint3(v);
        public static uint3 operator +(uint3 a, uint3 b) => new uint3(a.x + b.x, a.y + b.y, a.z + b.z);
        public static uint3 operator +(uint3 a, uint b) => new uint3(a.x + b, a.y + b, a.z + b);
        public static uint3 operator +(uint a, uint3 b) => new uint3(a + b.x, a + b.y, a + b.z);
        public static uint3 operator -(uint3 a, uint3 b) => new uint3(a.x - b.x, a.y - b.y, a.z - b.z);
        public static uint3 operator -(uint3 a, uint b) => new uint3(a.x - b, a.y - b, a.z - b);
        public static uint3 operator -(uint a, uint3 b) => new uint3(a - b.x, a - b.y, a - b.z);
        public static uint3 operator *(uint3 a, uint3 b) => new uint3(a.x * b.x, a.y * b.y, a.z * b.z);
        public static uint3 operator *(uint3 a, uint b) => new uint3(a.x * b, a.y * b, a.z * b);
        public static uint3 operator *(uint a, uint3 b) => new uint3(a * b.x, a * b.y, a * b.z);
        public static uint3 operator /(uint3 a, uint3 b) => new uint3(a.x / b.x, a.y / b.y, a.z / b.z);
        public static uint3 operator /(uint3 a, uint b) => new uint3(a.x / b, a.y / b, a.z / b);
        public static uint3 operator /(uint a, uint3 b) => new uint3(a / b.x, a / b.y, a / b.z);
        public static uint3 operator %(uint3 a, uint3 b) => new uint3(a.x % b.x, a.y % b.y, a.z % b.z);
        public static uint3 operator %(uint3 a, uint b) => new uint3(a.x % b, a.y % b, a.z % b);
        public static uint3 operator %(uint a, uint3 b) => new uint3(a % b.x, a % b.y, a % b.z);
        public static uint3 operator ++(uint3 v) => new uint3(v.x + 1u, v.y + 1u, v.z + 1u);
        public static uint3 operator --(uint3 v) => new uint3(v.x - 1u, v.y - 1u, v.z - 1u);
        public static uint3 operator +(uint3 v) => v;
        public static uint3 operator -(uint3 v) => new uint3((uint)-(int)v.x, (uint)-(int)v.y, (uint)-(int)v.z);
        public static bool3 operator <(uint3 a, uint3 b) => new bool3(a.x < b.x, a.y < b.y, a.z < b.z);
        public static bool3 operator <(uint3 a, uint b) => new bool3(a.x < b, a.y < b, a.z < b);
        public static bool3 operator <(uint a, uint3 b) => new bool3(a < b.x, a < b.y, a < b.z);
        public static bool3 operator <=(uint3 a, uint3 b) => new bool3(a.x <= b.x, a.y <= b.y, a.z <= b.z);
        public static bool3 operator <=(uint3 a, uint b) => new bool3(a.x <= b, a.y <= b, a.z <= b);
        public static bool3 operator <=(uint a, uint3 b) => new bool3(a <= b.x, a <= b.y, a <= b.z);
        public static bool3 operator >(uint3 a, uint3 b) => new bool3(a.x > b.x, a.y > b.y, a.z > b.z);
        public static bool3 operator >(uint3 a, uint b) => new bool3(a.x > b, a.y > b, a.z > b);
        public static bool3 operator >(uint a, uint3 b) => new bool3(a > b.x, a > b.y, a > b.z);
        public static bool3 operator >=(uint3 a, uint3 b) => new bool3(a.x >= b.x, a.y >= b.y, a.z >= b.z);
        public static bool3 operator >=(uint3 a, uint b) => new bool3(a.x >= b, a.y >= b, a.z >= b);
        public static bool3 operator >=(uint a, uint3 b) => new bool3(a >= b.x, a >= b.y, a >= b.z);
        public static bool3 operator ==(uint3 a, uint3 b) => new bool3(a.x == b.x, a.y == b.y, a.z == b.z);
        public static bool3 operator ==(uint3 a, uint b) => new bool3(a.x == b, a.y == b, a.z == b);
        public static bool3 operator ==(uint a, uint3 b) => new bool3(a == b.x, a == b.y, a == b.z);
        public static bool3 operator !=(uint3 a, uint3 b) => new bool3(a.x != b.x, a.y != b.y, a.z != b.z);
        public static bool3 operator !=(uint3 a, uint b) => new bool3(a.x != b, a.y != b, a.z != b);
        public static bool3 operator !=(uint a, uint3 b) => new bool3(a != b.x, a != b.y, a != b.z);
        public static uint3 operator &(uint3 a, uint3 b) => new uint3(a.x & b.x, a.y & b.y, a.z & b.z);
        public static uint3 operator &(uint3 a, uint b) => new uint3(a.x & b, a.y & b, a.z & b);
        public static uint3 operator &(uint a, uint3 b) => new uint3(a & b.x, a & b.y, a & b.z);
        public static uint3 operator |(uint3 a, uint3 b) => new uint3(a.x | b.x, a.y | b.y, a.z | b.z);
        public static uint3 operator |(uint3 a, uint b) => new uint3(a.x | b, a.y | b, a.z | b);
        public static uint3 operator |(uint a, uint3 b) => new uint3(a | b.x, a | b.y, a | b.z);
        public static uint3 operator ^(uint3 a, uint3 b) => new uint3(a.x ^ b.x, a.y ^ b.y, a.z ^ b.z);
        public static uint3 operator ^(uint3 a, uint b) => new uint3(a.x ^ b, a.y ^ b, a.z ^ b);
        public static uint3 operator ^(uint a, uint3 b) => new uint3(a ^ b.x, a ^ b.y, a ^ b.z);
        public static uint3 operator ~(uint3 v) => new uint3(~v.x, ~v.y, ~v.z);
        public static uint3 operator <<(uint3 v, int n) => new uint3(v.x << n, v.y << n, v.z << n);
        public static uint3 operator >>(uint3 v, int n) => new uint3(v.x >> n, v.y >> n, v.z >> n);
        public uint this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; case 2: return z; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly uint2 xx => new uint2(x, x);
        public uint2 xy { readonly get => new uint2(x, y); set { x = value.x; y = value.y; } }
        public uint2 xz { readonly get => new uint2(x, z); set { x = value.x; z = value.y; } }
        public uint2 yx { readonly get => new uint2(y, x); set { y = value.x; x = value.y; } }
        public readonly uint2 yy => new uint2(y, y);
        public uint2 yz { readonly get => new uint2(y, z); set { y = value.x; z = value.y; } }
        public uint2 zx { readonly get => new uint2(z, x); set { z = value.x; x = value.y; } }
        public uint2 zy { readonly get => new uint2(z, y); set { z = value.x; y = value.y; } }
        public readonly uint2 zz => new uint2(z, z);
        public readonly uint3 xxx => new uint3(x, x, x);
        public readonly uint3 xxy => new uint3(x, x, y);
        public readonly uint3 xxz => new uint3(x, x, z);
        public readonly uint3 xyx => new uint3(x, y, x);
        public readonly uint3 xyy => new uint3(x, y, y);
        public uint3 xyz { readonly get => new uint3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
        public readonly uint3 xzx => new uint3(x, z, x);
        public uint3 xzy { readonly get => new uint3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
        public readonly uint3 xzz => new uint3(x, z, z);
        public readonly uint3 yxx => new uint3(y, x, x);
        public readonly uint3 yxy => new uint3(y, x, y);
        public uint3 yxz { readonly get => new uint3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
        public readonly uint3 yyx => new uint3(y, y, x);
        public readonly uint3 yyy => new uint3(y, y, y);
        public readonly uint3 yyz => new uint3(y, y, z);
        public uint3 yzx { readonly get => new uint3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
        public readonly uint3 yzy => new uint3(y, z, y);
        public readonly uint3 yzz => new uint3(y, z, z);
        public readonly uint3 zxx => new uint3(z, x, x);
        public uint3 zxy { readonly get => new uint3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
        public readonly uint3 zxz => new uint3(z, x, z);
        public uint3 zyx { readonly get => new uint3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
        public readonly uint3 zyy => new uint3(z, y, y);
        public readonly uint3 zyz => new uint3(z, y, z);
        public readonly uint3 zzx => new uint3(z, z, x);
        public readonly uint3 zzy => new uint3(z, z, y);
        public readonly uint3 zzz => new uint3(z, z, z);
        public readonly uint4 xxxx => new uint4(x, x, x, x);
        public readonly uint4 xxxy => new uint4(x, x, x, y);
        public readonly uint4 xxxz => new uint4(x, x, x, z);
        public readonly uint4 xxyx => new uint4(x, x, y, x);
        public readonly uint4 xxyy => new uint4(x, x, y, y);
        public readonly uint4 xxyz => new uint4(x, x, y, z);
        public readonly uint4 xxzx => new uint4(x, x, z, x);
        public readonly uint4 xxzy => new uint4(x, x, z, y);
        public readonly uint4 xxzz => new uint4(x, x, z, z);
        public readonly uint4 xyxx => new uint4(x, y, x, x);
        public readonly uint4 xyxy => new uint4(x, y, x, y);
        public readonly uint4 xyxz => new uint4(x, y, x, z);
        public readonly uint4 xyyx => new uint4(x, y, y, x);
        public readonly uint4 xyyy => new uint4(x, y, y, y);
        public readonly uint4 xyyz => new uint4(x, y, y, z);
        public readonly uint4 xyzx => new uint4(x, y, z, x);
        public readonly uint4 xyzy => new uint4(x, y, z, y);
        public readonly uint4 xyzz => new uint4(x, y, z, z);
        public readonly uint4 xzxx => new uint4(x, z, x, x);
        public readonly uint4 xzxy => new uint4(x, z, x, y);
        public readonly uint4 xzxz => new uint4(x, z, x, z);
        public readonly uint4 xzyx => new uint4(x, z, y, x);
        public readonly uint4 xzyy => new uint4(x, z, y, y);
        public readonly uint4 xzyz => new uint4(x, z, y, z);
        public readonly uint4 xzzx => new uint4(x, z, z, x);
        public readonly uint4 xzzy => new uint4(x, z, z, y);
        public readonly uint4 xzzz => new uint4(x, z, z, z);
        public readonly uint4 yxxx => new uint4(y, x, x, x);
        public readonly uint4 yxxy => new uint4(y, x, x, y);
        public readonly uint4 yxxz => new uint4(y, x, x, z);
        public readonly uint4 yxyx => new uint4(y, x, y, x);
        public readonly uint4 yxyy => new uint4(y, x, y, y);
        public readonly uint4 yxyz => new uint4(y, x, y, z);
        public readonly uint4 yxzx => new uint4(y, x, z, x);
        public readonly uint4 yxzy => new uint4(y, x, z, y);
        public readonly uint4 yxzz => new uint4(y, x, z, z);
        public readonly uint4 yyxx => new uint4(y, y, x, x);
        public readonly uint4 yyxy => new uint4(y, y, x, y);
        public readonly uint4 yyxz => new uint4(y, y, x, z);
        public readonly uint4 yyyx => new uint4(y, y, y, x);
        public readonly uint4 yyyy => new uint4(y, y, y, y);
        public readonly uint4 yyyz => new uint4(y, y, y, z);
        public readonly uint4 yyzx => new uint4(y, y, z, x);
        public readonly uint4 yyzy => new uint4(y, y, z, y);
        public readonly uint4 yyzz => new uint4(y, y, z, z);
        public readonly uint4 yzxx => new uint4(y, z, x, x);
        public readonly uint4 yzxy => new uint4(y, z, x, y);
        public readonly uint4 yzxz => new uint4(y, z, x, z);
        public readonly uint4 yzyx => new uint4(y, z, y, x);
        public readonly uint4 yzyy => new uint4(y, z, y, y);
        public readonly uint4 yzyz => new uint4(y, z, y, z);
        public readonly uint4 yzzx => new uint4(y, z, z, x);
        public readonly uint4 yzzy => new uint4(y, z, z, y);
        public readonly uint4 yzzz => new uint4(y, z, z, z);
        public readonly uint4 zxxx => new uint4(z, x, x, x);
        public readonly uint4 zxxy => new uint4(z, x, x, y);
        public readonly uint4 zxxz => new uint4(z, x, x, z);
        public readonly uint4 zxyx => new uint4(z, x, y, x);
        public readonly uint4 zxyy => new uint4(z, x, y, y);
        public readonly uint4 zxyz => new uint4(z, x, y, z);
        public readonly uint4 zxzx => new uint4(z, x, z, x);
        public readonly uint4 zxzy => new uint4(z, x, z, y);
        public readonly uint4 zxzz => new uint4(z, x, z, z);
        public readonly uint4 zyxx => new uint4(z, y, x, x);
        public readonly uint4 zyxy => new uint4(z, y, x, y);
        public readonly uint4 zyxz => new uint4(z, y, x, z);
        public readonly uint4 zyyx => new uint4(z, y, y, x);
        public readonly uint4 zyyy => new uint4(z, y, y, y);
        public readonly uint4 zyyz => new uint4(z, y, y, z);
        public readonly uint4 zyzx => new uint4(z, y, z, x);
        public readonly uint4 zyzy => new uint4(z, y, z, y);
        public readonly uint4 zyzz => new uint4(z, y, z, z);
        public readonly uint4 zzxx => new uint4(z, z, x, x);
        public readonly uint4 zzxy => new uint4(z, z, x, y);
        public readonly uint4 zzxz => new uint4(z, z, x, z);
        public readonly uint4 zzyx => new uint4(z, z, y, x);
        public readonly uint4 zzyy => new uint4(z, z, y, y);
        public readonly uint4 zzyz => new uint4(z, z, y, z);
        public readonly uint4 zzzx => new uint4(z, z, z, x);
        public readonly uint4 zzzy => new uint4(z, z, z, y);
        public readonly uint4 zzzz => new uint4(z, z, z, z);
        public readonly bool Equals(uint3 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y) && z.Equals(rhs.z);
        public override readonly bool Equals(object o) => o is uint3 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y, z);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "uint3({0}, {1}, {2})", x, y, z);
        public readonly string ToString(string format, IFormatProvider formatProvider) => string.Format("uint3({0}, {1}, {2})", x.ToString(format, formatProvider), y.ToString(format, formatProvider), z.ToString(format, formatProvider));
    }

    [Serializable]
    public partial struct uint4 : IEquatable<uint4>, IFormattable
    {
        public uint x;
        public uint y;
        public uint z;
        public uint w;
        public static readonly uint4 zero;
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint4(uint x, uint y, uint z, uint w) { this.x = x; this.y = y; this.z = z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint4(uint x, uint y, uint2 zw) { this.x = x; this.y = y; this.z = zw.x; this.w = zw.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint4(uint x, uint2 yz, uint w) { this.x = x; this.y = yz.x; this.z = yz.y; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint4(uint x, uint3 yzw) { this.x = x; this.y = yzw.x; this.z = yzw.y; this.w = yzw.z; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint4(uint2 xy, uint z, uint w) { this.x = xy.x; this.y = xy.y; this.z = z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint4(uint2 xy, uint2 zw) { this.x = xy.x; this.y = xy.y; this.z = zw.x; this.w = zw.y; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint4(uint3 xyz, uint w) { this.x = xyz.x; this.y = xyz.y; this.z = xyz.z; this.w = w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint4(uint4 xyzw) { this.x = xyzw.x; this.y = xyzw.y; this.z = xyzw.z; this.w = xyzw.w; }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public uint4(uint v) { x = v; y = v; z = v; w = v; }
        public uint4(float v) { x = (uint)(v); y = (uint)(v); z = (uint)(v); w = (uint)(v); }
        public uint4(float4 v) { x = (uint)(v.x); y = (uint)(v.y); z = (uint)(v.z); w = (uint)(v.w); }
        public uint4(double v) { x = (uint)(v); y = (uint)(v); z = (uint)(v); w = (uint)(v); }
        public uint4(double4 v) { x = (uint)(v.x); y = (uint)(v.y); z = (uint)(v.z); w = (uint)(v.w); }
        public uint4(int v) { x = (uint)(v); y = (uint)(v); z = (uint)(v); w = (uint)(v); }
        public uint4(int4 v) { x = (uint)(v.x); y = (uint)(v.y); z = (uint)(v.z); w = (uint)(v.w); }
        public uint4(bool v) { x = (v ? 1u : 0u); y = (v ? 1u : 0u); z = (v ? 1u : 0u); w = (v ? 1u : 0u); }
        public uint4(bool4 v) { x = (v.x ? 1u : 0u); y = (v.y ? 1u : 0u); z = (v.z ? 1u : 0u); w = (v.w ? 1u : 0u); }
        public static implicit operator uint4(uint v) => new uint4(v);
        public static explicit operator uint4(float v) => new uint4(v);
        public static explicit operator uint4(float4 v) => new uint4(v);
        public static explicit operator uint4(double v) => new uint4(v);
        public static explicit operator uint4(double4 v) => new uint4(v);
        public static explicit operator uint4(int v) => new uint4(v);
        public static explicit operator uint4(int4 v) => new uint4(v);
        public static explicit operator uint4(bool v) => new uint4(v);
        public static explicit operator uint4(bool4 v) => new uint4(v);
        public static uint4 operator +(uint4 a, uint4 b) => new uint4(a.x + b.x, a.y + b.y, a.z + b.z, a.w + b.w);
        public static uint4 operator +(uint4 a, uint b) => new uint4(a.x + b, a.y + b, a.z + b, a.w + b);
        public static uint4 operator +(uint a, uint4 b) => new uint4(a + b.x, a + b.y, a + b.z, a + b.w);
        public static uint4 operator -(uint4 a, uint4 b) => new uint4(a.x - b.x, a.y - b.y, a.z - b.z, a.w - b.w);
        public static uint4 operator -(uint4 a, uint b) => new uint4(a.x - b, a.y - b, a.z - b, a.w - b);
        public static uint4 operator -(uint a, uint4 b) => new uint4(a - b.x, a - b.y, a - b.z, a - b.w);
        public static uint4 operator *(uint4 a, uint4 b) => new uint4(a.x * b.x, a.y * b.y, a.z * b.z, a.w * b.w);
        public static uint4 operator *(uint4 a, uint b) => new uint4(a.x * b, a.y * b, a.z * b, a.w * b);
        public static uint4 operator *(uint a, uint4 b) => new uint4(a * b.x, a * b.y, a * b.z, a * b.w);
        public static uint4 operator /(uint4 a, uint4 b) => new uint4(a.x / b.x, a.y / b.y, a.z / b.z, a.w / b.w);
        public static uint4 operator /(uint4 a, uint b) => new uint4(a.x / b, a.y / b, a.z / b, a.w / b);
        public static uint4 operator /(uint a, uint4 b) => new uint4(a / b.x, a / b.y, a / b.z, a / b.w);
        public static uint4 operator %(uint4 a, uint4 b) => new uint4(a.x % b.x, a.y % b.y, a.z % b.z, a.w % b.w);
        public static uint4 operator %(uint4 a, uint b) => new uint4(a.x % b, a.y % b, a.z % b, a.w % b);
        public static uint4 operator %(uint a, uint4 b) => new uint4(a % b.x, a % b.y, a % b.z, a % b.w);
        public static uint4 operator ++(uint4 v) => new uint4(v.x + 1u, v.y + 1u, v.z + 1u, v.w + 1u);
        public static uint4 operator --(uint4 v) => new uint4(v.x - 1u, v.y - 1u, v.z - 1u, v.w - 1u);
        public static uint4 operator +(uint4 v) => v;
        public static uint4 operator -(uint4 v) => new uint4((uint)-(int)v.x, (uint)-(int)v.y, (uint)-(int)v.z, (uint)-(int)v.w);
        public static bool4 operator <(uint4 a, uint4 b) => new bool4(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
        public static bool4 operator <(uint4 a, uint b) => new bool4(a.x < b, a.y < b, a.z < b, a.w < b);
        public static bool4 operator <(uint a, uint4 b) => new bool4(a < b.x, a < b.y, a < b.z, a < b.w);
        public static bool4 operator <=(uint4 a, uint4 b) => new bool4(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
        public static bool4 operator <=(uint4 a, uint b) => new bool4(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
        public static bool4 operator <=(uint a, uint4 b) => new bool4(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
        public static bool4 operator >(uint4 a, uint4 b) => new bool4(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
        public static bool4 operator >(uint4 a, uint b) => new bool4(a.x > b, a.y > b, a.z > b, a.w > b);
        public static bool4 operator >(uint a, uint4 b) => new bool4(a > b.x, a > b.y, a > b.z, a > b.w);
        public static bool4 operator >=(uint4 a, uint4 b) => new bool4(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
        public static bool4 operator >=(uint4 a, uint b) => new bool4(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
        public static bool4 operator >=(uint a, uint4 b) => new bool4(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
        public static bool4 operator ==(uint4 a, uint4 b) => new bool4(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
        public static bool4 operator ==(uint4 a, uint b) => new bool4(a.x == b, a.y == b, a.z == b, a.w == b);
        public static bool4 operator ==(uint a, uint4 b) => new bool4(a == b.x, a == b.y, a == b.z, a == b.w);
        public static bool4 operator !=(uint4 a, uint4 b) => new bool4(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
        public static bool4 operator !=(uint4 a, uint b) => new bool4(a.x != b, a.y != b, a.z != b, a.w != b);
        public static bool4 operator !=(uint a, uint4 b) => new bool4(a != b.x, a != b.y, a != b.z, a != b.w);
        public static uint4 operator &(uint4 a, uint4 b) => new uint4(a.x & b.x, a.y & b.y, a.z & b.z, a.w & b.w);
        public static uint4 operator &(uint4 a, uint b) => new uint4(a.x & b, a.y & b, a.z & b, a.w & b);
        public static uint4 operator &(uint a, uint4 b) => new uint4(a & b.x, a & b.y, a & b.z, a & b.w);
        public static uint4 operator |(uint4 a, uint4 b) => new uint4(a.x | b.x, a.y | b.y, a.z | b.z, a.w | b.w);
        public static uint4 operator |(uint4 a, uint b) => new uint4(a.x | b, a.y | b, a.z | b, a.w | b);
        public static uint4 operator |(uint a, uint4 b) => new uint4(a | b.x, a | b.y, a | b.z, a | b.w);
        public static uint4 operator ^(uint4 a, uint4 b) => new uint4(a.x ^ b.x, a.y ^ b.y, a.z ^ b.z, a.w ^ b.w);
        public static uint4 operator ^(uint4 a, uint b) => new uint4(a.x ^ b, a.y ^ b, a.z ^ b, a.w ^ b);
        public static uint4 operator ^(uint a, uint4 b) => new uint4(a ^ b.x, a ^ b.y, a ^ b.z, a ^ b.w);
        public static uint4 operator ~(uint4 v) => new uint4(~v.x, ~v.y, ~v.z, ~v.w);
        public static uint4 operator <<(uint4 v, int n) => new uint4(v.x << n, v.y << n, v.z << n, v.w << n);
        public static uint4 operator >>(uint4 v, int n) => new uint4(v.x >> n, v.y >> n, v.z >> n, v.w >> n);
        public uint this[int index]
        {
            get { switch (index) { case 0: return x; case 1: return y; case 2: return z; case 3: return w; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
            set { switch (index) { case 0: x = value; break; case 1: y = value; break; case 2: z = value; break; case 3: w = value; break; default: throw new ArgumentOutOfRangeException(nameof(index)); } }
        }
        public readonly uint2 xx => new uint2(x, x);
        public uint2 xy { readonly get => new uint2(x, y); set { x = value.x; y = value.y; } }
        public uint2 xz { readonly get => new uint2(x, z); set { x = value.x; z = value.y; } }
        public uint2 xw { readonly get => new uint2(x, w); set { x = value.x; w = value.y; } }
        public uint2 yx { readonly get => new uint2(y, x); set { y = value.x; x = value.y; } }
        public readonly uint2 yy => new uint2(y, y);
        public uint2 yz { readonly get => new uint2(y, z); set { y = value.x; z = value.y; } }
        public uint2 yw { readonly get => new uint2(y, w); set { y = value.x; w = value.y; } }
        public uint2 zx { readonly get => new uint2(z, x); set { z = value.x; x = value.y; } }
        public uint2 zy { readonly get => new uint2(z, y); set { z = value.x; y = value.y; } }
        public readonly uint2 zz => new uint2(z, z);
        public uint2 zw { readonly get => new uint2(z, w); set { z = value.x; w = value.y; } }
        public uint2 wx { readonly get => new uint2(w, x); set { w = value.x; x = value.y; } }
        public uint2 wy { readonly get => new uint2(w, y); set { w = value.x; y = value.y; } }
        public uint2 wz { readonly get => new uint2(w, z); set { w = value.x; z = value.y; } }
        public readonly uint2 ww => new uint2(w, w);
        public readonly uint3 xxx => new uint3(x, x, x);
        public readonly uint3 xxy => new uint3(x, x, y);
        public readonly uint3 xxz => new uint3(x, x, z);
        public readonly uint3 xxw => new uint3(x, x, w);
        public readonly uint3 xyx => new uint3(x, y, x);
        public readonly uint3 xyy => new uint3(x, y, y);
        public uint3 xyz { readonly get => new uint3(x, y, z); set { x = value.x; y = value.y; z = value.z; } }
        public uint3 xyw { readonly get => new uint3(x, y, w); set { x = value.x; y = value.y; w = value.z; } }
        public readonly uint3 xzx => new uint3(x, z, x);
        public uint3 xzy { readonly get => new uint3(x, z, y); set { x = value.x; z = value.y; y = value.z; } }
        public readonly uint3 xzz => new uint3(x, z, z);
        public uint3 xzw { readonly get => new uint3(x, z, w); set { x = value.x; z = value.y; w = value.z; } }
        public readonly uint3 xwx => new uint3(x, w, x);
        public uint3 xwy { readonly get => new uint3(x, w, y); set { x = value.x; w = value.y; y = value.z; } }
        public uint3 xwz { readonly get => new uint3(x, w, z); set { x = value.x; w = value.y; z = value.z; } }
        public readonly uint3 xww => new uint3(x, w, w);
        public readonly uint3 yxx => new uint3(y, x, x);
        public readonly uint3 yxy => new uint3(y, x, y);
        public uint3 yxz { readonly get => new uint3(y, x, z); set { y = value.x; x = value.y; z = value.z; } }
        public uint3 yxw { readonly get => new uint3(y, x, w); set { y = value.x; x = value.y; w = value.z; } }
        public readonly uint3 yyx => new uint3(y, y, x);
        public readonly uint3 yyy => new uint3(y, y, y);
        public readonly uint3 yyz => new uint3(y, y, z);
        public readonly uint3 yyw => new uint3(y, y, w);
        public uint3 yzx { readonly get => new uint3(y, z, x); set { y = value.x; z = value.y; x = value.z; } }
        public readonly uint3 yzy => new uint3(y, z, y);
        public readonly uint3 yzz => new uint3(y, z, z);
        public uint3 yzw { readonly get => new uint3(y, z, w); set { y = value.x; z = value.y; w = value.z; } }
        public uint3 ywx { readonly get => new uint3(y, w, x); set { y = value.x; w = value.y; x = value.z; } }
        public readonly uint3 ywy => new uint3(y, w, y);
        public uint3 ywz { readonly get => new uint3(y, w, z); set { y = value.x; w = value.y; z = value.z; } }
        public readonly uint3 yww => new uint3(y, w, w);
        public readonly uint3 zxx => new uint3(z, x, x);
        public uint3 zxy { readonly get => new uint3(z, x, y); set { z = value.x; x = value.y; y = value.z; } }
        public readonly uint3 zxz => new uint3(z, x, z);
        public uint3 zxw { readonly get => new uint3(z, x, w); set { z = value.x; x = value.y; w = value.z; } }
        public uint3 zyx { readonly get => new uint3(z, y, x); set { z = value.x; y = value.y; x = value.z; } }
        public readonly uint3 zyy => new uint3(z, y, y);
        public readonly uint3 zyz => new uint3(z, y, z);
        public uint3 zyw { readonly get => new uint3(z, y, w); set { z = value.x; y = value.y; w = value.z; } }
        public readonly uint3 zzx => new uint3(z, z, x);
        public readonly uint3 zzy => new uint3(z, z, y);
        public readonly uint3 zzz => new uint3(z, z, z);
        public readonly uint3 zzw => new uint3(z, z, w);
        public uint3 zwx { readonly get => new uint3(z, w, x); set { z = value.x; w = value.y; x = value.z; } }
        public uint3 zwy { readonly get => new uint3(z, w, y); set { z = value.x; w = value.y; y = value.z; } }
        public readonly uint3 zwz => new uint3(z, w, z);
        public readonly uint3 zww => new uint3(z, w, w);
        public readonly uint3 wxx => new uint3(w, x, x);
        public uint3 wxy { readonly get => new uint3(w, x, y); set { w = value.x; x = value.y; y = value.z; } }
        public uint3 wxz { readonly get => new uint3(w, x, z); set { w = value.x; x = value.y; z = value.z; } }
        public readonly uint3 wxw => new uint3(w, x, w);
        public uint3 wyx { readonly get => new uint3(w, y, x); set { w = value.x; y = value.y; x = value.z; } }
        public readonly uint3 wyy => new uint3(w, y, y);
        public uint3 wyz { readonly get => new uint3(w, y, z); set { w = value.x; y = value.y; z = value.z; } }
        public readonly uint3 wyw => new uint3(w, y, w);
        public uint3 wzx { readonly get => new uint3(w, z, x); set { w = value.x; z = value.y; x = value.z; } }
        public uint3 wzy { readonly get => new uint3(w, z, y); set { w = value.x; z = value.y; y = value.z; } }
        public readonly uint3 wzz => new uint3(w, z, z);
        public readonly uint3 wzw => new uint3(w, z, w);
        public readonly uint3 wwx => new uint3(w, w, x);
        public readonly uint3 wwy => new uint3(w, w, y);
        public readonly uint3 wwz => new uint3(w, w, z);
        public readonly uint3 www => new uint3(w, w, w);
        public readonly uint4 xxxx => new uint4(x, x, x, x);
        public readonly uint4 xxxy => new uint4(x, x, x, y);
        public readonly uint4 xxxz => new uint4(x, x, x, z);
        public readonly uint4 xxxw => new uint4(x, x, x, w);
        public readonly uint4 xxyx => new uint4(x, x, y, x);
        public readonly uint4 xxyy => new uint4(x, x, y, y);
        public readonly uint4 xxyz => new uint4(x, x, y, z);
        public readonly uint4 xxyw => new uint4(x, x, y, w);
        public readonly uint4 xxzx => new uint4(x, x, z, x);
        public readonly uint4 xxzy => new uint4(x, x, z, y);
        public readonly uint4 xxzz => new uint4(x, x, z, z);
        public readonly uint4 xxzw => new uint4(x, x, z, w);
        public readonly uint4 xxwx => new uint4(x, x, w, x);
        public readonly uint4 xxwy => new uint4(x, x, w, y);
        public readonly uint4 xxwz => new uint4(x, x, w, z);
        public readonly uint4 xxww => new uint4(x, x, w, w);
        public readonly uint4 xyxx => new uint4(x, y, x, x);
        public readonly uint4 xyxy => new uint4(x, y, x, y);
        public readonly uint4 xyxz => new uint4(x, y, x, z);
        public readonly uint4 xyxw => new uint4(x, y, x, w);
        public readonly uint4 xyyx => new uint4(x, y, y, x);
        public readonly uint4 xyyy => new uint4(x, y, y, y);
        public readonly uint4 xyyz => new uint4(x, y, y, z);
        public readonly uint4 xyyw => new uint4(x, y, y, w);
        public readonly uint4 xyzx => new uint4(x, y, z, x);
        public readonly uint4 xyzy => new uint4(x, y, z, y);
        public readonly uint4 xyzz => new uint4(x, y, z, z);
        public uint4 xyzw { readonly get => new uint4(x, y, z, w); set { x = value.x; y = value.y; z = value.z; w = value.w; } }
        public readonly uint4 xywx => new uint4(x, y, w, x);
        public readonly uint4 xywy => new uint4(x, y, w, y);
        public uint4 xywz { readonly get => new uint4(x, y, w, z); set { x = value.x; y = value.y; w = value.z; z = value.w; } }
        public readonly uint4 xyww => new uint4(x, y, w, w);
        public readonly uint4 xzxx => new uint4(x, z, x, x);
        public readonly uint4 xzxy => new uint4(x, z, x, y);
        public readonly uint4 xzxz => new uint4(x, z, x, z);
        public readonly uint4 xzxw => new uint4(x, z, x, w);
        public readonly uint4 xzyx => new uint4(x, z, y, x);
        public readonly uint4 xzyy => new uint4(x, z, y, y);
        public readonly uint4 xzyz => new uint4(x, z, y, z);
        public uint4 xzyw { readonly get => new uint4(x, z, y, w); set { x = value.x; z = value.y; y = value.z; w = value.w; } }
        public readonly uint4 xzzx => new uint4(x, z, z, x);
        public readonly uint4 xzzy => new uint4(x, z, z, y);
        public readonly uint4 xzzz => new uint4(x, z, z, z);
        public readonly uint4 xzzw => new uint4(x, z, z, w);
        public readonly uint4 xzwx => new uint4(x, z, w, x);
        public uint4 xzwy { readonly get => new uint4(x, z, w, y); set { x = value.x; z = value.y; w = value.z; y = value.w; } }
        public readonly uint4 xzwz => new uint4(x, z, w, z);
        public readonly uint4 xzww => new uint4(x, z, w, w);
        public readonly uint4 xwxx => new uint4(x, w, x, x);
        public readonly uint4 xwxy => new uint4(x, w, x, y);
        public readonly uint4 xwxz => new uint4(x, w, x, z);
        public readonly uint4 xwxw => new uint4(x, w, x, w);
        public readonly uint4 xwyx => new uint4(x, w, y, x);
        public readonly uint4 xwyy => new uint4(x, w, y, y);
        public uint4 xwyz { readonly get => new uint4(x, w, y, z); set { x = value.x; w = value.y; y = value.z; z = value.w; } }
        public readonly uint4 xwyw => new uint4(x, w, y, w);
        public readonly uint4 xwzx => new uint4(x, w, z, x);
        public uint4 xwzy { readonly get => new uint4(x, w, z, y); set { x = value.x; w = value.y; z = value.z; y = value.w; } }
        public readonly uint4 xwzz => new uint4(x, w, z, z);
        public readonly uint4 xwzw => new uint4(x, w, z, w);
        public readonly uint4 xwwx => new uint4(x, w, w, x);
        public readonly uint4 xwwy => new uint4(x, w, w, y);
        public readonly uint4 xwwz => new uint4(x, w, w, z);
        public readonly uint4 xwww => new uint4(x, w, w, w);
        public readonly uint4 yxxx => new uint4(y, x, x, x);
        public readonly uint4 yxxy => new uint4(y, x, x, y);
        public readonly uint4 yxxz => new uint4(y, x, x, z);
        public readonly uint4 yxxw => new uint4(y, x, x, w);
        public readonly uint4 yxyx => new uint4(y, x, y, x);
        public readonly uint4 yxyy => new uint4(y, x, y, y);
        public readonly uint4 yxyz => new uint4(y, x, y, z);
        public readonly uint4 yxyw => new uint4(y, x, y, w);
        public readonly uint4 yxzx => new uint4(y, x, z, x);
        public readonly uint4 yxzy => new uint4(y, x, z, y);
        public readonly uint4 yxzz => new uint4(y, x, z, z);
        public uint4 yxzw { readonly get => new uint4(y, x, z, w); set { y = value.x; x = value.y; z = value.z; w = value.w; } }
        public readonly uint4 yxwx => new uint4(y, x, w, x);
        public readonly uint4 yxwy => new uint4(y, x, w, y);
        public uint4 yxwz { readonly get => new uint4(y, x, w, z); set { y = value.x; x = value.y; w = value.z; z = value.w; } }
        public readonly uint4 yxww => new uint4(y, x, w, w);
        public readonly uint4 yyxx => new uint4(y, y, x, x);
        public readonly uint4 yyxy => new uint4(y, y, x, y);
        public readonly uint4 yyxz => new uint4(y, y, x, z);
        public readonly uint4 yyxw => new uint4(y, y, x, w);
        public readonly uint4 yyyx => new uint4(y, y, y, x);
        public readonly uint4 yyyy => new uint4(y, y, y, y);
        public readonly uint4 yyyz => new uint4(y, y, y, z);
        public readonly uint4 yyyw => new uint4(y, y, y, w);
        public readonly uint4 yyzx => new uint4(y, y, z, x);
        public readonly uint4 yyzy => new uint4(y, y, z, y);
        public readonly uint4 yyzz => new uint4(y, y, z, z);
        public readonly uint4 yyzw => new uint4(y, y, z, w);
        public readonly uint4 yywx => new uint4(y, y, w, x);
        public readonly uint4 yywy => new uint4(y, y, w, y);
        public readonly uint4 yywz => new uint4(y, y, w, z);
        public readonly uint4 yyww => new uint4(y, y, w, w);
        public readonly uint4 yzxx => new uint4(y, z, x, x);
        public readonly uint4 yzxy => new uint4(y, z, x, y);
        public readonly uint4 yzxz => new uint4(y, z, x, z);
        public uint4 yzxw { readonly get => new uint4(y, z, x, w); set { y = value.x; z = value.y; x = value.z; w = value.w; } }
        public readonly uint4 yzyx => new uint4(y, z, y, x);
        public readonly uint4 yzyy => new uint4(y, z, y, y);
        public readonly uint4 yzyz => new uint4(y, z, y, z);
        public readonly uint4 yzyw => new uint4(y, z, y, w);
        public readonly uint4 yzzx => new uint4(y, z, z, x);
        public readonly uint4 yzzy => new uint4(y, z, z, y);
        public readonly uint4 yzzz => new uint4(y, z, z, z);
        public readonly uint4 yzzw => new uint4(y, z, z, w);
        public uint4 yzwx { readonly get => new uint4(y, z, w, x); set { y = value.x; z = value.y; w = value.z; x = value.w; } }
        public readonly uint4 yzwy => new uint4(y, z, w, y);
        public readonly uint4 yzwz => new uint4(y, z, w, z);
        public readonly uint4 yzww => new uint4(y, z, w, w);
        public readonly uint4 ywxx => new uint4(y, w, x, x);
        public readonly uint4 ywxy => new uint4(y, w, x, y);
        public uint4 ywxz { readonly get => new uint4(y, w, x, z); set { y = value.x; w = value.y; x = value.z; z = value.w; } }
        public readonly uint4 ywxw => new uint4(y, w, x, w);
        public readonly uint4 ywyx => new uint4(y, w, y, x);
        public readonly uint4 ywyy => new uint4(y, w, y, y);
        public readonly uint4 ywyz => new uint4(y, w, y, z);
        public readonly uint4 ywyw => new uint4(y, w, y, w);
        public uint4 ywzx { readonly get => new uint4(y, w, z, x); set { y = value.x; w = value.y; z = value.z; x = value.w; } }
        public readonly uint4 ywzy => new uint4(y, w, z, y);
        public readonly uint4 ywzz => new uint4(y, w, z, z);
        public readonly uint4 ywzw => new uint4(y, w, z, w);
        public readonly uint4 ywwx => new uint4(y, w, w, x);
        public readonly uint4 ywwy => new uint4(y, w, w, y);
        public readonly uint4 ywwz => new uint4(y, w, w, z);
        public readonly uint4 ywww => new uint4(y, w, w, w);
        public readonly uint4 zxxx => new uint4(z, x, x, x);
        public readonly uint4 zxxy => new uint4(z, x, x, y);
        public readonly uint4 zxxz => new uint4(z, x, x, z);
        public readonly uint4 zxxw => new uint4(z, x, x, w);
        public readonly uint4 zxyx => new uint4(z, x, y, x);
        public readonly uint4 zxyy => new uint4(z, x, y, y);
        public readonly uint4 zxyz => new uint4(z, x, y, z);
        public uint4 zxyw { readonly get => new uint4(z, x, y, w); set { z = value.x; x = value.y; y = value.z; w = value.w; } }
        public readonly uint4 zxzx => new uint4(z, x, z, x);
        public readonly uint4 zxzy => new uint4(z, x, z, y);
        public readonly uint4 zxzz => new uint4(z, x, z, z);
        public readonly uint4 zxzw => new uint4(z, x, z, w);
        public readonly uint4 zxwx => new uint4(z, x, w, x);
        public uint4 zxwy { readonly get => new uint4(z, x, w, y); set { z = value.x; x = value.y; w = value.z; y = value.w; } }
        public readonly uint4 zxwz => new uint4(z, x, w, z);
        public readonly uint4 zxww => new uint4(z, x, w, w);
        public readonly uint4 zyxx => new uint4(z, y, x, x);
        public readonly uint4 zyxy => new uint4(z, y, x, y);
        public readonly uint4 zyxz => new uint4(z, y, x, z);
        public uint4 zyxw { readonly get => new uint4(z, y, x, w); set { z = value.x; y = value.y; x = value.z; w = value.w; } }
        public readonly uint4 zyyx => new uint4(z, y, y, x);
        public readonly uint4 zyyy => new uint4(z, y, y, y);
        public readonly uint4 zyyz => new uint4(z, y, y, z);
        public readonly uint4 zyyw => new uint4(z, y, y, w);
        public readonly uint4 zyzx => new uint4(z, y, z, x);
        public readonly uint4 zyzy => new uint4(z, y, z, y);
        public readonly uint4 zyzz => new uint4(z, y, z, z);
        public readonly uint4 zyzw => new uint4(z, y, z, w);
        public uint4 zywx { readonly get => new uint4(z, y, w, x); set { z = value.x; y = value.y; w = value.z; x = value.w; } }
        public readonly uint4 zywy => new uint4(z, y, w, y);
        public readonly uint4 zywz => new uint4(z, y, w, z);
        public readonly uint4 zyww => new uint4(z, y, w, w);
        public readonly uint4 zzxx => new uint4(z, z, x, x);
        public readonly uint4 zzxy => new uint4(z, z, x, y);
        public readonly uint4 zzxz => new uint4(z, z, x, z);
        public readonly uint4 zzxw => new uint4(z, z, x, w);
        public readonly uint4 zzyx => new uint4(z, z, y, x);
        public readonly uint4 zzyy => new uint4(z, z, y, y);
        public readonly uint4 zzyz => new uint4(z, z, y, z);
        public readonly uint4 zzyw => new uint4(z, z, y, w);
        public readonly uint4 zzzx => new uint4(z, z, z, x);
        public readonly uint4 zzzy => new uint4(z, z, z, y);
        public readonly uint4 zzzz => new uint4(z, z, z, z);
        public readonly uint4 zzzw => new uint4(z, z, z, w);
        public readonly uint4 zzwx => new uint4(z, z, w, x);
        public readonly uint4 zzwy => new uint4(z, z, w, y);
        public readonly uint4 zzwz => new uint4(z, z, w, z);
        public readonly uint4 zzww => new uint4(z, z, w, w);
        public readonly uint4 zwxx => new uint4(z, w, x, x);
        public uint4 zwxy { readonly get => new uint4(z, w, x, y); set { z = value.x; w = value.y; x = value.z; y = value.w; } }
        public readonly uint4 zwxz => new uint4(z, w, x, z);
        public readonly uint4 zwxw => new uint4(z, w, x, w);
        public uint4 zwyx { readonly get => new uint4(z, w, y, x); set { z = value.x; w = value.y; y = value.z; x = value.w; } }
        public readonly uint4 zwyy => new uint4(z, w, y, y);
        public readonly uint4 zwyz => new uint4(z, w, y, z);
        public readonly uint4 zwyw => new uint4(z, w, y, w);
        public readonly uint4 zwzx => new uint4(z, w, z, x);
        public readonly uint4 zwzy => new uint4(z, w, z, y);
        public readonly uint4 zwzz => new uint4(z, w, z, z);
        public readonly uint4 zwzw => new uint4(z, w, z, w);
        public readonly uint4 zwwx => new uint4(z, w, w, x);
        public readonly uint4 zwwy => new uint4(z, w, w, y);
        public readonly uint4 zwwz => new uint4(z, w, w, z);
        public readonly uint4 zwww => new uint4(z, w, w, w);
        public readonly uint4 wxxx => new uint4(w, x, x, x);
        public readonly uint4 wxxy => new uint4(w, x, x, y);
        public readonly uint4 wxxz => new uint4(w, x, x, z);
        public readonly uint4 wxxw => new uint4(w, x, x, w);
        public readonly uint4 wxyx => new uint4(w, x, y, x);
        public readonly uint4 wxyy => new uint4(w, x, y, y);
        public uint4 wxyz { readonly get => new uint4(w, x, y, z); set { w = value.x; x = value.y; y = value.z; z = value.w; } }
        public readonly uint4 wxyw => new uint4(w, x, y, w);
        public readonly uint4 wxzx => new uint4(w, x, z, x);
        public uint4 wxzy { readonly get => new uint4(w, x, z, y); set { w = value.x; x = value.y; z = value.z; y = value.w; } }
        public readonly uint4 wxzz => new uint4(w, x, z, z);
        public readonly uint4 wxzw => new uint4(w, x, z, w);
        public readonly uint4 wxwx => new uint4(w, x, w, x);
        public readonly uint4 wxwy => new uint4(w, x, w, y);
        public readonly uint4 wxwz => new uint4(w, x, w, z);
        public readonly uint4 wxww => new uint4(w, x, w, w);
        public readonly uint4 wyxx => new uint4(w, y, x, x);
        public readonly uint4 wyxy => new uint4(w, y, x, y);
        public uint4 wyxz { readonly get => new uint4(w, y, x, z); set { w = value.x; y = value.y; x = value.z; z = value.w; } }
        public readonly uint4 wyxw => new uint4(w, y, x, w);
        public readonly uint4 wyyx => new uint4(w, y, y, x);
        public readonly uint4 wyyy => new uint4(w, y, y, y);
        public readonly uint4 wyyz => new uint4(w, y, y, z);
        public readonly uint4 wyyw => new uint4(w, y, y, w);
        public uint4 wyzx { readonly get => new uint4(w, y, z, x); set { w = value.x; y = value.y; z = value.z; x = value.w; } }
        public readonly uint4 wyzy => new uint4(w, y, z, y);
        public readonly uint4 wyzz => new uint4(w, y, z, z);
        public readonly uint4 wyzw => new uint4(w, y, z, w);
        public readonly uint4 wywx => new uint4(w, y, w, x);
        public readonly uint4 wywy => new uint4(w, y, w, y);
        public readonly uint4 wywz => new uint4(w, y, w, z);
        public readonly uint4 wyww => new uint4(w, y, w, w);
        public readonly uint4 wzxx => new uint4(w, z, x, x);
        public uint4 wzxy { readonly get => new uint4(w, z, x, y); set { w = value.x; z = value.y; x = value.z; y = value.w; } }
        public readonly uint4 wzxz => new uint4(w, z, x, z);
        public readonly uint4 wzxw => new uint4(w, z, x, w);
        public uint4 wzyx { readonly get => new uint4(w, z, y, x); set { w = value.x; z = value.y; y = value.z; x = value.w; } }
        public readonly uint4 wzyy => new uint4(w, z, y, y);
        public readonly uint4 wzyz => new uint4(w, z, y, z);
        public readonly uint4 wzyw => new uint4(w, z, y, w);
        public readonly uint4 wzzx => new uint4(w, z, z, x);
        public readonly uint4 wzzy => new uint4(w, z, z, y);
        public readonly uint4 wzzz => new uint4(w, z, z, z);
        public readonly uint4 wzzw => new uint4(w, z, z, w);
        public readonly uint4 wzwx => new uint4(w, z, w, x);
        public readonly uint4 wzwy => new uint4(w, z, w, y);
        public readonly uint4 wzwz => new uint4(w, z, w, z);
        public readonly uint4 wzww => new uint4(w, z, w, w);
        public readonly uint4 wwxx => new uint4(w, w, x, x);
        public readonly uint4 wwxy => new uint4(w, w, x, y);
        public readonly uint4 wwxz => new uint4(w, w, x, z);
        public readonly uint4 wwxw => new uint4(w, w, x, w);
        public readonly uint4 wwyx => new uint4(w, w, y, x);
        public readonly uint4 wwyy => new uint4(w, w, y, y);
        public readonly uint4 wwyz => new uint4(w, w, y, z);
        public readonly uint4 wwyw => new uint4(w, w, y, w);
        public readonly uint4 wwzx => new uint4(w, w, z, x);
        public readonly uint4 wwzy => new uint4(w, w, z, y);
        public readonly uint4 wwzz => new uint4(w, w, z, z);
        public readonly uint4 wwzw => new uint4(w, w, z, w);
        public readonly uint4 wwwx => new uint4(w, w, w, x);
        public readonly uint4 wwwy => new uint4(w, w, w, y);
        public readonly uint4 wwwz => new uint4(w, w, w, z);
        public readonly uint4 wwww => new uint4(w, w, w, w);
        public readonly bool Equals(uint4 rhs) => x.Equals(rhs.x) && y.Equals(rhs.y) && z.Equals(rhs.z) && w.Equals(rhs.w);
        public override readonly bool Equals(object o) => o is uint4 v && Equals(v);
        public override readonly int GetHashCode() => HashCode.Combine(x, y, z, w);
        public override readonly string ToString() => string.Format(CultureInfo.InvariantCulture, "uint4({0}, {1}, {2}, {3})", x, y, z, w);
        public readonly string ToString(string format, IFormatProvider formatProvider) => string.Format("uint4({0}, {1}, {2}, {3})", x.ToString(format, formatProvider), y.ToString(format, formatProvider), z.ToString(format, formatProvider), w.ToString(format, formatProvider));
    }
}
