"""Export the four tadpole-swarm body plans (Tools/NCA/results/swarm_targets/*.json, the exact phase-1 training
targets that Tools/NCA/swarm_target.py builds from swarm_model.js) into a compact JS data file for swarm_creature.js.

    python Tools/Ecology/flight/creatures/build_plans.py      ->  creatures/swarm_plans.js  (window.SwarmPlans)

Per plan: the 8 animation frames of unit hearts (each frame centred on its own mean, as swarm_nca.cost_matrix
centres it), and per unit the attributes the yardstick scores: element, slot (body region), prism half-extents after
the element identity clamp (swarm_nca.identity_np), tier (Charge only), facing per frame, outward normal and
spindle (len, bend). No torch: identity_np is re-stated here in numpy.
"""
import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "..", "..", "NCA", "results", "swarm_targets"))
KINDS = ("mass", "space", "charge", "time")
MAJOR = {"mass": 1, "space": 2, "charge": 0, "time": 3}
HMIN, HMAX = 0.25, 3.0
SWIM_AXIS = {"mass": [1, 0, 0], "space": [0, 1, 0], "charge": [1, 0, 0], "time": [1, 0, 0]}   # jellyfish: bell first


def identity_np(elem, h, tier):
    h = np.clip(np.asarray(h, float), HMIN, HMAX)
    if elem == 0:
        o = np.clip(h, 0.3, 2.2)
    elif elem == 1:
        o = np.clip(h, 0.5, 1.8); o = np.minimum(o, o.min() * 1.6)
    elif elem == 2:
        L = np.clip(h[0], 0.9, 3.0); c = lambda x: np.clip(min(x, L / 4), 0.25, 0.42)
        o = np.array([L, c(h[1]), c(h[2])])
    else:
        L = np.clip(h[0], 0.45, 1.2); c = lambda x: np.clip(min(x, L / 1.5), 0.3, 0.6)
        o = np.array([L, c(h[1]), c(h[2])])
    return o, (tier if elem == 0 else 0)


def r(a, d=2):
    return [round(float(x), d) for x in np.asarray(a).ravel()]


def main():
    out = {}
    for k in KINDS:
        d = json.load(open(os.path.join(SRC, k + ".json")))
        fr = d["frames"]
        U0 = fr[0]["units"]
        n = len(U0)
        P = np.array([[u["p"] for u in f["units"]] for f in fr], float)
        P = P - P.mean(1, keepdims=True)
        Fd = np.array([[u["f"] for u in f["units"]] for f in fr], float)
        Fd = Fd / np.maximum(np.linalg.norm(Fd, axis=-1, keepdims=True), 1e-6)
        H, T = [], []
        for u in U0:
            h, t = identity_np(u["elem"], u["prism"]["h"], u["prism"].get("tier", 0))
            H.append(h); T.append(int(t))
        roles = sorted({u["role"] for u in U0})
        rep = d["report"]
        out[k] = dict(
            kind=k, name=d["name"], major=MAJOR[k], n=n, frames=len(fr),
            slots=sum(1 for c in rep["slots"] if c > 0), mix=rep["elements"], swimAxis=SWIM_AXIS[k],
            P=r(P), F=r(Fd), elem=[u["elem"] for u in U0], slot=[u["prism"]["slot"] for u in U0],
            tier=T, H=r(H, 3), N=r([u["n"] for u in U0]), SP=r([[u["spindle"]["len"], u["spindle"]["bend"]] for u in U0], 3),
            roleNames=roles, role=[roles.index(u["role"]) for u in U0])
    js = ("/* swarm_plans.js - GENERATED by build_plans.py from Tools/NCA/results/swarm_targets (phase-1 targets). Do not edit.\n"
          " * Four body plans of one tadpole swarm: mass = Whale, space = Jellyfish, charge = Pufferfish, time = Dragonfly.\n"
          " * Element index order (NCA): 0 Charge, 1 Mass, 2 Space, 3 Time. P/F are [frame][unit][xyz] flattened. */\n"
          "(function (root) {\n  const SwarmPlans = " + json.dumps(out, separators=(",", ":")) + ";\n"
          "  if (typeof module !== 'undefined' && module.exports) module.exports = SwarmPlans;\n"
          "  if (root) root.SwarmPlans = SwarmPlans;\n})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));\n")
    path = os.path.join(HERE, "swarm_plans.js")
    open(path, "w").write(js)
    print(path, len(js), "bytes;", {k: (v["name"], v["n"], v["mix"]) for k, v in out.items()})


if __name__ == "__main__":
    main()
