#!/usr/bin/env python3
"""Emit a self-contained nca_creature.js with the trained 3D NCA weights inlined.

  python3 build_nca_creature.py [--weights PATH] [--fmt f16|i8|f32] [--out nca_creature.js]

Reads the template nca_creature.src.js, packs w1/b1/w2/b2 (fp16 base64 by default,
per-row int8 with --fmt i8) and replaces the /*__NCA_WEIGHTS__*/null placeholder.
"""
import argparse, base64, json, os, shutil, subprocess
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_W = os.path.normpath(os.path.join(HERE, '../../../NCA/results/lizard3d_swim/weights.json'))

def pack(arr, fmt):
    a = np.asarray(arr, dtype=np.float32)
    row = a.shape[-1] if a.ndim > 1 else a.size
    flat = a.reshape(-1)
    t = {'fmt': fmt, 'n': int(flat.size), 'row': int(row)}
    if fmt == 'f16':
        t['data'] = base64.b64encode(flat.astype('<f2').tobytes()).decode()
    elif fmt == 'i8':
        rows = flat.reshape(-1, row)
        sc = np.abs(rows).max(axis=1) / 127.0
        sc[sc == 0] = 1.0
        q = np.clip(np.round(rows / sc[:, None]), -127, 127).astype(np.int8)
        t['scale'] = [float(s) for s in sc]
        t['data'] = base64.b64encode(q.tobytes()).decode()
    else:
        t['fmt'] = 'f32'
        t['data'] = base64.b64encode(flat.astype('<f4').tobytes()).decode()
    return t

def build_wasm():
    """Compile nca_kernel.c -> nca_kernel.wasm (when clang with the wasm32 target is available and the .c is newer),
    then return {b64, heapBase} for embedding. The committed .wasm is used when clang is missing."""
    c, w = os.path.join(HERE, 'nca_kernel.c'), os.path.join(HERE, 'nca_kernel.wasm')
    if shutil.which('clang') and (not os.path.exists(w) or os.path.getmtime(c) > os.path.getmtime(w)):
        subprocess.run(['clang', '--target=wasm32', '-O3', '-msimd128', '-mbulk-memory', '-nostdlib', '-Wl,--no-entry',
                        '-Wl,--import-memory', '-Wl,--export=nca_cells', '-Wl,--export=__heap_base', '-o', w, c], check=True)
    if not os.path.exists(w):
        print('warning: no nca_kernel.wasm - built module will use the JS backend only'); return None
    data = open(w, 'rb').read()
    assert len(data) < 4096, 'keep the kernel < 4 KB: Chrome refuses synchronous WebAssembly.Module() above that'
    return {'b64': base64.b64encode(data).decode(), 'heapBase': wasm_heap_base(data)}

def wasm_heap_base(data):
    """Read the exported global __heap_base (an i32.const initialiser) from the wasm binary."""
    def leb(b, i, signed=False):
        r = s = 0
        while True:
            x = b[i]; i += 1; r |= (x & 0x7f) << s; s += 7
            if not x & 0x80: break
        if signed and x & 0x40: r -= 1 << s
        return r, i
    i, globals_, gidx = 8, [], None
    while i < len(data):
        sid = data[i]; size, i = leb(data, i + 1); end = i + size
        if sid == 6:                                   # global section
            n, j = leb(data, i)
            for _ in range(n):
                j += 2                                  # valtype, mut
                assert data[j] == 0x41; v, j = leb(data, j + 1, True); assert data[j] == 0x0b; j += 1
                globals_.append(v)
        elif sid == 7:                                 # export section
            n, j = leb(data, i)
            for _ in range(n):
                ln, j = leb(data, j); name = data[j:j + ln].decode(); j += ln; kind = data[j]; idx, j = leb(data, j + 1)
                if name == '__heap_base' and kind == 3: gidx = idx
        i = end
    return globals_[gidx]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--weights', default=DEFAULT_W)
    ap.add_argument('--fmt', default='f16', choices=['f16', 'i8', 'f32'])
    ap.add_argument('--out', default=os.path.join(HERE, 'nca_creature.js'))
    a = ap.parse_args()
    w = json.load(open(a.weights))
    packed = {k: w[k] for k in ('channel_n', 'hidden', 'fire_rate', 'D', 'H', 'W')}
    packed['period'] = w.get('period', 8); packed['frames'] = w.get('frames', 8)
    packed['source'] = os.path.relpath(a.weights, HERE)
    packed['tensors'] = {}
    err = 0.0
    for k in ('w1', 'b1', 'w2', 'b2'):
        # 1D biases must not be quantized per-element with i8 (one scale per value) -> keep f16
        f = a.fmt if (a.fmt != 'i8' or np.asarray(w[k]).ndim > 1) else 'f16'
        packed['tensors'][k] = pack(w[k], f)
    src = open(os.path.join(HERE, 'nca_creature.src.js')).read()
    marker = '/*__NCA_WEIGHTS__*/null'
    assert marker in src, 'placeholder missing in template'
    body = src.replace(marker, json.dumps(packed, separators=(',', ':')))
    wasm = build_wasm()
    wmark = '/*__NCA_WASM__*/null'
    assert wmark in body, 'wasm placeholder missing in template'
    body = body.replace(wmark, json.dumps(wasm, separators=(',', ':')) if wasm else 'null')
    hdr = ('// GENERATED by build_nca_creature.py from nca_creature.src.js -- do not edit by hand.\n'
           f'// weights: {packed["source"]} ({a.fmt})\n')
    open(a.out, 'w').write(hdr + body)
    n = sum(t['n'] for t in packed['tensors'].values())
    print(f'wrote {a.out}: {os.path.getsize(a.out)} bytes ({n} params, {a.fmt}); template {len(src)} bytes')

if __name__ == '__main__':
    main()
