/* swarm_creature.js - a morphing tadpole-swarm creature for the flyable ecology cell.
 *
 * One swarm of tadpole units (heart crystal + spindle + body prism) that sorts itself into one of four phase-1 body
 * plans and swims as a body:  mass = Whale, space = Jellyfish, charge = Pufferfish, time = Dragonfly.
 *
 * The controller is the phase-1 front runner (Tools/NCA/DISCOVERIES.md: "a designed composition controller + a local
 * shape rule + a fractional update", sortfeel frac 8), restated for a game creature:
 *   - COMPOSITION IS DESIGNED. A composition vector (or setElement) fixes how many tadpoles of each element the body
 *     wants; the plan is the majority element's plan (with a short dwell, so a noisy vector does not flicker). Each
 *     plan region (element x slot) gets a quota of the n tadpoles; a tadpole of a surplus element MOLTS (re-forms its
 *     crystal) into the element its region lacks. Nothing is ever destroyed: lossless = molting.
 *   - SHAPE IS LOCAL. Each tadpole commits to a fate (one well of its type in the plan, animated through the plan's
 *     8-frame swim cycle). It knows only its fate, its neighbours (spatial hash) and the body frame: separation from
 *     neighbours, and Potts-style fate SWAPS with same-element neighbours that would each sit better in the other's
 *     spot. A plan switch re-deals fates once (greedy nearest, same element first) and the swaps polish it.
 *   - FRACTIONAL UPDATE. Only 1 in `frac` (default 8) tadpoles runs the local rule per step (neighbours, swaps,
 *     molts, look); the rest coast on their stale intent. Cheaper and, as phase 1 found, smoother (a low-pass).
 *     Every tadpole still tracks its animated well each frame with a critically damped spring (O(n), trivial).
 *   - hit(): tadpoles in the blast are knocked loose (stunned, tumbling), some crystals crack into a random element;
 *     after the stun they swim back with a RAMPED gain (the phase-1 fix for the post-strike jolt) and the controller
 *     molts the cracked ones back.
 *
 * Coordinates: units are simulated in the body's SWIM frame (voxels, +x = direction of travel, +y = up), which is
 * the plan frame rotated so the plan's swim axis is +x (the jellyfish swims bell first, +y in its plan). World =
 * position + Q_body * (scale * swim). The yardstick (swarm_loss.js) is evaluated in the PLAN frame (lossState()).
 *
 *   const c = new SwarmCreature({ n: 192, element: 'mass', position: [0, 0, 0], seed: 1, scale: 0.4 });
 *   c.steer([40, 0, 10], 8);  c.step(dt);  c.setElement('space');  c.setComposition([.2, .1, .6, .1]);
 *   c.hit(worldPoint, worldRadius);  const u = c.units();  const g = c.mesh(THREE); scene.add(g); c.sync();
 *
 * Needs SwarmPlans (swarm_plans.js, generated by build_plans.py): a <script> before this one, or require() in node.
 */
(function (root) {
  'use strict';
  const Plans = (typeof module !== 'undefined' && module.exports) ? require('./swarm_plans.js') : root.SwarmPlans;

  // NCA element order: 0 Charge, 1 Mass, 2 Space, 3 Time. Colours = ELEMENT_COLOUR in flight/src/60_stakes.js.
  const ELEM_NAMES = ['charge', 'mass', 'space', 'time'];
  const ELEMENT_COLOUR = { mass: [0.98, 0.42, 0.30], charge: [1.0, 0.84, 0.25], space: [0.42, 0.62, 1.0], time: [0.62, 1.0, 0.55] };
  const COL = ELEM_NAMES.map(k => ELEMENT_COLOUR[k]);
  const PLAN_OF = ['charge', 'mass', 'space', 'time'];          // majority element index -> plan kind
  const HEART_R = [1.149, 0.8685, 1.149, 0.8685];                // 0.5 * heart world size (tadpole_model.js)
  const HMIN = 0.25, HMAX = 3.0;

  function elemIndex(e) {
    if (typeof e === 'number') return e | 0;
    const i = ELEM_NAMES.indexOf(String(e).toLowerCase());
    if (i < 0) throw new Error('SwarmCreature: unknown element ' + e);
    return i;
  }
  function mulberry32(a) {
    return function () {
      a |= 0; a = (a + 0x6D2B79F5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }
  const clamp = (x, a, b) => x < a ? a : x > b ? b : x;

  // the element identity clamp (swarm_nca.identity_np, as build_plans.py states it): a relabelled well wears it
  function identity(elem, h) {
    h = h.map(v => clamp(v, HMIN, HMAX));
    if (elem === 0) return h.map(v => clamp(v, 0.3, 2.2));
    if (elem === 1) { let o = h.map(v => clamp(v, 0.5, 1.8)); const m = Math.min(o[0], o[1], o[2]) * 1.6; return o.map(v => Math.min(v, m)); }
    if (elem === 2) { const L = clamp(h[0], 0.9, 3.0), c = x => clamp(Math.min(x, L / 4), 0.25, 0.42); return [L, c(h[1]), c(h[2])]; }
    const L = clamp(h[0], 0.45, 1.2), c = x => clamp(Math.min(x, L / 1.5), 0.3, 0.6); return [L, c(h[1]), c(h[2])];
  }

  // ---- per-plan cache in the swim frame ---------------------------------------------------------------------------
  // swim = R * plan, R maps the plan's swim axis to +x. Jellyfish [0,1,0]: (x,y,z) -> (y,-x,z).
  const _planCache = {};
  function planData(kind) {
    if (_planCache[kind]) return _planCache[kind];
    const pl = Plans[kind];
    const jelly = pl.swimAxis[1] === 1;
    const rot = jelly ? (a, o, b, k) => { b[k] = a[o + 1]; b[k + 1] = -a[o]; b[k + 2] = a[o + 2]; }
                      : (a, o, b, k) => { b[k] = a[o]; b[k + 1] = a[o + 1]; b[k + 2] = a[o + 2]; };
    const m = pl.n, F = pl.frames;
    const PS = new Float32Array(F * m * 3), FS = new Float32Array(F * m * 3), NS = new Float32Array(m * 3);
    for (let q = 0; q < F * m; q++) { rot(pl.P, 3 * q, PS, 3 * q); rot(pl.F, 3 * q, FS, 3 * q); }
    for (let j = 0; j < m; j++) rot(pl.N, 3 * j, NS, 3 * j);
    // types (element, slot) -> plan unit lists
    const types = new Map();
    for (let j = 0; j < m; j++) {
      const key = pl.elem[j] * 4 + pl.slot[j];
      if (!types.has(key)) types.set(key, []);
      types.get(key).push(j);
    }
    const mix = [0, 0, 0, 0]; for (let j = 0; j < m; j++) mix[pl.elem[j]]++;
    const d = { kind, pl, m, F, PS, FS, NS, types, jelly, mix: mix.map(c => c / m) };
    _planCache[kind] = d;
    return d;
  }
  // swim-frame vector -> plan frame (the inverse rotation)
  function toPlan(d, x, y, z, out, k) {
    if (d.jelly) { out[k] = -y; out[k + 1] = x; out[k + 2] = z; } else { out[k] = x; out[k + 1] = y; out[k + 2] = z; }
  }

  // largest-remainder rounding of fractions w (sum 1) to integers summing to n
  function apportion(w, n) {
    const s = w.reduce((a, b) => a + b, 0) || 1;
    const raw = w.map(x => x / s * n), out = raw.map(Math.floor);
    let left = n - out.reduce((a, b) => a + b, 0);
    const order = raw.map((r, i) => [r - Math.floor(r), i]).sort((a, b) => b[0] - a[0]);
    for (let k = 0; left > 0; k = (k + 1) % order.length, left--) out[order[k][1]]++;
    return out;
  }

  // ---- the creature -----------------------------------------------------------------------------------------------
  function SwarmCreature(opt) {
    opt = opt || {};
    const n = this.n = Math.max(8, opt.n | 0 || 192);
    this.rand = mulberry32((opt.seed | 0) || 1);
    this.frac = Math.max(1, opt.frac | 0 || 8);
    this.scale = opt.scale || 0.4;                     // world units per voxel
    this.position = Float64Array.from(opt.position || [0, 0, 0]);
    this.heading = Float64Array.from([1, 0, 0]);
    this.up = [0, 1, 0];
    this.bank = 0;
    this.speed = 0;                                    // world units / s
    this.cruise = opt.cruise || 6;
    this.turnRate = opt.turnRate || 1.4;               // rad / s
    this.goal = null; this.goalSpeed = null;
    this.phase = 0;                                    // swim-cycle phase in plan frames [0, F)
    this.cycleBase = opt.cycleBase || 0.45;            // cycles / s at rest
    this.cycleGain = opt.cycleGain || 0.05;            // extra cycles / s per world unit / s
    this.time = 0; this.tick = 0;
    this.w = opt.stiffness || 5.0;                     // tracking spring (critically damped), 1/s
    this.vmax = opt.vmax || 36;                        // voxels / s (sets the morph pace)
    this.sepR = 1.5; this.sepK = 18;
    this.swapR = 5.0;
    this.moltP = 0.35;                                 // chance per own update that a mis-crystalled tadpole molts
    this.dwell = opt.dwell != null ? opt.dwell : 0.25; // s a new majority must hold before the plan switches

    // tadpoles
    this.p = new Float32Array(3 * n); this.v = new Float32Array(3 * n);
    this.f = new Float32Array(3 * n); this.nr = new Float32Array(3 * n);
    this.h = new Float32Array(3 * n); this.sp = new Float32Array(2 * n);
    this.elem = new Uint8Array(n); this.prevElem = new Uint8Array(n); this.dom = new Uint8Array(n);
    this.tier = new Uint8Array(n);
    this.fate = new Int32Array(n);                     // index into the current target list
    this.adopt = new Float32Array(n);                  // time at which a tadpole takes up its new-plan fate
    this.stun = new Float32Array(n); this.ramp = new Float32Array(n).fill(1);
    this.moltT = new Float32Array(n);
    this.sep = new Float32Array(3 * n);                // stale separation intent (fractional)
    // spatial hash
    this.hsize = 4096; this.hhead = new Int32Array(this.hsize); this.hnext = new Int32Array(n); this.cell = 3.0;
    this.stats = { molts: 0, swaps: 0, updates: 0 };

    const e0 = elemIndex(opt.element != null ? opt.element : 'mass');
    this.comp = planData(PLAN_OF[e0]).mix.slice();
    this.kind = PLAN_OF[e0]; this.cand = this.kind; this.candT = 0;
    this.T = this._targets(planData(this.kind), this.comp);
    this.prevT = null;
    // born formed: every tadpole on its own well, wearing its look
    for (let i = 0; i < n; i++) {
      this.fate[i] = i; const T = this.T;
      this.elem[i] = this.prevElem[i] = T.elem[i]; this.dom[i] = T.slot[i]; this.tier[i] = T.tier[i];
      for (let a = 0; a < 3; a++) this.h[3 * i + a] = T.h[3 * i + a];
      this.sp[2 * i] = T.sp[2 * i]; this.sp[2 * i + 1] = T.sp[2 * i + 1];
    }
    const tmp = new Float32Array(6);
    for (let i = 0; i < n; i++) {
      this._wellAt(this.T, i, this.phase, tmp);
      for (let a = 0; a < 3; a++) { this.p[3 * i + a] = tmp[a] + (this.rand() - 0.5) * 0.2; this.f[3 * i + a] = 1; }
      this._faceTarget(this.T, i, this.phase, tmp, 0);
      for (let a = 0; a < 3; a++) this.f[3 * i + a] = tmp[a];
      const j = this.T.j[i];
      for (let a = 0; a < 3; a++) this.nr[3 * i + a] = this.T.d.NS[3 * j + a];
    }
    if (opt.hatch) for (let i = 0; i < 3 * n; i++) this.p[i] = (this.rand() - 0.5) * 30;
  }

  /** Deal n wells of plan d to an element composition: region quotas, relabelled wells, duplicate offsets. */
  SwarmCreature.prototype._targets = function (d, comp) {
    const n = this.n, pl = d.pl, rand = this.rand;
    const keys = [...d.types.keys()].sort((a, b) => a - b);
    const quota = apportion(keys.map(k => d.types.get(k).length), n);
    const T = { d, n, j: new Int32Array(n), elem: new Uint8Array(n), slot: new Uint8Array(n), tier: new Uint8Array(n),
                off: new Float32Array(3 * n), h: new Float32Array(3 * n), sp: new Float32Array(2 * n) };
    let t = 0;
    keys.forEach((key, ki) => {
      const L = d.types.get(key), mc = L.length, qc = quota[ki];
      for (let k = 0; k < qc; k++, t++) {
        const j = qc >= mc ? L[k % mc] : L[Math.floor(k * mc / qc)];
        const dup = qc >= mc ? Math.floor(k / mc) : 0;
        T.j[t] = j; T.elem[t] = pl.elem[j]; T.slot[t] = pl.slot[j]; T.tier[t] = pl.tier[j];
        for (let a = 0; a < 3; a++) T.h[3 * t + a] = pl.H[3 * j + a];
        T.sp[2 * t] = pl.SP[2 * j]; T.sp[2 * t + 1] = pl.SP[2 * j + 1];
        if (dup > 0) {                                  // a duplicate sits beside its well, in the surface's tangent plane
          const N = [d.NS[3 * j], d.NS[3 * j + 1], d.NS[3 * j + 2]];
          let ax = Math.abs(N[0]) < 0.9 ? [1, 0, 0] : [0, 1, 0];
          let u = [N[1] * ax[2] - N[2] * ax[1], N[2] * ax[0] - N[0] * ax[2], N[0] * ax[1] - N[1] * ax[0]];
          const ul = Math.hypot(u[0], u[1], u[2]) || 1; u = u.map(x => x / ul);
          const w = [N[1] * u[2] - N[2] * u[1], N[2] * u[0] - N[0] * u[2], N[0] * u[1] - N[1] * u[0]];
          const ang = dup * 2.39996 + j, r = 1.1 * Math.sqrt(dup);
          for (let a = 0; a < 3; a++) T.off[3 * t + a] = r * (Math.cos(ang) * u[a] + Math.sin(ang) * w[a]);
        }
      }
    });
    // composition: relabel wells of surplus elements into deficit ones (the designed controller)
    const want = apportion(comp, n), have = [0, 0, 0, 0];
    for (let i = 0; i < n; i++) have[T.elem[i]]++;
    const order = []; for (let i = 0; i < n; i++) order.push(i);
    for (let i = n - 1; i > 0; i--) { const k = Math.floor(rand() * (i + 1)); const s = order[i]; order[i] = order[k]; order[k] = s; }
    for (const i of order) {
      const e = T.elem[i];
      if (have[e] <= want[e]) continue;
      let best = -1, gap = 0;
      for (let e2 = 0; e2 < 4; e2++) if (want[e2] - have[e2] > gap) { gap = want[e2] - have[e2]; best = e2; }
      if (best < 0) break;
      have[e]--; have[best]++; T.elem[i] = best; T.tier[i] = 0;
      const hh = identity(best, [T.h[3 * i], T.h[3 * i + 1], T.h[3 * i + 2]]);
      for (let a = 0; a < 3; a++) T.h[3 * i + a] = hh[a];
    }
    return T;
  };

  // Catmull-Rom through the plan's cyclic frames: well position (+ its phase derivative) of target t
  SwarmCreature.prototype._wellAt = function (T, t, phase, out) {
    const d = T.d, F = d.F, m = d.m, j = T.j[t];
    const k = Math.floor(phase), u = phase - k;
    const k0 = ((k - 1) % F + F) % F, k1 = ((k % F) + F) % F, k2 = (k1 + 1) % F, k3 = (k1 + 2) % F;
    const P = d.PS, o0 = 3 * (k0 * m + j), o1 = 3 * (k1 * m + j), o2 = 3 * (k2 * m + j), o3 = 3 * (k3 * m + j);
    const u2 = u * u, u3 = u2 * u;
    for (let a = 0; a < 3; a++) {
      const p0 = P[o0 + a], p1 = P[o1 + a], p2 = P[o2 + a], p3 = P[o3 + a];
      out[a] = 0.5 * (2 * p1 + (-p0 + p2) * u + (2 * p0 - 5 * p1 + 4 * p2 - p3) * u2 + (-p0 + 3 * p1 - 3 * p2 + p3) * u3) + T.off[3 * t + a];
      out[3 + a] = 0.5 * ((-p0 + p2) + 2 * (2 * p0 - 5 * p1 + 4 * p2 - p3) * u + 3 * (-p0 + 3 * p1 - 3 * p2 + p3) * u2);
    }
  };
  SwarmCreature.prototype._faceTarget = function (T, t, phase, out, o) {
    const d = T.d, F = d.F, m = d.m, j = T.j[t];
    const k = Math.floor(phase), u = phase - k, k1 = ((k % F) + F) % F, k2 = (k1 + 1) % F;
    let x = 0, y = 0, z = 0;
    const a1 = 3 * (k1 * m + j), a2 = 3 * (k2 * m + j);
    x = d.FS[a1] * (1 - u) + d.FS[a2] * u; y = d.FS[a1 + 1] * (1 - u) + d.FS[a2 + 1] * u; z = d.FS[a1 + 2] * (1 - u) + d.FS[a2 + 2] * u;
    const l = Math.hypot(x, y, z) || 1;
    out[o] = x / l; out[o + 1] = y / l; out[o + 2] = z / l;
  };

  // ---- composition / plan -----------------------------------------------------------------------------------------
  /** Switch to an element's body plan and its own element mix (a smooth morph + molts). */
  SwarmCreature.prototype.setElement = function (e) {
    const k = PLAN_OF[elemIndex(e)];
    this.comp = planData(k).mix.slice();
    this._switch(k);
    return this;
  };
  /** Composition vector [charge, mass, space, time] (fractions or counts; or an object keyed by element name).
   *  The plan follows the majority element after `dwell` s; the mix is honoured by molting. */
  SwarmCreature.prototype.setComposition = function (c) {
    if (!Array.isArray(c)) c = ELEM_NAMES.map(k => +(c[k] || 0));
    const s = c.reduce((a, b) => a + b, 0) || 1;
    this.comp = c.map(x => x / s);
    let maj = 0; for (let e = 1; e < 4; e++) if (this.comp[e] > this.comp[maj]) maj = e;
    const k = PLAN_OF[maj];
    if (k === this.kind) { this._redeal(this.kind); this.cand = k; this.candT = 0; }
    else if (this.dwell <= 0) this._switch(k);
    else if (k !== this.cand) { this.cand = k; this.candT = 0; }
    return this;
  };
  SwarmCreature.prototype.composition = function () {
    const c = [0, 0, 0, 0]; for (let i = 0; i < this.n; i++) c[this.elem[i]]++;
    return { want: this.comp.slice(), have: c.map(x => x / this.n), plan: this.kind, name: Plans[this.kind].name };
  };

  SwarmCreature.prototype._switch = function (kind) {
    this.cand = kind; this.candT = 0;
    this.morphStart = this.time; this.morphFrom = this.kind;
    this._redeal(kind);
  };

  /** Re-deal fates for plan `kind`: same element first (no molt), greedy nearest; the rest are dealt to the wells
   *  left over and molt. Each tadpole takes its new fate after a head-to-tail ripple delay. */
  SwarmCreature.prototype._redeal = function (kind) {
    const n = this.n, d = planData(kind);
    const old = this.T, oldFate = this.fate.slice();
    const T = this._targets(d, this.comp);
    const tmp = new Float32Array(6), W = new Float32Array(3 * n);
    for (let t = 0; t < n; t++) { this._wellAt(T, t, this.phase, tmp); W[3 * t] = tmp[0]; W[3 * t + 1] = tmp[1]; W[3 * t + 2] = tmp[2]; }
    const takenU = new Uint8Array(n), takenT = new Uint8Array(n), fate = new Int32Array(n).fill(-1);
    const order = []; for (let t = 0; t < n; t++) order.push(t);
    for (let i = n - 1; i > 0; i--) { const k = Math.floor(this.rand() * (i + 1)); const s = order[i]; order[i] = order[k]; order[k] = s; }
    const P = this.p;
    const pass = sameElem => {
      for (const t of order) {
        if (takenT[t]) continue;
        let best = -1, bd = Infinity;
        const wx = W[3 * t], wy = W[3 * t + 1], wz = W[3 * t + 2], e = T.elem[t];
        for (let i = 0; i < n; i++) {
          if (takenU[i] || (sameElem && this.elem[i] !== e)) continue;
          const dx = P[3 * i] - wx, dy = P[3 * i + 1] - wy, dz = P[3 * i + 2] - wz, dd = dx * dx + dy * dy + dz * dz;
          if (dd < bd) { bd = dd; best = i; }
        }
        if (best >= 0) { takenU[best] = 1; takenT[t] = 1; fate[best] = t; }
      }
    };
    pass(true); pass(false);
    // ripple: front of the body (swim +x) first
    let xmin = Infinity, xmax = -Infinity;
    for (let i = 0; i < n; i++) { xmin = Math.min(xmin, P[3 * i]); xmax = Math.max(xmax, P[3 * i]); }
    const span = Math.max(1, xmax - xmin), sameKind = kind === this.kind;
    this.prevT = old; this.prevFate = oldFate;
    for (let i = 0; i < n; i++) {
      this.fate[i] = fate[i];
      this.adopt[i] = sameKind ? this.time : this.time + 0.35 * (xmax - P[3 * i]) / span + 0.05 * this.rand();
    }
    this.T = T; this.kind = kind;
  };

  // ---- steering ---------------------------------------------------------------------------------------------------
  /** Swim the body toward a world point (null = idle drift). speed in world units / s (default cruise). */
  SwarmCreature.prototype.steer = function (target, speed) {
    this.goal = target ? Float64Array.from(target) : null;
    this.goalSpeed = speed != null ? speed : null;
    return this;
  };
  SwarmCreature.prototype._swimBody = function (dt) {
    let want = 0, turn = 0;
    if (this.goal) {
      const g = this.goal, p = this.position;
      let dx = g[0] - p[0], dy = g[1] - p[1], dz = g[2] - p[2];
      const dist = Math.hypot(dx, dy, dz);
      const vs = this.goalSpeed != null ? this.goalSpeed : this.cruise;
      want = vs * clamp((dist - 0.5) / (vs * 1.2 + 1e-6), 0, 1);       // arrive: brake inside ~1.2 s of travel
      if (dist > 1.0) {
        dx /= dist; dy /= dist; dz /= dist;
        const h = this.heading, c = clamp(h[0] * dx + h[1] * dy + h[2] * dz, -1, 1), ang = Math.acos(c);
        if (ang > 1e-5) {
          const s = Math.min(1, this.turnRate * dt / ang);
          // turning side for the bank: sign of (h x d) . up
          const cx = h[1] * dz - h[2] * dy, cz = h[0] * dy - h[1] * dx, cy = h[2] * dx - h[0] * dz;
          turn = Math.sign(cy) * Math.min(ang, this.turnRate * dt) / Math.max(dt, 1e-6); void cx; void cz;
          let nx = h[0] + (dx - h[0]) * s, ny = h[1] + (dy - h[1]) * s, nz = h[2] + (dz - h[2]) * s;
          if (ang > 2.8 && s < 1) { nx += -h[2] * 0.2; nz += h[0] * 0.2; }     // a U-turn needs a side to turn to
          ny = clamp(ny, -0.85, 0.85);
          want *= 0.25 + 0.75 * Math.max(0, c);                              // slow down to turn round
          const l = Math.hypot(nx, ny, nz) || 1; h[0] = nx / l; h[1] = ny / l; h[2] = nz / l;
        }
      }
    }
    this.speed += (want - this.speed) * Math.min(1, (want < this.speed ? 3 : 1.2) * dt);
    for (let a = 0; a < 3; a++) this.position[a] += this.heading[a] * this.speed * dt;
    this.bank += (clamp(-turn * 0.5, -0.6, 0.6) - this.bank) * Math.min(1, 2 * dt);
  };
  /** Body basis: columns x = heading, y = up (banked), z = x * y. Row-major 3x3. */
  SwarmCreature.prototype.basis = function () {
    const x = this.heading;
    let z = [x[1] * 0 - x[2] * 1, x[2] * 0 - x[0] * 0, x[0] * 1 - x[1] * 0];      // x * worldUp
    let zl = Math.hypot(z[0], z[1], z[2]); if (zl < 1e-6) { z = [0, 0, 1]; zl = 1; }
    z = z.map(v => v / zl);
    let y = [z[1] * x[2] - z[2] * x[1], z[2] * x[0] - z[0] * x[2], z[0] * x[1] - z[1] * x[0]];
    const cb = Math.cos(this.bank), sb = Math.sin(this.bank);
    const y2 = [y[0] * cb + z[0] * sb, y[1] * cb + z[1] * sb, y[2] * cb + z[2] * sb];
    const z2 = [z[0] * cb - y[0] * sb, z[1] * cb - y[1] * sb, z[2] * cb - y[2] * sb];
    return [x[0], y2[0], z2[0], x[1], y2[1], z2[1], x[2], y2[2], z2[2]];
  };

  // ---- the step ---------------------------------------------------------------------------------------------------
  /** Advance dt seconds (clamped/sub-stepped; state persists, so it can be paused and resumed at will).
   *  ctx (optional): { target, speed } = steer(target, speed) for this call. */
  SwarmCreature.prototype.step = function (dt, ctx) {
    if (ctx && ctx.target !== undefined) this.steer(ctx.target, ctx.speed);
    dt = Math.max(0, dt || 0);
    const sub = Math.max(1, Math.ceil(dt / (1 / 30)));
    for (let s = 0; s < sub; s++) this._step(dt / sub);
    return this;
  };

  SwarmCreature.prototype._hashBuild = function () {
    const n = this.n, P = this.p, H = this.hhead, N = this.hnext, c = 1 / this.cell, M = this.hsize - 1;
    H.fill(-1);
    for (let i = 0; i < n; i++) {
      const k = this._key(Math.floor(P[3 * i] * c), Math.floor(P[3 * i + 1] * c), Math.floor(P[3 * i + 2] * c)) & M;
      N[i] = H[k]; H[k] = i;
    }
  };
  SwarmCreature.prototype._key = function (x, y, z) { return (Math.imul(x, 73856093) ^ Math.imul(y, 19349663) ^ Math.imul(z, 83492791)); };

  SwarmCreature.prototype._step = function (dt) {
    if (dt <= 0) return;
    const n = this.n, P = this.p, V = this.v;
    this.time += dt; this.tick++;
    // plan dwell (composition-driven switches)
    if (this.cand !== this.kind) { this.candT += dt; if (this.candT >= this.dwell) this._switch(this.cand); }
    this._swimBody(dt);
    const F = this.T.d.F;
    this.phase = (this.phase + (this.cycleBase + this.cycleGain * this.speed) * F * dt) % F;
    const prate = (this.cycleBase + this.cycleGain * this.speed) * F;

    this._hashBuild();
    // --- fractional local rule: 1 in frac tadpoles per step
    const fr = this.frac, off = this.tick % fr;
    const tmp = new Float32Array(6), tmp2 = new Float32Array(6);
    for (let i = off; i < n; i += fr) this._local(i, dt * fr, tmp, tmp2);

    // --- every tadpole tracks its (animated) well: critically damped, speed-clipped
    const w = this.w, kp = w * w, kd = 2 * w, vmax = this.vmax;
    for (let i = 0; i < n; i++) {
      const o = 3 * i;
      if (this.stun[i] > 0) {                       // loose: tumble with drag
        this.stun[i] -= dt;
        const dr = Math.exp(-1.6 * dt);
        V[o] *= dr; V[o + 1] *= dr; V[o + 2] *= dr;
        P[o] += V[o] * dt; P[o + 1] += V[o + 1] * dt; P[o + 2] += V[o + 2] * dt;
        if (this.stun[i] <= 0) this.ramp[i] = 0;
        continue;
      }
      const prev = this.time < this.adopt[i] && this.prevT;
      const TT = prev ? this.prevT : this.T, t = prev ? this.prevFate[i] : this.fate[i];
      const ph = TT.d === this.T.d ? this.phase : (this.phase / F) * TT.d.F;
      this._wellAt(TT, t, ph, tmp);
      if (this.ramp[i] < 1) this.ramp[i] = Math.min(1, this.ramp[i] + dt / 0.6);
      const g = this.ramp[i] * this.ramp[i] * (3 - 2 * this.ramp[i]);
      for (let a = 0; a < 3; a++) {
        const tv = tmp[3 + a] * prate;
        let acc = g * (kp * (tmp[a] - P[o + a]) + kd * (tv - V[o + a])) + this.sep[o + a];
        V[o + a] += acc * dt;
      }
      const sp = Math.hypot(V[o], V[o + 1], V[o + 2]);
      if (sp > vmax) { const s = vmax / sp; V[o] *= s; V[o + 1] *= s; V[o + 2] *= s; }
      P[o] += V[o] * dt; P[o + 1] += V[o + 1] * dt; P[o + 2] += V[o + 2] * dt;
      if (this.moltT[i] > 0) this.moltT[i] = Math.max(0, this.moltT[i] - dt * 2.0);
    }
  };

  /** The local rule for tadpole i (runs once every `frac` steps; dtl = the time it covers). */
  SwarmCreature.prototype._local = function (i, dtl, tmp, tmp2) {
    const n = this.n, P = this.p, o = 3 * i, T = this.T;
    this.stats.updates++;
    const stunned = this.stun[i] > 0, adopted = this.time >= this.adopt[i];
    const t = this.fate[i];
    // neighbours: separation + fate swaps (same element, both adopted)
    const c = 1 / this.cell, M = this.hsize - 1;
    const cx = Math.floor(P[o] * c), cy = Math.floor(P[o + 1] * c), cz = Math.floor(P[o + 2] * c);
    let sx = 0, sy = 0, sz = 0;
    const R2 = this.sepR * this.sepR, S2 = this.swapR * this.swapR;
    let bestJ = -1, bestGain = 0.25;
    let myD = -1;
    if (adopted && !stunned) { this._wellAt(T, t, this.phase, tmp); myD = (P[o] - tmp[0]) ** 2 + (P[o + 1] - tmp[1]) ** 2 + (P[o + 2] - tmp[2]) ** 2; }
    const wi = [tmp[0], tmp[1], tmp[2]];
    let checked = 0;
    for (let ax = -1; ax <= 1; ax++) for (let ay = -1; ay <= 1; ay++) for (let az = -1; az <= 1; az++) {
      for (let j = this.hhead[this._key(cx + ax, cy + ay, cz + az) & M]; j >= 0; j = this.hnext[j]) {
        if (j === i) continue;
        const q = 3 * j, dx = P[o] - P[q], dy = P[o + 1] - P[q + 1], dz = P[o + 2] - P[q + 2], dd = dx * dx + dy * dy + dz * dz;
        if (dd < R2 && dd > 1e-8) {
          const d = Math.sqrt(dd), s = this.sepK * (this.sepR - d) / d;
          sx += dx * s; sy += dy * s; sz += dz * s;
        }
        if (myD >= 0 && checked < 8 && dd < S2 && this.elem[j] === this.elem[i] && this.stun[j] <= 0 && this.time >= this.adopt[j]) {
          checked++;
          const tj = this.fate[j];
          this._wellAt(T, tj, this.phase, tmp2);
          const dj = (P[q] - tmp2[0]) ** 2 + (P[q + 1] - tmp2[1]) ** 2 + (P[q + 2] - tmp2[2]) ** 2;
          const xi = (P[o] - tmp2[0]) ** 2 + (P[o + 1] - tmp2[1]) ** 2 + (P[o + 2] - tmp2[2]) ** 2;
          const xj = (P[q] - wi[0]) ** 2 + (P[q + 1] - wi[1]) ** 2 + (P[q + 2] - wi[2]) ** 2;
          // swapping a tadpole onto a well of another element would cost a molt: only same-element wells trade
          const ok = T.elem[t] === T.elem[tj] || (T.elem[tj] === this.elem[i] && T.elem[t] === this.elem[j]);
          const gain = myD + dj - xi - xj;
          if (ok && gain > bestGain) { bestGain = gain; bestJ = j; }
        }
      }
    }
    this.sep[o] = sx; this.sep[o + 1] = sy; this.sep[o + 2] = sz;
    if (bestJ >= 0) { const tj = this.fate[bestJ]; this.fate[bestJ] = t; this.fate[i] = tj; this.stats.swaps++; }
    if (stunned || !adopted) return;
    const ti = this.fate[i];
    // molt: a crystal of the wrong element re-forms into its well's element (designed composition, lossless)
    if (this.elem[i] !== T.elem[ti] && this.rand() < this.moltP) {
      this.prevElem[i] = this.elem[i]; this.elem[i] = T.elem[ti]; this.moltT[i] = 1; this.stats.molts++;
    }
    this.dom[i] = T.slot[ti]; this.tier[i] = this.elem[i] === 0 ? T.tier[ti] : 0;
    // look: prism, spindle, normal and facing ease toward the well's (stale between updates: a low-pass)
    const k = 1 - Math.exp(-4 * dtl);
    for (let a = 0; a < 3; a++) this.h[o + a] += (T.h[3 * ti + a] - this.h[o + a]) * k;
    this.sp[2 * i] += (T.sp[2 * ti] - this.sp[2 * i]) * k; this.sp[2 * i + 1] += (T.sp[2 * ti + 1] - this.sp[2 * i + 1]) * k;
    const j = T.j[ti], NS = T.d.NS;
    for (let a = 0; a < 3; a++) this.nr[o + a] += (NS[3 * j + a] - this.nr[o + a]) * k;
    this._faceTarget(T, ti, this.phase, tmp, 0);
    // a tadpole in transit faces where it swims
    const V = this.v, vs = Math.hypot(V[o], V[o + 1], V[o + 2]), wv = clamp((vs - 6) / 20, 0, 0.8);
    let fx = tmp[0] * (1 - wv), fy = tmp[1] * (1 - wv), fz = tmp[2] * (1 - wv);
    if (vs > 1e-6) { fx += wv * V[o] / vs; fy += wv * V[o + 1] / vs; fz += wv * V[o + 2] / vs; }
    const kf = 1 - Math.exp(-6 * dtl);
    fx = this.f[o] + (fx - this.f[o]) * kf; fy = this.f[o + 1] + (fy - this.f[o + 1]) * kf; fz = this.f[o + 2] + (fz - this.f[o + 2]) * kf;
    const fl = Math.hypot(fx, fy, fz) || 1;
    this.f[o] = fx / fl; this.f[o + 1] = fy / fl; this.f[o + 2] = fz / fl;
  };

  // ---- strikes ----------------------------------------------------------------------------------------------------
  /** Knock loose every tadpole within `radius` (world) of a world point. Returns how many. Some crystals crack. */
  SwarmCreature.prototype.hit = function (point, radius, opt) {
    opt = opt || {};
    const B = this.basis(), s = this.scale, n = this.n, P = this.p, V = this.v;
    const dx = point[0] - this.position[0], dy = point[1] - this.position[1], dz = point[2] - this.position[2];
    // swim = B^T (world - pos) / scale ; B is row-major with columns = axes
    const hx = (B[0] * dx + B[3] * dy + B[6] * dz) / s, hy = (B[1] * dx + B[4] * dy + B[7] * dz) / s, hz = (B[2] * dx + B[5] * dy + B[8] * dz) / s;
    const r = radius / s, crack = opt.crack != null ? opt.crack : 0.5, kick = opt.kick || 40;
    let count = 0;
    for (let i = 0; i < n; i++) {
      const o = 3 * i, ex = P[o] - hx, ey = P[o + 1] - hy, ez = P[o + 2] - hz, d = Math.hypot(ex, ey, ez);
      if (d > r) continue;
      count++;
      const fall = 1 - d / r, sp = kick * (0.4 + 0.6 * fall) / Math.max(d, 1e-3);
      V[o] += ex * sp + (this.rand() - 0.5) * 8; V[o + 1] += ey * sp + (this.rand() - 0.5) * 8; V[o + 2] += ez * sp + (this.rand() - 0.5) * 8;
      this.stun[i] = 0.5 + 0.5 * fall + 0.2 * this.rand();
      if (this.rand() < crack * fall + 0.1) {
        const e = (this.elem[i] + 1 + Math.floor(this.rand() * 3)) % 4;
        this.prevElem[i] = this.elem[i]; this.elem[i] = e; this.moltT[i] = 1;
      }
    }
    return count;
  };

  // ---- read-outs --------------------------------------------------------------------------------------------------
  /** The swarm in the PLAN frame for swarm_loss.js: { p, elem, dom, h, tier, f, sp }. */
  SwarmCreature.prototype.lossState = function () {
    const n = this.n, d = this.T.d, b = new Float32Array(3);
    const x = { p: [], elem: Array.from(this.elem), dom: Array.from(this.dom), h: [], tier: Array.from(this.tier), f: [], sp: [] };
    for (let i = 0; i < n; i++) {
      const o = 3 * i;
      toPlan(d, this.p[o], this.p[o + 1], this.p[o + 2], b, 0); x.p.push([b[0], b[1], b[2]]);
      toPlan(d, this.f[o], this.f[o + 1], this.f[o + 2], b, 0); x.f.push([b[0], b[1], b[2]]);
      x.h.push([this.h[o], this.h[o + 1], this.h[o + 2]]); x.sp.push([this.sp[2 * i], this.sp[2 * i + 1]]);
    }
    return x;
  };

  /** World-space tadpoles: heart positions, unit quaternions (local x = forward, y = side, z = normal), prism
   *  half-extents (world), prism centres, colours (molt flash included), elements. Typed arrays, reused. */
  SwarmCreature.prototype.units = function () {
    const n = this.n;
    if (!this._u) this._u = { count: n, pos: new Float32Array(3 * n), quat: new Float32Array(4 * n), half: new Float32Array(3 * n),
      prism: new Float32Array(3 * n), colour: new Float32Array(3 * n), heartR: new Float32Array(n), elem: this.elem, dom: this.dom, tier: this.tier };
    const U = this._u, B = this.basis(), s = this.scale, X = this.position;
    const M = new Float64Array(9);
    for (let i = 0; i < n; i++) {
      const o = 3 * i;
      const wx = B[0] * this.p[o] + B[1] * this.p[o + 1] + B[2] * this.p[o + 2];
      const wy = B[3] * this.p[o] + B[4] * this.p[o + 1] + B[5] * this.p[o + 2];
      const wz = B[6] * this.p[o] + B[7] * this.p[o + 1] + B[8] * this.p[o + 2];
      U.pos[o] = X[0] + s * wx; U.pos[o + 1] = X[1] + s * wy; U.pos[o + 2] = X[2] + s * wz;
      // unit frame [f, s, n] in world
      const fl = [this.f[o], this.f[o + 1], this.f[o + 2]];
      let nl = [this.nr[o], this.nr[o + 1], this.nr[o + 2]];
      const dn = nl[0] * fl[0] + nl[1] * fl[1] + nl[2] * fl[2];
      nl = [nl[0] - dn * fl[0], nl[1] - dn * fl[1], nl[2] - dn * fl[2]];
      let ln = Math.hypot(nl[0], nl[1], nl[2]);
      if (ln < 1e-4) { nl = Math.abs(fl[1]) < 0.9 ? [-fl[2], 0, fl[0]] : [0, fl[2], -fl[1]]; ln = Math.hypot(nl[0], nl[1], nl[2]) || 1; }
      nl = nl.map(v => v / ln);
      const sl = [nl[1] * fl[2] - nl[2] * fl[1], nl[2] * fl[0] - nl[0] * fl[2], nl[0] * fl[1] - nl[1] * fl[0]];
      const W = v => [B[0] * v[0] + B[1] * v[1] + B[2] * v[2], B[3] * v[0] + B[4] * v[1] + B[5] * v[2], B[6] * v[0] + B[7] * v[1] + B[8] * v[2]];
      const fw = W(fl), sw = W(sl), nw = W(nl);
      M[0] = fw[0]; M[3] = fw[1]; M[6] = fw[2]; M[1] = sw[0]; M[4] = sw[1]; M[7] = sw[2]; M[2] = nw[0]; M[5] = nw[1]; M[8] = nw[2];
      quatFromM(M, U.quat, 4 * i);
      const e = this.elem[i], r = HEART_R[e];
      const shield = this.tier[i] === 2 && e === 0 ? 1 / 3 : 1;
      U.half[o] = s * this.h[o] * shield; U.half[o + 1] = s * this.h[o + 1] * shield; U.half[o + 2] = s * this.h[o + 2] * shield;
      const back = s * (r + this.sp[2 * i] + this.h[o] * shield);
      U.prism[o] = U.pos[o] - fw[0] * back; U.prism[o + 1] = U.pos[o + 1] - fw[1] * back; U.prism[o + 2] = U.pos[o + 2] - fw[2] * back;
      U.heartR[i] = s * r;
      const m = this.moltT[i], c0 = COL[this.prevElem[i]], c1 = COL[e], flash = Math.sin(Math.PI * m) * 0.6;
      const stunDim = this.stun[i] > 0 ? 0.65 : 1;
      for (let a = 0; a < 3; a++) U.colour[o + a] = Math.min(1, ((c0[a] * m + c1[a] * (1 - m)) * (1 - flash) + flash) * stunDim);
    }
    return U;
  };
  function quatFromM(m, q, k) {          // row-major 3x3 rotation -> quaternion (x, y, z, w)
    const tr = m[0] + m[4] + m[8];
    let x, y, z, w;
    if (tr > 0) { const s = 0.5 / Math.sqrt(tr + 1); w = 0.25 / s; x = (m[7] - m[5]) * s; y = (m[2] - m[6]) * s; z = (m[3] - m[1]) * s; }
    else if (m[0] > m[4] && m[0] > m[8]) { const s = 2 * Math.sqrt(1 + m[0] - m[4] - m[8]); w = (m[7] - m[5]) / s; x = 0.25 * s; y = (m[1] + m[3]) / s; z = (m[2] + m[6]) / s; }
    else if (m[4] > m[8]) { const s = 2 * Math.sqrt(1 + m[4] - m[0] - m[8]); w = (m[2] - m[6]) / s; x = (m[1] + m[3]) / s; y = 0.25 * s; z = (m[5] + m[7]) / s; }
    else { const s = 2 * Math.sqrt(1 + m[8] - m[0] - m[4]); w = (m[3] - m[1]) / s; x = (m[2] + m[6]) / s; y = (m[5] + m[7]) / s; z = 0.25 * s; }
    const l = Math.hypot(x, y, z, w) || 1;
    q[k] = x / l; q[k + 1] = y / l; q[k + 2] = z / l; q[k + 3] = w / l;
  }

  /** The body's world centre (the swarm centroid) and a bounding radius. */
  SwarmCreature.prototype.bounds = function () {
    const U = this.units(), n = this.n, c = [0, 0, 0];
    for (let i = 0; i < n; i++) { c[0] += U.pos[3 * i]; c[1] += U.pos[3 * i + 1]; c[2] += U.pos[3 * i + 2]; }
    c[0] /= n; c[1] /= n; c[2] /= n;
    let r = 0; for (let i = 0; i < n; i++) r = Math.max(r, Math.hypot(U.pos[3 * i] - c[0], U.pos[3 * i + 1] - c[1], U.pos[3 * i + 2] - c[2]));
    return { centre: c, radius: r };
  };

  // ---- three.js helper --------------------------------------------------------------------------------------------
  /** A THREE.Group with two InstancedMeshes (prisms, hearts). Call sync() after step() to write the instances. */
  SwarmCreature.prototype.mesh = function (THREE, opt) {
    opt = opt || {};
    const n = this.n, g = new THREE.Group();
    const pm = new THREE.MeshStandardMaterial({ roughness: 0.45, metalness: 0.15, flatShading: true });
    const hm = new THREE.MeshStandardMaterial({ roughness: 0.2, metalness: 0.1, flatShading: true, emissive: 0x111111 });
    const prisms = new THREE.InstancedMesh(new THREE.BoxGeometry(2, 2, 2), pm, n);
    const hearts = new THREE.InstancedMesh(new THREE.OctahedronGeometry(1, 0), hm, n);
    for (const im of [prisms, hearts]) {
      im.instanceMatrix.setUsage(THREE.DynamicDrawUsage); im.frustumCulled = false;
      im.setColorAt(0, new THREE.Color(1, 1, 1));
      g.add(im);
    }
    this._three = { THREE, g, prisms, hearts, col: new THREE.Color() };
    this.sync();
    return g;
  };
  SwarmCreature.prototype.sync = function () {
    const R = this._three; if (!R) return;
    const U = this.units(), n = this.n, A = R.prisms.instanceMatrix.array, H = R.hearts.instanceMatrix.array;
    const pc = R.prisms.instanceColor.array, hc = R.hearts.instanceColor.array;
    for (let i = 0; i < n; i++) {
      const q = 4 * i, x = U.quat[q], y = U.quat[q + 1], z = U.quat[q + 2], w = U.quat[q + 3];
      // rotation matrix columns from the quaternion
      const c0 = [1 - 2 * (y * y + z * z), 2 * (x * y + z * w), 2 * (x * z - y * w)];
      const c1 = [2 * (x * y - z * w), 1 - 2 * (x * x + z * z), 2 * (y * z + x * w)];
      const c2 = [2 * (x * z + y * w), 2 * (y * z - x * w), 1 - 2 * (x * x + y * y)];
      const o = 16 * i, hx = U.half[3 * i], hy = U.half[3 * i + 1], hz = U.half[3 * i + 2];
      A[o] = c0[0] * hx; A[o + 1] = c0[1] * hx; A[o + 2] = c0[2] * hx; A[o + 3] = 0;
      A[o + 4] = c1[0] * hy; A[o + 5] = c1[1] * hy; A[o + 6] = c1[2] * hy; A[o + 7] = 0;
      A[o + 8] = c2[0] * hz; A[o + 9] = c2[1] * hz; A[o + 10] = c2[2] * hz; A[o + 11] = 0;
      A[o + 12] = U.prism[3 * i]; A[o + 13] = U.prism[3 * i + 1]; A[o + 14] = U.prism[3 * i + 2]; A[o + 15] = 1;
      const r = U.heartR[i];
      H[o] = c0[0] * r; H[o + 1] = c0[1] * r; H[o + 2] = c0[2] * r; H[o + 3] = 0;
      H[o + 4] = c1[0] * r; H[o + 5] = c1[1] * r; H[o + 6] = c1[2] * r; H[o + 7] = 0;
      H[o + 8] = c2[0] * r; H[o + 9] = c2[1] * r; H[o + 10] = c2[2] * r; H[o + 11] = 0;
      H[o + 12] = U.pos[3 * i]; H[o + 13] = U.pos[3 * i + 1]; H[o + 14] = U.pos[3 * i + 2]; H[o + 15] = 1;
      for (let a = 0; a < 3; a++) { const cc = U.colour[3 * i + a]; pc[3 * i + a] = cc * 0.85; hc[3 * i + a] = Math.min(1, cc * 1.25 + 0.1); }
    }
    R.prisms.instanceMatrix.needsUpdate = true; R.hearts.instanceMatrix.needsUpdate = true;
    R.prisms.instanceColor.needsUpdate = true; R.hearts.instanceColor.needsUpdate = true;
  };

  SwarmCreature.ELEMENTS = ELEM_NAMES;
  SwarmCreature.ELEMENT_COLOUR = ELEMENT_COLOUR;
  SwarmCreature.PLANS = { mass: 'Whale', space: 'Jellyfish', charge: 'Pufferfish', time: 'Dragonfly' };
  SwarmCreature.planData = planData;

  if (typeof module !== 'undefined' && module.exports) module.exports = SwarmCreature;
  if (root) root.SwarmCreature = SwarmCreature;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
